/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class {{self.name}}
 *
 * This file has been generated by dub {{dub.version}}.
 */
{% for h in self:headers() do %}
#include "{{h.path}}"
{% end %}

{% for method in self:methods() do %}
{% end %}
