/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for library {{lib.name}}
 *
 * This file has been generated by dub {{dub.version}}.
 */
#include "dub/dub.h"
{% for header in lib:constHeaders() do %}
#include "{{self:header(header)}}"
{% end %}

extern "C" {
{% for _, class in ipairs(classes) do %}
int luaopen_{{self:name(class)}}(lua_State *L);
{% end %}
}

{% if lib.has_constants then %}
// --=============================================== CONSTANTS
static const struct dub_const_Reg {{lib.name}}_const[] = {
{% for const in lib:constants() do %}
  { {{string.format('%-15s, %-20s', '"'.. self:constName(const) ..'"', const)}} },
{% end %}
  { NULL, NULL},
};
{% end %}

extern "C" int luaopen_{{lib.name}}(lua_State *L) {
{% for _, class in ipairs(classes) do %}
  luaopen_{{self:name(class)}}(L);
{% end %}

{% if lib.has_constants or lib.has_functions then %}
  // Create the table which will contain all the constants
  lua_getfield(L, LUA_GLOBALSINDEX, "{{lib.name}}");
  if (lua_isnil(L, -1)) {
    // no global table called {{lib.name}}
    lua_pop(L, 1);
    lua_newtable(L);
    // <lib>
    lua_pushvalue(L, -1);
    // <lib> <lib>
    // _G.{{lib.name}} = <lib>
    lua_setglobal(L, "{{lib.name}}");
    // <lib>
  }
  // <lib>
{% end %}
{% if lib.has_constants then %}
  // register global constants
  dub_register_const(L, {{lib.name}}_const);
{% end %}
  return 0;
}
