/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for library {{lib_name}}
 *
 * This file has been generated by dub {{dub.version}}.
 */
#include "dub/dub.h"

extern "C" {
{% for _, class in ipairs(list) do %}
int luaopen_{{self:name(class)}}(lua_State *L);
{% end %}
}

extern "C" int luaopen_{{lib_name}}(lua_State *L) {
{% for _, class in ipairs(list) do %}
  luaopen_{{self:name(class)}}(L);
{% end %}
  return 0;
}
