lubyk: /Users/gaspard/git/lubyk/modules/b2/bind/b2Math.h File Reference
/Users/gaspard/git/lubyk/modules/b2/bind/b2Math.h File Reference
#include <Box2D/Common/b2Settings.h>
#include <cmath>
#include <cfloat>
#include <cstddef>
#include <limits>
Classes
struct b2Vec2
A 2D column vector.
struct b2Vec3
A 2D column vector with 3 elements.
struct b2Mat22
A 2-by-2 matrix. Stored in column-major order.
struct b2Mat33
A 3-by-3 matrix. Stored in column-major order.
struct b2Rot
Rotation.
struct b2Transform
struct b2Sweep
Defines
#define b2Sqrt(x) std::sqrt(x)
#define b2Atan2(y, x) std::atan2(y, x)
Functions
bool b2IsValid (float32 x)
float32 b2InvSqrt (float32 x)
This is a approximate yet fast inverse square-root.
float32 b2Dot (const b2Vec2 &a, const b2Vec2 &b)
Perform the dot product on two vectors.
float32 b2Cross (const b2Vec2 &a, const b2Vec2 &b)
Perform the cross product on two vectors. In 2D this produces a scalar.
b2Vec2 b2Cross (const b2Vec2 &a, float32 s)
b2Vec2 b2Cross (float32 s, const b2Vec2 &a)
b2Vec2 b2Mul (const b2Mat22 &A, const b2Vec2 &v)
b2Vec2 b2MulT (const b2Mat22 &A, const b2Vec2 &v)
b2Vec2 operator+ (const b2Vec2 &a, const b2Vec2 &b)
Add two vectors component-wise.
b2Vec2 operator- (const b2Vec2 &a, const b2Vec2 &b)
Subtract two vectors component-wise.
b2Vec2 operator* (float32 s, const b2Vec2 &a)
bool operator== (const b2Vec2 &a, const b2Vec2 &b)
float32 b2Distance (const b2Vec2 &a, const b2Vec2 &b)
float32 b2DistanceSquared (const b2Vec2 &a, const b2Vec2 &b)
b2Vec3 operator* (float32 s, const b2Vec3 &a)
b2Vec3 operator+ (const b2Vec3 &a, const b2Vec3 &b)
Add two vectors component-wise.
b2Vec3 operator- (const b2Vec3 &a, const b2Vec3 &b)
Subtract two vectors component-wise.
float32 b2Dot (const b2Vec3 &a, const b2Vec3 &b)
Perform the dot product on two vectors.
b2Vec3 b2Cross (const b2Vec3 &a, const b2Vec3 &b)
Perform the cross product on two vectors.
b2Mat22 operator+ (const b2Mat22 &A, const b2Mat22 &B)
b2Mat22 b2Mul (const b2Mat22 &A, const b2Mat22 &B)
b2Mat22 b2MulT (const b2Mat22 &A, const b2Mat22 &B)
b2Vec3 b2Mul (const b2Mat33 &A, const b2Vec3 &v)
Multiply a matrix times a vector.
b2Vec2 b2Mul22 (const b2Mat33 &A, const b2Vec2 &v)
Multiply a matrix times a vector.
b2Rot b2Mul (const b2Rot &q, const b2Rot &r)
Multiply two rotations: q * r.
b2Rot b2MulT (const b2Rot &q, const b2Rot &r)
Transpose multiply two rotations: qT * r.
b2Vec2 b2Mul (const b2Rot &q, const b2Vec2 &v)
Rotate a vector.
b2Vec2 b2MulT (const b2Rot &q, const b2Vec2 &v)
Inverse rotate a vector.
b2Vec2 b2Mul (const b2Transform &T, const b2Vec2 &v)
b2Vec2 b2MulT (const b2Transform &T, const b2Vec2 &v)
b2Transform b2Mul (const b2Transform &A, const b2Transform &B)
b2Transform b2MulT (const b2Transform &A, const b2Transform &B)
template<typename T >
T b2Abs (T a)
b2Vec2 b2Abs (const b2Vec2 &a)
b2Mat22 b2Abs (const b2Mat22 &A)
template<typename T >
T b2Min (T a, T b)
b2Vec2 b2Min (const b2Vec2 &a, const b2Vec2 &b)
template<typename T >
T b2Max (T a, T b)
b2Vec2 b2Max (const b2Vec2 &a, const b2Vec2 &b)
template<typename T >
T b2Clamp (T a, T low, T high)
b2Vec2 b2Clamp (const b2Vec2 &a, const b2Vec2 &low, const b2Vec2 &high)
template<typename T >
void b2Swap (T &a, T &b)
uint32 b2NextPowerOfTwo (uint32 x)
bool b2IsPowerOfTwo (uint32 x)
Variables
const b2Vec2 b2Vec2_zero
Useful constant.
Define Documentation
#define b2Atan2 (y, x) std::atan2(y, x)
Definition at line 61 of file b2Math.h.
Referenced by b2Rot::GetAngle().
#define b2Sqrt (x) std::sqrt(x)
Definition at line 60 of file b2Math.h.
Referenced by b2Vec2::Length().
Function Documentation
template<typename T > T b2Abs (T a) [inline]
Definition at line 627 of file b2Math.h.
References a, and T.
Referenced by b2Abs(), and b2DynamicTree::RayCast().
b2Vec2 b2Abs (const b2Vec2 & a) [inline]
Definition at line 632 of file b2Math.h.
References b2Abs(), b2Vec2::x, and b2Vec2::y.
b2Mat22 b2Abs (const b2Mat22 & A) [inline]
Definition at line 637 of file b2Math.h.
References b2Abs(), b2Mat22::ex, and b2Mat22::ey.
template<typename T > T b2Clamp (T a, T low, T high) [inline]
Definition at line 665 of file b2Math.h.
References b2Max(), and b2Min().
b2Vec2 b2Clamp (const b2Vec2 & a, const b2Vec2 & low, const b2Vec2 & high) [inline]
Definition at line 670 of file b2Math.h.
References b2Max(), and b2Min().
float32 b2Cross (const b2Vec2 & a, const b2Vec2 & b) [inline]
Perform the cross product on two vectors. In 2D this produces a scalar.
Definition at line 423 of file b2Math.h.
References b2Vec2::x, and b2Vec2::y.
Referenced by b2Body::ApplyForce(), b2Body::ApplyLinearImpulse(), b2Body::GetLinearVelocityFromWorldPoint(), and b2DynamicTree::RayCast().
b2Vec2 b2Cross (const b2Vec2 & a, float32 s) [inline]
Perform the cross product on a vector and a scalar. In 2D this produces a vector.
Definition at line 430 of file b2Math.h.
References b2Vec2::x, and b2Vec2::y.
b2Vec2 b2Cross (float32 s, const b2Vec2 & a) [inline]
Perform the cross product on a scalar and a vector. In 2D this produces a vector.
Definition at line 437 of file b2Math.h.
References b2Vec2::x, and b2Vec2::y.
b2Vec3 b2Cross (const b2Vec3 & a, const b2Vec3 & b) [inline]
Perform the cross product on two vectors.
Definition at line 514 of file b2Math.h.
References b2Vec3::x, b2Vec3::y, and b2Vec3::z.
float32 b2Distance (const b2Vec2 & a, const b2Vec2 & b) [inline]
Definition at line 478 of file b2Math.h.
References b, c, and b2Vec2::Length().
float32 b2DistanceSquared (const b2Vec2 & a, const b2Vec2 & b) [inline]
Definition at line 484 of file b2Math.h.
References b, b2Dot(), and c.
float32 b2Dot (const b2Vec2 & a, const b2Vec2 & b) [inline]
Perform the dot product on two vectors.
Definition at line 417 of file b2Math.h.
References b2Vec2::x, and b2Vec2::y.
Referenced by b2DistanceSquared(), b2MulT(), b2Body::GetInertia(), b2Body::GetMassData(), b2DistanceProxy::GetSupport(), b2DistanceProxy::GetSupportVertex(), b2DynamicTree::RayCast(), and b2Body::SetLinearVelocity().
float32 b2Dot (const b2Vec3 & a, const b2Vec3 & b) [inline]
Perform the dot product on two vectors.
Definition at line 508 of file b2Math.h.
References b2Vec3::x, b2Vec3::y, and b2Vec3::z.
float32 b2InvSqrt (float32 x) [inline]
This is a approximate yet fast inverse square-root.
Definition at line 44 of file b2Math.h.
bool b2IsPowerOfTwo (uint32 x) [inline]
Definition at line 697 of file b2Math.h.
References result.
bool b2IsValid (float32 x) [inline]
This function is used to ensure that a floating point number is not a NaN or infinity.
Definition at line 31 of file b2Math.h.
Referenced by b2Vec2::IsValid(), and b2Fixture::SetDensity().
template<typename T > T b2Max (T a, T b) [inline]
Definition at line 654 of file b2Math.h.
References b.
Referenced by b2Clamp(), b2Max(), b2AABB::Combine(), and b2DynamicTree::RayCast().
b2Vec2 b2Max (const b2Vec2 & a, const b2Vec2 & b) [inline]
Definition at line 659 of file b2Math.h.
References b2Max(), b2Vec2::x, and b2Vec2::y.
template<typename T > T b2Min (T a, T b) [inline]
Definition at line 643 of file b2Math.h.
References b.
Referenced by b2Clamp(), b2Min(), b2AABB::Combine(), and b2DynamicTree::RayCast().
b2Vec2 b2Min (const b2Vec2 & a, const b2Vec2 & b) [inline]
Definition at line 648 of file b2Math.h.
References b2Min(), b2Vec2::x, and b2Vec2::y.
b2Vec2 b2Mul (const b2Mat22 & A, const b2Vec2 & v) [inline]
Multiply a matrix times a vector. If a rotation matrix is provided, then this transforms the vector from one frame to another.
Definition at line 444 of file b2Math.h.
References b2Mat22::ex, b2Mat22::ey, b2Vec2::x, and b2Vec2::y.
Referenced by b2Body::Advance(), b2Mul(), b2Sweep::GetTransform(), b2Body::GetWorldPoint(), b2Body::GetWorldVector(), and b2Body::SynchronizeTransform().
b2Mat22 b2Mul (const b2Mat22 & A, const b2Mat22 & B) [inline]
Definition at line 525 of file b2Math.h.
References b2Mul(), b2Mat22::ex, and b2Mat22::ey.
b2Vec3 b2Mul (const b2Mat33 & A, const b2Vec3 & v) [inline]
Multiply a matrix times a vector.
Definition at line 539 of file b2Math.h.
References b2Mat33::ex, b2Mat33::ey, b2Mat33::ez, b2Vec3::x, b2Vec3::y, and b2Vec3::z.
b2Rot b2Mul (const b2Rot & q, const b2Rot & r) [inline]
Multiply two rotations: q * r.
Definition at line 551 of file b2Math.h.
References b2Rot::c, and b2Rot::s.
b2Vec2 b2Mul (const b2Rot & q, const b2Vec2 & v) [inline]
Rotate a vector.
Definition at line 577 of file b2Math.h.
References b2Rot::c, b2Rot::s, b2Vec2::x, and b2Vec2::y.
b2Vec2 b2Mul (const b2Transform & T, const b2Vec2 & v) [inline]
Definition at line 588 of file b2Math.h.
References b2Rot::c, b2Transform::p, b2Transform::q, b2Rot::s, b2Vec2::x, and b2Vec2::y.
b2Transform b2Mul (const b2Transform & A, const b2Transform & B) [inline]
Definition at line 608 of file b2Math.h.
References b2Mul(), b2Transform::p, and b2Transform::q.
b2Vec2 b2Mul22 (const b2Mat33 & A, const b2Vec2 & v) [inline]
Multiply a matrix times a vector.
Definition at line 545 of file b2Math.h.
References b2Mat33::ex, b2Mat33::ey, b2Vec2::x, b2Vec3::x, b2Vec2::y, and b2Vec3::y.
b2Vec2 b2MulT (const b2Mat22 & A, const b2Vec2 & v) [inline]
Multiply a matrix transpose times a vector. If a rotation matrix is provided, then this transforms the vector from one frame to another (inverse transform).
Definition at line 451 of file b2Math.h.
References b2Dot(), b2Mat22::ex, and b2Mat22::ey.
Referenced by b2MulT(), b2Body::GetLocalPoint(), and b2Body::GetLocalVector().
b2Mat22 b2MulT (const b2Mat22 & A, const b2Mat22 & B) [inline]
Definition at line 531 of file b2Math.h.
References b2Dot(), b2Mat22::ex, and b2Mat22::ey.
b2Rot b2MulT (const b2Rot & q, const b2Rot & r) [inline]
Transpose multiply two rotations: qT * r.
Definition at line 564 of file b2Math.h.
References b2Rot::c, and b2Rot::s.
b2Vec2 b2MulT (const b2Rot & q, const b2Vec2 & v) [inline]
Inverse rotate a vector.
Definition at line 583 of file b2Math.h.
References b2Rot::c, b2Rot::s, b2Vec2::x, and b2Vec2::y.
b2Vec2 b2MulT (const b2Transform & T, const b2Vec2 & v) [inline]
Definition at line 596 of file b2Math.h.
References b2Rot::c, b2Transform::p, b2Transform::q, b2Rot::s, b2Vec2::x, and b2Vec2::y.
b2Transform b2MulT (const b2Transform & A, const b2Transform & B) [inline]
Definition at line 618 of file b2Math.h.
References b2MulT(), b2Transform::p, and b2Transform::q.
uint32 b2NextPowerOfTwo (uint32 x) [inline]
"Next Largest Power of 2 Given a binary integer value x, the next largest power of 2 can be computed by a SWAR algorithm that recursively "folds" the upper bits into the lower bits. This process yields a bit vector with the same most significant 1 as x, but all 1's below it. Adding 1 to that value yields the next largest power of 2. For a 32-bit value:"
Definition at line 687 of file b2Math.h.
template<typename T > void b2Swap (T & a, T & b) [inline]
Definition at line 675 of file b2Math.h.
References a, b, and T.
b2Vec2 operator* (float32 s, const b2Vec2 & a) [inline]
Definition at line 468 of file b2Math.h.
References b2Vec2::x, and b2Vec2::y.
b2Vec3 operator* (float32 s, const b2Vec3 & a) [inline]
Definition at line 490 of file b2Math.h.
References b2Vec3::x, b2Vec3::y, and b2Vec3::z.
b2Vec2 operator+ (const b2Vec2 & a, const b2Vec2 & b) [inline]
Add two vectors component-wise.
Definition at line 457 of file b2Math.h.
References b2Vec2::x, and b2Vec2::y.
b2Vec3 operator+ (const b2Vec3 & a, const b2Vec3 & b) [inline]
Add two vectors component-wise.
Definition at line 496 of file b2Math.h.
References b2Vec3::x, b2Vec3::y, and b2Vec3::z.
b2Mat22 operator+ (const b2Mat22 & A, const b2Mat22 & B) [inline]
Definition at line 519 of file b2Math.h.
References b2Mat22::ex, and b2Mat22::ey.
b2Vec2 operator- (const b2Vec2 & a, const b2Vec2 & b) [inline]
Subtract two vectors component-wise.
Definition at line 463 of file b2Math.h.
References b2Vec2::x, and b2Vec2::y.
b2Vec3 operator- (const b2Vec3 & a, const b2Vec3 & b) [inline]
Subtract two vectors component-wise.
Definition at line 502 of file b2Math.h.
References b2Vec3::x, b2Vec3::y, and b2Vec3::z.
bool operator== (const b2Vec2 & a, const b2Vec2 & b) [inline]
Definition at line 473 of file b2Math.h.
References b2Vec2::x, and b2Vec2::y.
Variable Documentation
const b2Vec2 b2Vec2_zero
Useful constant.