lubyk: lubyk::Semaphore Class Reference
lubyk::Semaphore Class Reference
#include <semaphore.h>
Inherits lubyk::NonCopyable.
Public Member Functions
Semaphore (int resource_count=0)
~Semaphore ()
void acquire ()
void release ()
void acquire (size_t count)
void release (size_t count)
void acquire_all ()
void release_all ()
Private Attributes
size_t resource_count_
Mutex acquire_mutex_
sem_t * semaphore_
Detailed Description
Definition at line 42 of file semaphore.h.
Constructor & Destructor Documentation
lubyk::Semaphore::Semaphore (int resource_count = 0)
lubyk::Semaphore::~Semaphore ()
Member Function Documentation
void lubyk::Semaphore::acquire () [inline]
Get resource or wait until it is available.
Definition at line 50 of file semaphore.h.
References semaphore_.
Referenced by acquire(), and acquire_all().
void lubyk::Semaphore::acquire (size_t count) [inline]
Acquire multiple resources at the same time.
Definition at line 62 of file semaphore.h.
References acquire(), acquire_mutex_, count, and resource_count_.
void lubyk::Semaphore::acquire_all () [inline]
Acquire all resources protected by this semaphore
Definition at line 81 of file semaphore.h.
References acquire(), and resource_count_.
void lubyk::Semaphore::release () [inline]
Release resource.
Definition at line 56 of file semaphore.h.
References semaphore_.
Referenced by release(), and release_all().
void lubyk::Semaphore::release (size_t count) [inline]
Release multiple resources at the same time.
Definition at line 72 of file semaphore.h.
References count, release(), and resource_count_.
void lubyk::Semaphore::release_all () [inline]
Release all resources previously acquired with a call to 'acquire_all'.
Definition at line 87 of file semaphore.h.
References release(), and resource_count_.
Member Data Documentation
Mutex lubyk::Semaphore::acquire_mutex_ [private]
Definition at line 93 of file semaphore.h.
Referenced by acquire().
size_t lubyk::Semaphore::resource_count_ [private]
Definition at line 92 of file semaphore.h.
Referenced by acquire(), acquire_all(), release(), and release_all().
sem_t* lubyk::Semaphore::semaphore_ [private]
Definition at line 94 of file semaphore.h.
Referenced by acquire(), and release().
The documentation for this class was generated from the following file:
/Users/gaspard/git/lubyk/modules/lubyk/include/lubyk/semaphore.h