lubyk: zmq::Socket Class Reference
zmq::Socket Class Reference
#include <Socket.h>
Inherits lubyk::LuaObject.
Public Member Functions
Socket (int type, lubyk::Worker *worker)
~Socket ()
int fd ()
void setNonBlocking (bool non_blocking)
void setsockopt (int type, lua_State *L)
void bind (const char *location)
int bind (int min_port=2000, int max_port=20000, int retries=100)
void connect (const char *location)
bool hasEvent (int event)
LuaStackSize recv (lua_State *L)
bool send (lua_State *L)
bool rawSend (lua_State *L)
LuaStackSize request (lua_State *L)
const char * location ()
int port ()
const char * type () const
Private Member Functions
void throw_bind_error (int err, const char *location)
void throw_recv_error (int err)
void throw_poll_error (int err)
void throw_send_error (int err)
Private Attributes
void * socket_
std::string location_
int type_
int send_flags_
TimeRef time_ref_
Friends
class Poller
Detailed Description
ZeroMQ Socket.
Bindings info:
lib_name:'Socket_core' string_format:'%s (%s)' string_args:'(*userdata)->location(), (*userdata)->type()'
Definition at line 54 of file Socket.h.
Constructor & Destructor Documentation
zmq::Socket::Socket (int type, lubyk::Worker * worker) [inline]
The worker is not provided by LuaObject before luaInit is called. This call happens after full object construction. We need the worker to set the zmq context, so we pass it as argument.
Definition at line 70 of file Socket.h.
References lubyk::Worker::zmq_context_, and lubyk::Worker::zmq_context_refcount_.
zmq::Socket::~Socket () [inline]
Definition at line 100 of file Socket.h.
Member Function Documentation
void zmq::Socket::bind (const char * location) [inline]
Bind a service to a location like "tcp://\*:5500" Should NOT be used while in a request() or recv().
Definition at line 180 of file Socket.h.
int zmq::Socket::bind (int min_port = 2000, int max_port = 20000, int retries = 100) [inline]
Bind to a random port. Should NOT be used while in a request() or recv().
Definition at line 190 of file Socket.h.
References buffer.
void zmq::Socket::connect (const char * location) [inline]
Connect to a server.
Definition at line 211 of file Socket.h.
int zmq::Socket::fd () [inline]
Definition at line 108 of file Socket.h.
Referenced by zmq::Poller::modify().
bool zmq::Socket::hasEvent (int event) [inline]
Return true if the socket responds to the given event. This has to be used when we do not use zmq_poll but some external poll/select on the file descriptor.
Definition at line 221 of file Socket.h.
const char* zmq::Socket::location () [inline]
Definition at line 359 of file Socket.h.
int zmq::Socket::port () [inline]
Definition at line 363 of file Socket.h.
References pos.
bool zmq::Socket::rawSend (lua_State * L) [inline]
Sends raw bytes without using msgpack.
Returns:
false in case the send buffer is full.
Definition at line 275 of file Socket.h.
References data, and size.
LuaStackSize zmq::Socket::recv (lua_State * L) [inline]
Receive a message (blocks). Should NOT be used while already in a request() or recv(). For a server, this should typically be used inside the loop. We pass the lua_State to avoid mixing thread contexts.
Definition at line 235 of file Socket.h.
References msgpack_bin_to_lua().
LuaStackSize zmq::Socket::request (lua_State * L) [inline]
Request = remote call. Can be used by multiple threads.
Definition at line 292 of file Socket.h.
References buffer, msgpack_sbuffer::data, free_msgpack_msg(), msgpack_bin_to_lua(), msgpack_lua_to_bin(), msgpack_sbuffer::size, and start.
bool zmq::Socket::send (lua_State * L) [inline]
Send a message packed with msgpack. Varying parameters.
Returns:
false in case the send buffer is full.
Definition at line 255 of file Socket.h.
References buffer, msgpack_sbuffer::data, free_msgpack_msg(), msgpack_lua_to_bin(), and msgpack_sbuffer::size.
void zmq::Socket::setNonBlocking (bool non_blocking) [inline]
Definition at line 117 of file Socket.h.
void zmq::Socket::setsockopt (int type, lua_State * L) [inline]
Set socket options.
Definition at line 127 of file Socket.h.
References status, and str.
void zmq::Socket::throw_bind_error (int err, const char * location) [inline, private]
Definition at line 391 of file Socket.h.
References type.
void zmq::Socket::throw_poll_error (int err) [inline, private]
Definition at line 427 of file Socket.h.
void zmq::Socket::throw_recv_error (int err) [inline, private]
Definition at line 411 of file Socket.h.
References type.
void zmq::Socket::throw_send_error (int err) [inline, private]
Definition at line 438 of file Socket.h.
References type.
const char* zmq::Socket::type () const [inline]
Return a string representing the socket type.
Definition at line 374 of file Socket.h.
Friends And Related Function Documentation
friend class Poller [friend]
Definition at line 56 of file Socket.h.
Member Data Documentation
std::string zmq::Socket::location_ [private]
Definition at line 58 of file Socket.h.
int zmq::Socket::send_flags_ [private]
Definition at line 60 of file Socket.h.
void* zmq::Socket::socket_ [private]
Definition at line 57 of file Socket.h.
Referenced by zmq::Poller::add(), and zmq::Poller::modify().
TimeRef zmq::Socket::time_ref_ [private]
Timer used for timeout in request.
Definition at line 64 of file Socket.h.
int zmq::Socket::type_ [private]
Definition at line 59 of file Socket.h.
The documentation for this class was generated from the following file:
/Users/gaspard/git/lubyk/modules/zmq/include/zmq/Socket.h