lubyk: b2Body Class Reference
b2Body Class Reference
A rigid body. These are created via b2World::CreateBody.
#include <b2Body.h>
Public Member Functions
b2Fixture * CreateFixture (const b2FixtureDef *def)
b2Fixture * CreateFixture (const b2Shape *shape, float32 density)
void DestroyFixture (b2Fixture *fixture)
void SetTransform (const b2Vec2 &position, float32 angle)
const b2Transform & GetTransform () const
const b2Vec2 & GetPosition () const
float32 GetAngle () const
const b2Vec2 & GetWorldCenter () const
Get the world position of the center of mass.
const b2Vec2 & GetLocalCenter () const
Get the local position of the center of mass.
void SetLinearVelocity (const b2Vec2 &v)
b2Vec2 GetLinearVelocity () const
void SetAngularVelocity (float32 omega)
float32 GetAngularVelocity () const
void ApplyForce (const b2Vec2 &force, const b2Vec2 &point)
void ApplyForceToCenter (const b2Vec2 &force)
void ApplyTorque (float32 torque)
void ApplyLinearImpulse (const b2Vec2 &impulse, const b2Vec2 &point)
void ApplyAngularImpulse (float32 impulse)
float32 GetMass () const
float32 GetInertia () const
void GetMassData (b2MassData *data) const
void SetMassData (const b2MassData *data)
void ResetMassData ()
b2Vec2 GetWorldPoint (const b2Vec2 &localPoint) const
b2Vec2 GetWorldVector (const b2Vec2 &localVector) const
b2Vec2 GetLocalPoint (const b2Vec2 &worldPoint) const
b2Vec2 GetLocalVector (const b2Vec2 &worldVector) const
b2Vec2 GetLinearVelocityFromWorldPoint (const b2Vec2 &worldPoint) const
b2Vec2 GetLinearVelocityFromLocalPoint (const b2Vec2 &localPoint) const
float32 GetLinearDamping () const
Get the linear damping of the body.
void SetLinearDamping (float32 linearDamping)
Set the linear damping of the body.
float32 GetAngularDamping () const
Get the angular damping of the body.
void SetAngularDamping (float32 angularDamping)
Set the angular damping of the body.
float32 GetGravityScale () const
Get the gravity scale of the body.
void SetGravityScale (float32 scale)
Set the gravity scale of the body.
void SetType (b2BodyType type)
Set the type of this body. This may alter the mass and velocity.
b2BodyType GetType () const
Get the type of this body.
void SetBullet (bool flag)
Should this body be treated like a bullet for continuous collision detection?
bool IsBullet () const
Is this body treated like a bullet for continuous collision detection?
void SetSleepingAllowed (bool flag)
bool IsSleepingAllowed () const
Is this body allowed to sleep.
void SetAwake (bool flag)
bool IsAwake () const
void SetActive (bool flag)
bool IsActive () const
Get the active state of the body.
void SetFixedRotation (bool flag)
bool IsFixedRotation () const
Does this body have fixed rotation?
b2Fixture * GetFixtureList ()
Get the list of all fixtures attached to this body.
const b2Fixture * GetFixtureList () const
b2JointEdge * GetJointList ()
Get the list of all joints attached to this body.
const b2JointEdge * GetJointList () const
b2ContactEdge * GetContactList ()
const b2ContactEdge * GetContactList () const
b2Body * GetNext ()
Get the next body in the world's body list.
const b2Body * GetNext () const
void * GetUserData () const
Get the user data pointer that was provided in the body definition.
void SetUserData (void *data)
Set the user data. Use this to store your application specific data.
b2World * GetWorld ()
Get the parent world of this body.
const b2World * GetWorld () const
void Dump ()
Dump this body to a log file.
Private Types
enum {
e_islandFlag = 0x0001, e_awakeFlag = 0x0002, e_autoSleepFlag = 0x0004, e_bulletFlag = 0x0008,
e_fixedRotationFlag = 0x0010, e_activeFlag = 0x0020, e_toiFlag = 0x0040
}
Private Member Functions
b2Body (const b2BodyDef *bd, b2World *world)
~b2Body ()
void SynchronizeFixtures ()
void SynchronizeTransform ()
bool ShouldCollide (const b2Body *other) const
void Advance (float32 t)
Private Attributes
b2BodyType m_type
uint16 m_flags
int32 m_islandIndex
b2Transform m_xf
b2Sweep m_sweep
b2Vec2 m_linearVelocity
float32 m_angularVelocity
b2Vec2 m_force
float32 m_torque
b2World * m_world
b2Body * m_prev
b2Body * m_next
b2Fixture * m_fixtureList
int32 m_fixtureCount
b2JointEdge * m_jointList
b2ContactEdge * m_contactList
float32 m_mass
float32 m_invMass
float32 m_I
float32 m_invI
float32 m_linearDamping
float32 m_angularDamping
float32 m_gravityScale
float32 m_sleepTime
void * m_userData
Friends
class b2World
class b2Island
class b2ContactManager
class b2ContactSolver
class b2Contact
class b2DistanceJoint
class b2GearJoint
class b2WheelJoint
class b2MouseJoint
class b2PrismaticJoint
class b2PulleyJoint
class b2RevoluteJoint
class b2WeldJoint
class b2FrictionJoint
class b2RopeJoint
Detailed Description
A rigid body. These are created via b2World::CreateBody.
Definition at line 126 of file b2Body.h.
Member Enumeration Documentation
anonymous enum [private]
Enumerator:
e_islandFlag
e_awakeFlag
e_autoSleepFlag
e_bulletFlag
e_fixedRotationFlag
e_activeFlag
e_toiFlag
Definition at line 401 of file b2Body.h.
Constructor & Destructor Documentation
b2Body::b2Body (const b2BodyDef * bd, b2World * world) [private]
b2Body::~b2Body () [private]
Member Function Documentation
void b2Body::Advance (float32 t) [inline, private]
Definition at line 826 of file b2Body.h.
References b2Sweep::a, b2Sweep::a0, b2Sweep::Advance(), b2Mul(), b2Sweep::c, b2Sweep::c0, b2Sweep::localCenter, m_sweep, m_xf, b2Transform::p, b2Transform::q, and b2Rot::Set().
void b2Body::ApplyAngularImpulse (float32 impulse) [inline]
Apply an angular impulse.
Parameters:
impulse the angular impulse in units of kg*m*m/s
Definition at line 806 of file b2Body.h.
References b2_dynamicBody, IsAwake(), m_angularVelocity, m_invI, m_type, and SetAwake().
void b2Body::ApplyForce (const b2Vec2 & force, const b2Vec2 & point) [inline]
Apply a force at a world point. If the force is not applied at the center of mass, it will generate a torque and affect the angular velocity. This wakes up the body.
Parameters:
force the world force vector, usually in Newtons (N).
point the world position of the point of application.
Definition at line 745 of file b2Body.h.
References b2_dynamicBody, b2Cross(), b2Sweep::c, IsAwake(), m_force, m_sweep, m_torque, m_type, and SetAwake().
void b2Body::ApplyForceToCenter (const b2Vec2 & force) [inline]
Apply a force to the center of mass. This wakes up the body.
Parameters:
force the world force vector, usually in Newtons (N).
Definition at line 761 of file b2Body.h.
References b2_dynamicBody, IsAwake(), m_force, m_type, and SetAwake().
void b2Body::ApplyLinearImpulse (const b2Vec2 & impulse, const b2Vec2 & point) [inline]
Apply an impulse at a point. This immediately modifies the velocity. It also modifies the angular velocity if the point of application is not at the center of mass. This wakes up the body.
Parameters:
impulse the world impulse vector, usually in N-seconds or kg-m/s.
point the world position of the point of application.
Definition at line 791 of file b2Body.h.
References b2_dynamicBody, b2Cross(), b2Sweep::c, IsAwake(), m_angularVelocity, m_invI, m_invMass, m_linearVelocity, m_sweep, m_type, and SetAwake().
void b2Body::ApplyTorque (float32 torque) [inline]
Apply a torque. This affects the angular velocity without affecting the linear velocity of the center of mass. This wakes up the body.
Parameters:
torque about the z-axis (out of the screen), usually in N-m.
Definition at line 776 of file b2Body.h.
References b2_dynamicBody, IsAwake(), m_torque, m_type, and SetAwake().
b2Fixture* b2Body::CreateFixture (const b2FixtureDef * def)
Creates a fixture and attach it to this body. Use this function if you need to set some fixture parameters, like friction. Otherwise you can create the fixture directly from a shape. If the density is non-zero, this function automatically updates the mass of the body. Contacts are not created until the next time step.
Parameters:
def the fixture definition.
Warning:
This function is locked during callbacks.
b2Fixture* b2Body::CreateFixture (const b2Shape * shape, float32 density)
Creates a fixture from a shape and attach it to this body. This is a convenience function. Use b2FixtureDef if you need to set parameters like friction, restitution, user data, or filtering. If the density is non-zero, this function automatically updates the mass of the body.
Parameters:
shape the shape to be cloned.
density the shape density (set to zero for static bodies).
Warning:
This function is locked during callbacks.
void b2Body::DestroyFixture (b2Fixture * fixture)
Destroy a fixture. This removes the fixture from the broad-phase and destroys all contacts associated with this fixture. This will automatically adjust the mass of the body if the body is dynamic and the fixture has positive density. All fixtures attached to a body are implicitly destroyed when the body is destroyed.
Parameters:
fixture the fixture to be removed.
Warning:
This function is locked during callbacks.
void b2Body::Dump ()
Dump this body to a log file.
float32 b2Body::GetAngle () const [inline]
Get the angle in radians.
Returns:
the current world rotation angle in radians.
Definition at line 478 of file b2Body.h.
References b2Sweep::a, and m_sweep.
float32 b2Body::GetAngularDamping () const [inline]
Get the angular damping of the body.
Definition at line 590 of file b2Body.h.
References m_angularDamping.
float32 b2Body::GetAngularVelocity () const [inline]
Get the angular velocity.
Returns:
the angular velocity in radians/second.
Definition at line 528 of file b2Body.h.
References m_angularVelocity.
b2ContactEdge * b2Body::GetContactList () [inline]
Get the list of all contacts attached to this body.
Warning:
this list changes during the time step and you may miss some collisions if you don't use b2ContactListener.
Definition at line 715 of file b2Body.h.
References m_contactList.
const b2ContactEdge * b2Body::GetContactList () const [inline]
Definition at line 720 of file b2Body.h.
References m_contactList.
b2Fixture * b2Body::GetFixtureList () [inline]
Get the list of all fixtures attached to this body.
Definition at line 695 of file b2Body.h.
References m_fixtureList.
const b2Fixture * b2Body::GetFixtureList () const [inline]
Definition at line 700 of file b2Body.h.
References m_fixtureList.
float32 b2Body::GetGravityScale () const [inline]
Get the gravity scale of the body.
Definition at line 600 of file b2Body.h.
References m_gravityScale.
float32 b2Body::GetInertia () const [inline]
Get the rotational inertia of the body about the local origin.
Returns:
the rotational inertia, usually in kg-m^2.
Definition at line 538 of file b2Body.h.
References b2Dot(), b2Sweep::localCenter, m_I, m_mass, and m_sweep.
b2JointEdge * b2Body::GetJointList () [inline]
Get the list of all joints attached to this body.
Definition at line 705 of file b2Body.h.
References m_jointList.
const b2JointEdge * b2Body::GetJointList () const [inline]
Definition at line 710 of file b2Body.h.
References m_jointList.
float32 b2Body::GetLinearDamping () const [inline]
Get the linear damping of the body.
Definition at line 580 of file b2Body.h.
References m_linearDamping.
b2Vec2 b2Body::GetLinearVelocity () const [inline]
Get the linear velocity of the center of mass.
Returns:
the linear velocity of the center of mass.
Definition at line 508 of file b2Body.h.
References m_linearVelocity.
b2Vec2 b2Body::GetLinearVelocityFromLocalPoint (const b2Vec2 & localPoint) const [inline]
Get the world velocity of a local point.
Parameters:
a point in local coordinates.
Returns:
the world velocity of a point.
Definition at line 575 of file b2Body.h.
References GetLinearVelocityFromWorldPoint(), and GetWorldPoint().
b2Vec2 b2Body::GetLinearVelocityFromWorldPoint (const b2Vec2 & worldPoint) const [inline]
Get the world linear velocity of a world point attached to this body.
Parameters:
a point in world coordinates.
Returns:
the world velocity of a point.
Definition at line 570 of file b2Body.h.
References b2Cross(), b2Sweep::c, m_angularVelocity, m_linearVelocity, and m_sweep.
Referenced by GetLinearVelocityFromLocalPoint().
const b2Vec2 & b2Body::GetLocalCenter () const [inline]
Get the local position of the center of mass.
Definition at line 488 of file b2Body.h.
References b2Sweep::localCenter, and m_sweep.
b2Vec2 b2Body::GetLocalPoint (const b2Vec2 & worldPoint) const [inline]
Gets a local point relative to the body's origin given a world point.
Parameters:
a point in world coordinates.
Returns:
the corresponding local point relative to the body's origin.
Definition at line 560 of file b2Body.h.
References b2MulT(), and m_xf.
b2Vec2 b2Body::GetLocalVector (const b2Vec2 & worldVector) const [inline]
Gets a local vector given a world vector.
Parameters:
a vector in world coordinates.
Returns:
the corresponding local vector.
Definition at line 565 of file b2Body.h.
References b2MulT(), m_xf, and b2Transform::q.
float32 b2Body::GetMass () const [inline]
Get the total mass of the body.
Returns:
the mass, usually in kilograms (kg).
Definition at line 533 of file b2Body.h.
References m_mass.
void b2Body::GetMassData (b2MassData * data) const [inline]
Get the mass data of the body.
Returns:
a struct containing the mass, inertia and center of the body.
Definition at line 543 of file b2Body.h.
References b2Dot(), b2MassData::center, b2MassData::I, b2Sweep::localCenter, m_I, m_mass, m_sweep, and b2MassData::mass.
b2Body * b2Body::GetNext () [inline]
Get the next body in the world's body list.
Definition at line 725 of file b2Body.h.
References m_next.
const b2Body * b2Body::GetNext () const [inline]
Definition at line 730 of file b2Body.h.
References m_next.
const b2Vec2 & b2Body::GetPosition () const [inline]
Get the world body origin position.
Returns:
the world position of the body's origin.
Definition at line 473 of file b2Body.h.
References m_xf, and b2Transform::p.
const b2Transform & b2Body::GetTransform () const [inline]
Get the body transform for the body's origin.
Returns:
the world transform of the body's origin.
Definition at line 468 of file b2Body.h.
References m_xf.
Referenced by b2Contact::GetWorldManifold(), b2Fixture::RayCast(), and b2Fixture::TestPoint().
b2BodyType b2Body::GetType () const [inline]
Get the type of this body.
Definition at line 463 of file b2Body.h.
References m_type.
void * b2Body::GetUserData () const [inline]
Get the user data pointer that was provided in the body definition.
Definition at line 740 of file b2Body.h.
References m_userData.
b2World * b2Body::GetWorld () [inline]
Get the parent world of this body.
Definition at line 836 of file b2Body.h.
References m_world.
const b2World * b2Body::GetWorld () const [inline]
Definition at line 841 of file b2Body.h.
References m_world.
const b2Vec2 & b2Body::GetWorldCenter () const [inline]
Get the world position of the center of mass.
Definition at line 483 of file b2Body.h.
References b2Sweep::c, and m_sweep.
b2Vec2 b2Body::GetWorldPoint (const b2Vec2 & localPoint) const [inline]
Get the world coordinates of a point given the local coordinates.
Parameters:
localPoint a point on the body measured relative the the body's origin.
Returns:
the same point expressed in world coordinates.
Definition at line 550 of file b2Body.h.
References b2Mul(), and m_xf.
Referenced by GetLinearVelocityFromLocalPoint().
b2Vec2 b2Body::GetWorldVector (const b2Vec2 & localVector) const [inline]
Get the world coordinates of a vector given the local coordinates.
Parameters:
localVector a vector fixed in the body.
Returns:
the same vector expressed in world coordinates.
Definition at line 555 of file b2Body.h.
References b2Mul(), m_xf, and b2Transform::q.
bool b2Body::IsActive () const [inline]
Get the active state of the body.
Definition at line 653 of file b2Body.h.
References e_activeFlag, and m_flags.
bool b2Body::IsAwake () const [inline]
Get the sleeping state of this body.
Returns:
true if the body is sleeping.
Definition at line 648 of file b2Body.h.
References e_awakeFlag, and m_flags.
Referenced by ApplyAngularImpulse(), ApplyForce(), ApplyForceToCenter(), ApplyLinearImpulse(), and ApplyTorque().
bool b2Body::IsBullet () const [inline]
Is this body treated like a bullet for continuous collision detection?
Definition at line 622 of file b2Body.h.
References e_bulletFlag, and m_flags.
bool b2Body::IsFixedRotation () const [inline]
Does this body have fixed rotation?
Definition at line 672 of file b2Body.h.
References e_fixedRotationFlag, and m_flags.
bool b2Body::IsSleepingAllowed () const [inline]
Is this body allowed to sleep.
Definition at line 690 of file b2Body.h.
References e_autoSleepFlag, and m_flags.
void b2Body::ResetMassData ()
This resets the mass properties to the sum of the mass properties of the fixtures. This normally does not need to be called unless you called SetMassData to override the mass and you later want to reset the mass.
Referenced by SetFixedRotation().
void b2Body::SetActive (bool flag)
Set the active state of the body. An inactive body is not simulated and cannot be collided with or woken up. If you pass a flag of true, all fixtures will be added to the broad-phase. If you pass a flag of false, all fixtures will be removed from the broad-phase and all contacts will be destroyed. Fixtures and joints are otherwise unaffected. You may continue to create/destroy fixtures and joints on inactive bodies. Fixtures on an inactive body are implicitly inactive and will not participate in collisions, ray-casts, or queries. Joints connected to an inactive body are implicitly inactive. An inactive body is still owned by a b2World object and remains in the body list.
void b2Body::SetAngularDamping (float32 angularDamping) [inline]
Set the angular damping of the body.
Definition at line 595 of file b2Body.h.
References m_angularDamping.
void b2Body::SetAngularVelocity (float32 omega) [inline]
Set the angular velocity.
Parameters:
omega the new angular velocity in radians/second.
Definition at line 513 of file b2Body.h.
References b2_staticBody, m_angularVelocity, m_type, and SetAwake().
void b2Body::SetAwake (bool flag) [inline]
Set the sleep state of the body. A sleeping body has very low CPU cost.
Parameters:
flag set to true to put body to sleep, false to wake it.
Definition at line 627 of file b2Body.h.
References e_awakeFlag, m_angularVelocity, m_flags, m_force, m_linearVelocity, m_sleepTime, m_torque, and b2Vec2::SetZero().
Referenced by ApplyAngularImpulse(), ApplyForce(), ApplyForceToCenter(), ApplyLinearImpulse(), ApplyTorque(), SetAngularVelocity(), SetLinearVelocity(), and SetSleepingAllowed().
void b2Body::SetBullet (bool flag) [inline]
Should this body be treated like a bullet for continuous collision detection?
Definition at line 610 of file b2Body.h.
References e_bulletFlag, and m_flags.
void b2Body::SetFixedRotation (bool flag) [inline]
Set this body to have fixed rotation. This causes the mass to be reset.
Definition at line 658 of file b2Body.h.
References e_fixedRotationFlag, m_flags, and ResetMassData().
void b2Body::SetGravityScale (float32 scale) [inline]
Set the gravity scale of the body.
Definition at line 605 of file b2Body.h.
References m_gravityScale, and scale.
void b2Body::SetLinearDamping (float32 linearDamping) [inline]
Set the linear damping of the body.
Definition at line 585 of file b2Body.h.
References m_linearDamping.
void b2Body::SetLinearVelocity (const b2Vec2 & v) [inline]
Set the linear velocity of the center of mass.
Parameters:
v the new linear velocity of the center of mass.
Definition at line 493 of file b2Body.h.
References b2_staticBody, b2Dot(), m_linearVelocity, m_type, and SetAwake().
void b2Body::SetMassData (const b2MassData * data)
Set the mass properties to override the mass properties of the fixtures. Note that this changes the center of mass position. Note that creating or destroying fixtures can also alter the mass. This function has no effect if the body isn't dynamic.
Parameters:
massData the mass properties.
void b2Body::SetSleepingAllowed (bool flag) [inline]
You can disable sleeping on this body. If you disable sleeping, the body will be woken.
Definition at line 677 of file b2Body.h.
References e_autoSleepFlag, m_flags, and SetAwake().
void b2Body::SetTransform (const b2Vec2 & position, float32 angle)
Set the position of the body's origin and rotation. This breaks any contacts and wakes the other bodies. Manipulating a body's transform may cause non-physical behavior.
Parameters:
position the world position of the body's local origin.
angle the world rotation in radians.
void b2Body::SetType (b2BodyType type)
Set the type of this body. This may alter the mass and velocity.
void b2Body::SetUserData (void * data) [inline]
Set the user data. Use this to store your application specific data.
Definition at line 735 of file b2Body.h.
References data, and m_userData.
bool b2Body::ShouldCollide (const b2Body * other) const [private]
void b2Body::SynchronizeFixtures () [private]
void b2Body::SynchronizeTransform () [inline, private]
Definition at line 820 of file b2Body.h.
References b2Sweep::a, b2Mul(), b2Sweep::c, b2Sweep::localCenter, m_sweep, m_xf, b2Transform::p, b2Transform::q, and b2Rot::Set().
Friends And Related Function Documentation
friend class b2Contact [friend]
Definition at line 387 of file b2Body.h.
friend class b2ContactManager [friend]
Definition at line 385 of file b2Body.h.
friend class b2ContactSolver [friend]
Definition at line 386 of file b2Body.h.
friend class b2DistanceJoint [friend]
Definition at line 389 of file b2Body.h.
friend class b2FrictionJoint [friend]
Definition at line 397 of file b2Body.h.
friend class b2GearJoint [friend]
Definition at line 390 of file b2Body.h.
friend class b2Island [friend]
Definition at line 384 of file b2Body.h.
friend class b2MouseJoint [friend]
Definition at line 392 of file b2Body.h.
friend class b2PrismaticJoint [friend]
Definition at line 393 of file b2Body.h.
friend class b2PulleyJoint [friend]
Definition at line 394 of file b2Body.h.
friend class b2RevoluteJoint [friend]
Definition at line 395 of file b2Body.h.
friend class b2RopeJoint [friend]
Definition at line 398 of file b2Body.h.
friend class b2WeldJoint [friend]
Definition at line 396 of file b2Body.h.
friend class b2WheelJoint [friend]
Definition at line 391 of file b2Body.h.
friend class b2World [friend]
Definition at line 383 of file b2Body.h.
Member Data Documentation
float32 b2Body::m_angularDamping [private]
Definition at line 455 of file b2Body.h.
Referenced by GetAngularDamping(), and SetAngularDamping().
float32 b2Body::m_angularVelocity [private]
Definition at line 434 of file b2Body.h.
Referenced by ApplyAngularImpulse(), ApplyLinearImpulse(), GetAngularVelocity(), GetLinearVelocityFromWorldPoint(), SetAngularVelocity(), and SetAwake().
b2ContactEdge* b2Body::m_contactList [private]
Definition at line 447 of file b2Body.h.
Referenced by GetContactList().
int32 b2Body::m_fixtureCount [private]
Definition at line 444 of file b2Body.h.
b2Fixture* b2Body::m_fixtureList [private]
Definition at line 443 of file b2Body.h.
Referenced by GetFixtureList().
uint16 b2Body::m_flags [private]
Definition at line 426 of file b2Body.h.
Referenced by IsActive(), IsAwake(), IsBullet(), IsFixedRotation(), IsSleepingAllowed(), SetAwake(), SetBullet(), SetFixedRotation(), and SetSleepingAllowed().
b2Vec2 b2Body::m_force [private]
Definition at line 436 of file b2Body.h.
Referenced by ApplyForce(), ApplyForceToCenter(), and SetAwake().
float32 b2Body::m_gravityScale [private]
Definition at line 456 of file b2Body.h.
Referenced by GetGravityScale(), and SetGravityScale().
float32 b2Body::m_I [private]
Definition at line 452 of file b2Body.h.
Referenced by GetInertia(), and GetMassData().
float32 b2Body::m_invI [private]
Definition at line 452 of file b2Body.h.
Referenced by ApplyAngularImpulse(), and ApplyLinearImpulse().
float32 b2Body::m_invMass [private]
Definition at line 449 of file b2Body.h.
Referenced by ApplyLinearImpulse().
int32 b2Body::m_islandIndex [private]
Definition at line 428 of file b2Body.h.
Referenced by b2Island::Add().
b2JointEdge* b2Body::m_jointList [private]
Definition at line 446 of file b2Body.h.
Referenced by GetJointList().
float32 b2Body::m_linearDamping [private]
Definition at line 454 of file b2Body.h.
Referenced by GetLinearDamping(), and SetLinearDamping().
b2Vec2 b2Body::m_linearVelocity [private]
Definition at line 433 of file b2Body.h.
Referenced by ApplyLinearImpulse(), GetLinearVelocity(), GetLinearVelocityFromWorldPoint(), SetAwake(), and SetLinearVelocity().
float32 b2Body::m_mass [private]
Definition at line 449 of file b2Body.h.
Referenced by GetInertia(), GetMass(), and GetMassData().
b2Body* b2Body::m_next [private]
Definition at line 441 of file b2Body.h.
Referenced by GetNext().
b2Body* b2Body::m_prev [private]
Definition at line 440 of file b2Body.h.
float32 b2Body::m_sleepTime [private]
Definition at line 458 of file b2Body.h.
Referenced by SetAwake().
b2Sweep b2Body::m_sweep [private]
Definition at line 431 of file b2Body.h.
Referenced by Advance(), ApplyForce(), ApplyLinearImpulse(), GetAngle(), GetInertia(), GetLinearVelocityFromWorldPoint(), GetLocalCenter(), GetMassData(), GetWorldCenter(), and SynchronizeTransform().
float32 b2Body::m_torque [private]
Definition at line 437 of file b2Body.h.
Referenced by ApplyForce(), ApplyTorque(), and SetAwake().
b2BodyType b2Body::m_type [private]
Definition at line 424 of file b2Body.h.
Referenced by ApplyAngularImpulse(), ApplyForce(), ApplyForceToCenter(), ApplyLinearImpulse(), ApplyTorque(), GetType(), SetAngularVelocity(), and SetLinearVelocity().
void* b2Body::m_userData [private]
Definition at line 460 of file b2Body.h.
Referenced by GetUserData(), and SetUserData().
b2World* b2Body::m_world [private]
Definition at line 439 of file b2Body.h.
Referenced by GetWorld().
b2Transform b2Body::m_xf [private]
Definition at line 430 of file b2Body.h.
Referenced by Advance(), GetLocalPoint(), GetLocalVector(), GetPosition(), GetTransform(), GetWorldPoint(), GetWorldVector(), and SynchronizeTransform().
The documentation for this class was generated from the following file:
/Users/gaspard/git/lubyk/modules/b2/bind/b2Body.h