lubyk: lubyk::ScopedLock Class Reference
lubyk::ScopedLock Class Reference
#include <rmutex.h>
Inherits lubyk::NonCopyable.
Public Member Functions
ScopedLock (RMutex *mutex)
ScopedLock (RMutex &mutex)
~ScopedLock ()
Private Attributes
RMutex * mutex_ptr_
Detailed Description
FIXME: replace with a non-recursive mutex: we do not need recursion any more ! Scoped recursive Mutex Lock for exclusive access to a resource.
Definition at line 90 of file rmutex.h.
Constructor & Destructor Documentation
lubyk::ScopedLock::ScopedLock (RMutex * mutex) [inline]
Definition at line 93 of file rmutex.h.
References lubyk::RMutex::lock(), and mutex_ptr_.
lubyk::ScopedLock::ScopedLock (RMutex & mutex) [inline]
Definition at line 97 of file rmutex.h.
References lubyk::RMutex::lock(), and mutex_ptr_.
lubyk::ScopedLock::~ScopedLock () [inline]
Definition at line 101 of file rmutex.h.
References mutex_ptr_, and lubyk::RMutex::unlock().
Member Data Documentation
RMutex* lubyk::ScopedLock::mutex_ptr_ [private]
Definition at line 91 of file rmutex.h.
Referenced by ScopedLock(), and ~ScopedLock().
The documentation for this class was generated from the following file:
/Users/gaspard/git/lubyk/modules/lubyk/include/lubyk/rmutex.h