lubyk: mdns::Browser Class Reference
mdns::Browser Class Reference
#include <Browser.h>
Inherits mdns::AbstractBrowser, and lubyk::LuaObject.
Public Member Functions
Browser (const char *service_type)
~Browser ()
const char * serviceType ()
int fd ()
bool getServices ()
LuaStackSize nextService (lua_State *L)
Private Member Functions
void pushTxtRecord (lua_State *L, const std::string &txt)
Detailed Description
Browse for devices matching a give service type. Call a lua function when devices are added or removed.
Bindings info:
string_format:'%s' string_args:'(*userdata)->serviceType()' lib_name:'Browser_core'
Definition at line 48 of file Browser.h.
Constructor & Destructor Documentation
mdns::Browser::Browser (const char * service_type) [inline]
Definition at line 51 of file Browser.h.
mdns::Browser::~Browser () [inline]
Definition at line 54 of file Browser.h.
Member Function Documentation
int mdns::Browser::fd () [inline]
Return the mDNS browser's filedescriptor.
Definition at line 62 of file Browser.h.
bool mdns::Browser::getServices () [inline]
Load found services (must be called after waitRead or it blocks).
Reimplemented from mdns::AbstractBrowser.
Definition at line 68 of file Browser.h.
LuaStackSize mdns::Browser::nextService (lua_State * L) [inline]
Get next found service. Must call getServices after scheduler waitRead and before nextService.
Returns:
nil if there is nothing left.
Definition at line 76 of file Browser.h.
References mdns::Location::host(), mdns::Location::interface(), mdns::Location::ip(), mdns::AbstractBrowser::Service::is_add_, mdns::Location::name(), mdns::Location::name_from_ip(), mdns::Location::port(), and mdns::AbstractBrowser::Service::txt_.
void mdns::Browser::pushTxtRecord (lua_State * L, const std::string & txt) [inline, private]
Definition at line 121 of file Browser.h.
References key, line, pos, and value.
const char* mdns::Browser::serviceType () [inline]
Definition at line 56 of file Browser.h.
The documentation for this class was generated from the following file:
/Users/gaspard/git/lubyk/modules/mdns/include/mdns/Browser.h