lubyk: lubyk::ScopedUnlock Class Reference
lubyk::ScopedUnlock Class Reference
#include <rmutex.h>
Inherits lubyk::NonCopyable.
Public Member Functions
ScopedUnlock (RMutex *mutex)
ScopedUnlock (RMutex &mutex)
~ScopedUnlock ()
Private Attributes
RMutex * mutex_ptr_
Detailed Description
Scoped recursive Mutex Unlock to release exclusive access to a resource.
Definition at line 109 of file rmutex.h.
Constructor & Destructor Documentation
lubyk::ScopedUnlock::ScopedUnlock (RMutex * mutex) [inline]
Definition at line 113 of file rmutex.h.
References mutex_ptr_, and lubyk::RMutex::unlock().
lubyk::ScopedUnlock::ScopedUnlock (RMutex & mutex) [inline]
Definition at line 117 of file rmutex.h.
References mutex_ptr_, and lubyk::RMutex::unlock().
lubyk::ScopedUnlock::~ScopedUnlock () [inline]
Definition at line 121 of file rmutex.h.
References lubyk::RMutex::lock(), and mutex_ptr_.
Member Data Documentation
RMutex* lubyk::ScopedUnlock::mutex_ptr_ [private]
Definition at line 111 of file rmutex.h.
Referenced by ScopedUnlock(), and ~ScopedUnlock().
The documentation for this class was generated from the following file:
/Users/gaspard/git/lubyk/modules/lubyk/include/lubyk/rmutex.h