lubyk: lubyk::Condition Class Reference
lubyk::Condition Class Reference
#include <condition.h>
Inherits lubyk::Mutex.
Public Member Functions
Condition ()
~Condition ()
void wait ()
void signal ()
Private Attributes
pthread_cond_t cond_
Detailed Description
A class to ease multi-threading. The Condition helps lock a given thread while it waits for another to finish some work.
Typical usage is: 1. thread1 cond->lock() 2. start thread2 3. thread1 cond->wait() 3. in thread2 cond->signal() 4. thread1 cond->unlock()
Definition at line 57 of file condition.h.
Constructor & Destructor Documentation
lubyk::Condition::Condition () [inline]
Definition at line 60 of file condition.h.
References cond_.
lubyk::Condition::~Condition () [inline]
Definition at line 66 of file condition.h.
References cond_.
Member Function Documentation
void lubyk::Condition::signal () [inline]
Release any waiting thread.
Definition at line 83 of file condition.h.
References cond_, lubyk::Mutex::lock(), and lubyk::Mutex::unlock().
Referenced by lubyk::Thread::threadReady().
void lubyk::Condition::wait () [inline]
This makes the calling thread sleep until 'signal' is called. It should be called after having been locked by the thread that created the Condition.
Definition at line 75 of file condition.h.
References cond_, and lubyk::Mutex::mutex_.
Referenced by lubyk::Thread::startThread().
Member Data Documentation
pthread_cond_t lubyk::Condition::cond_ [private]
Definition at line 58 of file condition.h.
Referenced by Condition(), signal(), wait(), and ~Condition().
The documentation for this class was generated from the following file:
/Users/gaspard/git/lubyk/modules/lubyk/include/lubyk/condition.h