lubyk: lubyk::ThreadedLuaObject Class Reference
lubyk::ThreadedLuaObject Class Reference
#include <lua_object.h>
Inherits lubyk::LuaObject.
Inherited by dummy::Dummy, lk::Debug, mimas::Action, mimas::Application, mimas::Button, mimas::Callback, mimas::DataSource, mimas::FileObserver, mimas::GLWidget, mimas::LineEdit, mimas::ListView, mimas::MainWindow, mimas::Menu, mimas::MenuBar, mimas::Slider, mimas::SocketNotifier, mimas::TableView, mimas::Timer, and mimas::Widget.
Public Member Functions
ThreadedLuaObject () throw ()
int luaInit (lua_State *L, void *ptr, const char *type_name) throw ()
Public Attributes
lua_State * lua_
Protected Member Functions
bool pushLuaCallbackl (const char *method, int len) const
void setupLuaThread (lua_State *L) throw ()
Private Attributes
int thread_in_env_idx_
Detailed Description
Lua object with a Lua thread (has callbacks)
Definition at line 76 of file lua_object.h.
Constructor & Destructor Documentation
lubyk::ThreadedLuaObject::ThreadedLuaObject () throw ()
Member Function Documentation
int lubyk::ThreadedLuaObject::luaInit (lua_State * L, void * ptr, const char * type_name) throw ()
Reimplemented from lubyk::LuaObject.
Referenced by mimas::TableView::luaInit(), mimas::ListView::luaInit(), and mimas::Application::MakeApplication().
bool lubyk::ThreadedLuaObject::pushLuaCallbackl (const char * method, int len) const [protected]
The caller should lock before calling this.
Returns:
: true if the callback is set, false otherwise.
TODO: The 'const' stuff is stupid: can't we remove it ? FIXME: OPTIMIZATION: Register the keys and pass a ref in the registry.
void lubyk::ThreadedLuaObject::setupLuaThread (lua_State * L) throw () [protected]
Member Data Documentation
lua_State* lubyk::ThreadedLuaObject::lua_
Definition at line 79 of file lua_object.h.
Referenced by mimas::Callback::callback(), mimas::Callback::deleteOnCall(), mimas::TableView::luaInit(), mimas::ListView::luaInit(), mimas::Callback::setCallbackFromApp(), and mimas::Action::triggeredSlot().
int lubyk::ThreadedLuaObject::thread_in_env_idx_ [private]
Definition at line 77 of file lua_object.h.
The documentation for this class was generated from the following file:
/Users/gaspard/git/lubyk/modules/lubyk/include/lubyk/lua_object.h