lubyk: b2GrowableStack< T, N > Class Template Reference
b2GrowableStack< T, N > Class Template Reference
#include <b2GrowableStack.h>
Public Member Functions
b2GrowableStack ()
~b2GrowableStack ()
void Push (const T &element)
T Pop ()
int32 GetCount ()
Private Attributes
T * m_stack
T m_array [N]
int32 m_count
int32 m_capacity
Detailed Description
template<typename T, int32 N>
class b2GrowableStack< T, N >
This is a growable LIFO stack with an initial capacity of N. If the stack size exceeds the initial capacity, the heap is used to increase the size of the stack.
Definition at line 28 of file b2GrowableStack.h.
Constructor & Destructor Documentation
template<typename T, int32 N> b2GrowableStack< T, N >::b2GrowableStack () [inline]
Definition at line 31 of file b2GrowableStack.h.
References b2GrowableStack< T, N >::m_array, b2GrowableStack< T, N >::m_capacity, b2GrowableStack< T, N >::m_count, and b2GrowableStack< T, N >::m_stack.
template<typename T, int32 N> b2GrowableStack< T, N >::~b2GrowableStack () [inline]
Definition at line 38 of file b2GrowableStack.h.
References b2Free(), b2GrowableStack< T, N >::m_array, and b2GrowableStack< T, N >::m_stack.
Member Function Documentation
template<typename T, int32 N> int32 b2GrowableStack< T, N >::GetCount () [inline]
Definition at line 72 of file b2GrowableStack.h.
References b2GrowableStack< T, N >::m_count.
Referenced by b2DynamicTree::Query(), and b2DynamicTree::RayCast().
template<typename T, int32 N> T b2GrowableStack< T, N >::Pop () [inline]
Definition at line 65 of file b2GrowableStack.h.
References b2Assert, b2GrowableStack< T, N >::m_count, and b2GrowableStack< T, N >::m_stack.
Referenced by b2DynamicTree::Query(), and b2DynamicTree::RayCast().
template<typename T, int32 N> void b2GrowableStack< T, N >::Push (const T & element) [inline]
Definition at line 47 of file b2GrowableStack.h.
References b2Alloc(), b2Free(), element, b2GrowableStack< T, N >::m_array, b2GrowableStack< T, N >::m_capacity, b2GrowableStack< T, N >::m_count, b2GrowableStack< T, N >::m_stack, and T.
Referenced by b2DynamicTree::Query(), and b2DynamicTree::RayCast().
Member Data Documentation
template<typename T, int32 N> T b2GrowableStack< T, N >::m_array[N] [private]
Definition at line 79 of file b2GrowableStack.h.
Referenced by b2GrowableStack< T, N >::b2GrowableStack(), b2GrowableStack< T, N >::Push(), and b2GrowableStack< T, N >::~b2GrowableStack().
template<typename T, int32 N> int32 b2GrowableStack< T, N >::m_capacity [private]
Definition at line 81 of file b2GrowableStack.h.
Referenced by b2GrowableStack< T, N >::b2GrowableStack(), and b2GrowableStack< T, N >::Push().
template<typename T, int32 N> int32 b2GrowableStack< T, N >::m_count [private]
Definition at line 80 of file b2GrowableStack.h.
Referenced by b2GrowableStack< T, N >::b2GrowableStack(), b2GrowableStack< T, N >::GetCount(), b2GrowableStack< T, N >::Pop(), and b2GrowableStack< T, N >::Push().
template<typename T, int32 N> T* b2GrowableStack< T, N >::m_stack [private]
Definition at line 78 of file b2GrowableStack.h.
Referenced by b2GrowableStack< T, N >::b2GrowableStack(), b2GrowableStack< T, N >::Pop(), b2GrowableStack< T, N >::Push(), and b2GrowableStack< T, N >::~b2GrowableStack().
The documentation for this class was generated from the following file:
/Users/gaspard/git/lubyk/modules/b2/bind/b2GrowableStack.h