lubyk: lubyk::Mutex Class Reference
lubyk::Mutex Class Reference
#include <mutex.h>
Inherits lubyk::NonCopyable.
Inherited by lubyk::Condition, lubyk::Thread, mdns::AbstractBrowser, and mdns::AbstractRegistration.
Public Member Functions
Mutex ()
virtual ~Mutex ()
void lock ()
void unlock ()
Private Attributes
pthread_mutex_t mutex_
Friends
class Condition
Detailed Description
Simple wrapper class for a fast mutex.
Definition at line 43 of file mutex.h.
Constructor & Destructor Documentation
lubyk::Mutex::Mutex () [inline]
Definition at line 48 of file mutex.h.
References mutex_, and status.
virtual lubyk::Mutex::~Mutex () [inline, virtual]
Definition at line 56 of file mutex.h.
References mutex_, and status.
Member Function Documentation
void lubyk::Mutex::lock () [inline]
If the mutex is locked by another thread, waits until it is unlocked, lock and continue. If the mutex is not locked. Lock and continue. If this thread locked it: bang!
Definition at line 67 of file mutex.h.
References mutex_.
Referenced by lubyk::RMutex::lock(), lubyk::ScopedSLock::ScopedSLock(), lubyk::Condition::signal(), lubyk::Thread::startThread(), and lubyk::ScopedSUnlock::~ScopedSUnlock().
void lubyk::Mutex::unlock () [inline]
Release the lock so others can work on the data.
Definition at line 72 of file mutex.h.
References mutex_.
Referenced by lubyk::ScopedSUnlock::ScopedSUnlock(), lubyk::Condition::signal(), lubyk::RMutex::unlock(), and lubyk::ScopedSLock::~ScopedSLock().
Friends And Related Function Documentation
friend class Condition [friend]
Definition at line 46 of file mutex.h.
Member Data Documentation
pthread_mutex_t lubyk::Mutex::mutex_ [private]
Definition at line 45 of file mutex.h.
Referenced by lock(), Mutex(), unlock(), lubyk::Condition::wait(), and ~Mutex().
The documentation for this class was generated from the following file:
/Users/gaspard/git/lubyk/modules/lubyk/include/lubyk/mutex.h