lubyk: mimas::GLWidget::OpenGLScene Class Reference
mimas::GLWidget::OpenGLScene Class Reference
#include <GLWidget.h>
Public Member Functions
OpenGLScene (GLWidget *master)
virtual void drawBackground (QPainter *painter, const QRectF &rect)
Public Attributes
GLWidget * master_
bool resized_
Detailed Description
Definition at line 57 of file GLWidget.h.
Constructor & Destructor Documentation
mimas::GLWidget::OpenGLScene::OpenGLScene (GLWidget * master) [inline]
Definition at line 62 of file GLWidget.h.
Member Function Documentation
virtual void mimas::GLWidget::OpenGLScene::drawBackground (QPainter * painter, const QRectF & rect) [inline, virtual]
Definition at line 67 of file GLWidget.h.
References height, mimas::GLWidget::initializeGL(), mimas::GLWidget::paintGL(), mimas::GLWidget::resizeGL(), and width.
Member Data Documentation
GLWidget* mimas::GLWidget::OpenGLScene::master_
Definition at line 59 of file GLWidget.h.
bool mimas::GLWidget::OpenGLScene::resized_
Definition at line 60 of file GLWidget.h.
The documentation for this class was generated from the following file:
/Users/gaspard/git/lubyk/modules/mimas/include/mimas/GLWidget.h