lubyk: lubyk::Thread Class Reference
lubyk::Thread Class Reference
#include <thread.h>
Inherits lubyk::Mutex.
Public Member Functions
Thread ()
virtual ~Thread ()
template<void(*)(Thread *) Tmethod>
void startThread (void *parameter=NULL)
void startThread (void(*static_method)(Thread *), void *parameter=NULL)
template<class T , void(T::*)(Thread *) Tmethod>
void startThread (T *owner, void *parameter=NULL)
template<class T , void(T::*)() Tmethod>
void startThread (T *owner, void *parameter=NULL)
bool shouldRun ()
void kill ()
void sendSignal (int sig)
void registerSignal (int sig)
void join ()
void quit ()
bool isRunning ()
void highPriority ()
void normalPriority ()
void threadReady ()
Static Public Member Functions
static void millisleep (double milliseconds)
static Thread * thread_this ()
Public Attributes
void * parameter_
Static Public Attributes
static pthread_key_t sThisKey
Protected Attributes
bool should_run_
Static Private Member Functions
static void setThreadThis (Thread *thread)
static void * s_start_static_thread (void *thread_ptr)
template<class T , void(T::*)(Thread *) Tmethod>
static void * s_startThread (void *thread_ptr)
template<class T , void(T::*)() Tmethod>
static void * s_startThread (void *thread_ptr)
static void terminate (int sig)
Private Attributes
void * owner_
void(* static_method_)(Thread *)
pthread_t thread_id_
int normal_sched_policy_
struct sched_param normal_thread_param_
Condition condition_
Detailed Description
Definition at line 47 of file thread.h.
Constructor & Destructor Documentation
lubyk::Thread::Thread ()
virtual lubyk::Thread::~Thread () [virtual]
Member Function Documentation
void lubyk::Thread::highPriority ()
Set thread priority to high.
Referenced by lubyk::Timer< T, Tmethod >::startThread().
bool lubyk::Thread::isRunning () [inline]
Return true if the thread is running.
Definition at line 184 of file thread.h.
References thread_id_.
Referenced by startThread().
void lubyk::Thread::join () [inline]
Wait for thread to finish.
Definition at line 168 of file thread.h.
References thread_id_.
Referenced by lubyk::Timer< T, Tmethod >::join(), lubyk::Timer< T, Tmethod >::start(), and lubyk::Timer< T, Tmethod >::stop().
void lubyk::Thread::kill () [inline]
Kill thread (do not make this a virtual).
Definition at line 142 of file thread.h.
References should_run_, and thread_id_.
static void lubyk::Thread::millisleep (double milliseconds) [static]
Sleep for a given number of milliseconds.
Referenced by zmq::Poller::poll().
void lubyk::Thread::normalPriority ()
Set thread priority to normal.
void lubyk::Thread::quit () [inline]
Tell thread to quit (called from within own thread or when we can wait for next loop).
Definition at line 178 of file thread.h.
References should_run_.
Referenced by terminate().
void lubyk::Thread::registerSignal (int sig) [inline]
Definition at line 161 of file thread.h.
References terminate().
Referenced by s_start_static_thread(), and s_startThread().
static void* lubyk::Thread::s_start_static_thread (void * thread_ptr) [inline, static, private]
Static function to start a new thread from a class method or static function.
Definition at line 231 of file thread.h.
References registerSignal(), setThreadThis(), should_run_, static_method_, and thread_id_.
Referenced by startThread().
template<class T , void(T::*)(Thread *) Tmethod> static void* lubyk::Thread::s_startThread (void * thread_ptr) [inline, static, private]
Static function to start a new thread.
Definition at line 252 of file thread.h.
References owner_, registerSignal(), setThreadThis(), should_run_, T, and thread_id_.
template<class T , void(T::*)() Tmethod> static void* lubyk::Thread::s_startThread (void * thread_ptr) [inline, static, private]
Static function to start a new thread.
Definition at line 273 of file thread.h.
References owner_, registerSignal(), setThreadThis(), should_run_, T, and thread_id_.
void lubyk::Thread::sendSignal (int sig) [inline]
Send a signal to the running thread.
Definition at line 156 of file thread.h.
References thread_id_.
Referenced by lubyk::Timer< T, Tmethod >::interrupt().
static void lubyk::Thread::setThreadThis (Thread * thread) [inline, static, private]
Set 'this' value for the current thread so we can find our object back.
Definition at line 224 of file thread.h.
References sThisKey.
Referenced by s_start_static_thread(), and s_startThread().
bool lubyk::Thread::shouldRun () [inline]
Definition at line 136 of file thread.h.
References should_run_.
template<void(*)(Thread *) Tmethod> void lubyk::Thread::startThread (void * parameter = NULL) [inline]
Start a new thread with a class method.
Definition at line 55 of file thread.h.
References condition_, isRunning(), lubyk::Mutex::lock(), owner_, parameter, parameter_, s_start_static_thread(), should_run_, static_method_, thread_id_, and lubyk::Condition::wait().
Referenced by lubyk::Worker::execute(), and lubyk::Timer< T, Tmethod >::start().
void lubyk::Thread::startThread (void(*)(Thread *) static_method, void * parameter = NULL) [inline]
Start a new thread with a static function.
Definition at line 76 of file thread.h.
References condition_, isRunning(), lubyk::Mutex::lock(), owner_, parameter, parameter_, s_start_static_thread(), should_run_, static_method_, thread_id_, and lubyk::Condition::wait().
template<class T , void(T::*)(Thread *) Tmethod> void lubyk::Thread::startThread (T * owner, void * parameter = NULL) [inline]
Start a new thread with the given parameter. The class should check if it should stop using a typical "while (thread->run())". If the thread is interrupted with a SIGTERM, the class's terminate() method is called.
Definition at line 98 of file thread.h.
References condition_, isRunning(), lubyk::Mutex::lock(), owner_, parameter, parameter_, should_run_, thread_id_, and lubyk::Condition::wait().
template<class T , void(T::*)() Tmethod> void lubyk::Thread::startThread (T * owner, void * parameter = NULL) [inline]
Start a new thread with the given parameter. The class should check if it should stop using a typical "while (thread->run())". If the thread is interrupted with a SIGTERM, the class's terminate() method is called.
Definition at line 119 of file thread.h.
References condition_, isRunning(), lubyk::Mutex::lock(), owner_, parameter, parameter_, should_run_, thread_id_, and lubyk::Condition::wait().
static void lubyk::Thread::terminate (int sig) [inline, static, private]
Thread should stop.
Definition at line 291 of file thread.h.
References quit(), and thread_this().
Referenced by registerSignal().
static Thread* lubyk::Thread::thread_this () [inline, static]
Get "this" (used in static callbacks).
Definition at line 209 of file thread.h.
References sThisKey.
Referenced by terminate().
void lubyk::Thread::threadReady () [inline]
This method should be called by started thread when it has properly started an it is ready. The creating thread locks until this method is called.
Definition at line 202 of file thread.h.
References condition_, and lubyk::Condition::signal().
Referenced by lubyk::Worker::doExecute(), and lubyk::Timer< T, Tmethod >::startThread().
Member Data Documentation
Condition lubyk::Thread::condition_ [private]
Definition at line 306 of file thread.h.
Referenced by startThread(), and threadReady().
int lubyk::Thread::normal_sched_policy_ [private]
Thread's original scheduling policy (normal_priority).
Definition at line 299 of file thread.h.
struct sched_param lubyk::Thread::normal_thread_param_ [private]
Scheduling parameters for commands (lower).
Definition at line 300 of file thread.h.
void* lubyk::Thread::owner_ [private]
Definition at line 295 of file thread.h.
Referenced by s_startThread(), and startThread().
void* lubyk::Thread::parameter_
Any parameter that the started method could use.
Definition at line 217 of file thread.h.
Referenced by lubyk::Worker::doExecute(), and startThread().
bool lubyk::Thread::should_run_ [protected]
Definition at line 303 of file thread.h.
Referenced by kill(), quit(), s_start_static_thread(), s_startThread(), shouldRun(), and startThread().
void(* lubyk::Thread::static_method_)(Thread *) [private]
Definition at line 296 of file thread.h.
Referenced by s_start_static_thread(), and startThread().
pthread_key_t lubyk::Thread::sThisKey [static]
Key to retrieve 'this' value from a running thread.
Definition at line 215 of file thread.h.
Referenced by setThreadThis(), and thread_this().
pthread_t lubyk::Thread::thread_id_ [private]
Definition at line 298 of file thread.h.
Referenced by isRunning(), join(), kill(), s_start_static_thread(), s_startThread(), sendSignal(), and startThread().
The documentation for this class was generated from the following file:
/Users/gaspard/git/lubyk/modules/lubyk/include/lubyk/thread.h