lubyk: lubyk::Worker Class Reference
lubyk::Worker Class Reference
#include <worker.h>
Public Member Functions
Worker ()
~Worker ()
LuaStackSize spawn (const char *script, lua_State *L)
void execute (const char *cmd)
int waitpid (int pid)
void exit (int status)
LuaStackSize execPath (lua_State *L)
void run ()
double now ()
Static Public Member Functions
static Worker * getWorker (lua_State *L)
Public Attributes
TimeRef time_ref_
void * zmq_context_
size_t zmq_context_refcount_
Private Member Functions
void doExecute (Thread *runner)
Private Attributes
Implementation * impl_
Detailed Description
The worker should be created only once and is responsible for timing and lua locking.
Bindings info:
string_format:'%f' string_args:'(*userdata)->elapsed()'
Definition at line 56 of file worker.h.
Constructor & Destructor Documentation
lubyk::Worker::Worker ()
Referenced by execute().
lubyk::Worker::~Worker ()
Member Function Documentation
void lubyk::Worker::doExecute (Thread * runner) [inline, private]
Definition at line 208 of file worker.h.
References lubyk::Thread::parameter_, and lubyk::Thread::threadReady().
Referenced by execute().
LuaStackSize lubyk::Worker::execPath (lua_State * L)
Get the current executable's path.
void lubyk::Worker::execute (const char * cmd) [inline]
Execute a system command in a new thread
Definition at line 99 of file worker.h.
References doExecute(), lubyk::Thread::startThread(), and Worker().
void lubyk::Worker::exit (int status)
Exit with a given status.
static Worker* lubyk::Worker::getWorker (lua_State * L) [static]
For testing purpose.
double lubyk::Worker::now () [inline]
Definition at line 118 of file worker.h.
References lubyk::TimeRef::elapsed(), and time_ref_.
void lubyk::Worker::run ()
LuaStackSize lubyk::Worker::spawn (const char * script, lua_State * L)
Start a new process with the given Lua script.
Returns:
new process id or nil on failure
int lubyk::Worker::waitpid (int pid)
Wait for another process to finish (BLOCKING).
Member Data Documentation
Implementation* lubyk::Worker::impl_ [private]
Definition at line 58 of file worker.h.
TimeRef lubyk::Worker::time_ref_
Time reference. All times are in milliseconds (as double) from this reference. 0.0 = The worker's birthdate !
Definition at line 64 of file worker.h.
Referenced by elapsed().
void* lubyk::Worker::zmq_context_
These sets contain the bitfields set by fdSet methods. These sets contain the bitfields after the select operation. Stores the maximum value of all fd sets. Context use by zmq::Socket.
Definition at line 80 of file worker.h.
Referenced by zmq::Socket::Socket().
size_t lubyk::Worker::zmq_context_refcount_
Counts the number of zmq::Socket depending on the socket.
Definition at line 85 of file worker.h.
Referenced by zmq::Socket::Socket().
The documentation for this class was generated from the following file:
/Users/gaspard/git/lubyk/modules/lubyk/include/lubyk/worker.h