lubyk: b2DynamicTree Class Reference
b2DynamicTree Class Reference
#include <b2DynamicTree.h>
Public Member Functions
b2DynamicTree ()
Constructing the tree initializes the node pool.
~b2DynamicTree ()
Destroy the tree, freeing the node pool.
int32 CreateProxy (const b2AABB &aabb, void *userData)
Create a proxy. Provide a tight fitting AABB and a userData pointer.
void DestroyProxy (int32 proxyId)
Destroy a proxy. This asserts if the id is invalid.
bool MoveProxy (int32 proxyId, const b2AABB &aabb1, const b2Vec2 &displacement)
void * GetUserData (int32 proxyId) const
const b2AABB & GetFatAABB (int32 proxyId) const
Get the fat AABB for a proxy.
template<typename T >
void Query (T *callback, const b2AABB &aabb) const
template<typename T >
void RayCast (T *callback, const b2RayCastInput &input) const
void Validate () const
Validate this tree. For testing.
int32 GetHeight () const
int32 GetMaxBalance () const
float32 GetAreaRatio () const
Get the ratio of the sum of the node areas to the root area.
void RebuildBottomUp ()
Build an optimal tree. Very expensive. For testing.
Private Member Functions
int32 AllocateNode ()
void FreeNode (int32 node)
void InsertLeaf (int32 node)
void RemoveLeaf (int32 node)
int32 Balance (int32 index)
int32 ComputeHeight () const
int32 ComputeHeight (int32 nodeId) const
void ValidateStructure (int32 index) const
void ValidateMetrics (int32 index) const
Private Attributes
int32 m_root
b2TreeNode * m_nodes
int32 m_nodeCount
int32 m_nodeCapacity
int32 m_freeList
uint32 m_path
This is used to incrementally traverse the tree for re-balancing.
int32 m_insertionCount
Detailed Description
A dynamic AABB tree broad-phase, inspired by Nathanael Presson's btDbvt. A dynamic tree arranges data in a binary tree to accelerate queries such as volume queries and ray casts. Leafs are proxies with an AABB. In the tree we expand the proxy AABB by b2_fatAABBFactor so that the proxy AABB is bigger than the client object. This allows the client object to move by small amounts without triggering a tree update.
Nodes are pooled and relocatable, so we use node indices rather than pointers.
Definition at line 61 of file b2DynamicTree.h.
Constructor & Destructor Documentation
b2DynamicTree::b2DynamicTree ()
Constructing the tree initializes the node pool.
b2DynamicTree::~b2DynamicTree ()
Destroy the tree, freeing the node pool.
Member Function Documentation
int32 b2DynamicTree::AllocateNode () [private]
int32 b2DynamicTree::Balance (int32 index) [private]
int32 b2DynamicTree::ComputeHeight () const [private]
int32 b2DynamicTree::ComputeHeight (int32 nodeId) const [private]
int32 b2DynamicTree::CreateProxy (const b2AABB & aabb, void * userData)
Create a proxy. Provide a tight fitting AABB and a userData pointer.
void b2DynamicTree::DestroyProxy (int32 proxyId)
Destroy a proxy. This asserts if the id is invalid.
void b2DynamicTree::FreeNode (int32 node) [private]
float32 b2DynamicTree::GetAreaRatio () const
Get the ratio of the sum of the node areas to the root area.
Referenced by b2BroadPhase::GetTreeQuality().
const b2AABB & b2DynamicTree::GetFatAABB (int32 proxyId) const [inline]
Get the fat AABB for a proxy.
Definition at line 157 of file b2DynamicTree.h.
References b2TreeNode::aabb, b2Assert, m_nodeCapacity, and m_nodes.
Referenced by b2BroadPhase::GetFatAABB(), b2BroadPhase::TestOverlap(), and b2BroadPhase::UpdatePairs().
int32 b2DynamicTree::GetHeight () const
Compute the height of the binary tree in O(N) time. Should not be called often.
Referenced by b2BroadPhase::GetTreeHeight().
int32 b2DynamicTree::GetMaxBalance () const
Get the maximum balance of an node in the tree. The balance is the difference in height of the two children of a node.
Referenced by b2BroadPhase::GetTreeBalance().
void * b2DynamicTree::GetUserData (int32 proxyId) const [inline]
Get proxy user data.
Returns:
the proxy user data or 0 if the id is invalid.
Definition at line 151 of file b2DynamicTree.h.
References b2Assert, m_nodeCapacity, m_nodes, and b2TreeNode::userData.
Referenced by b2BroadPhase::GetUserData(), and b2BroadPhase::UpdatePairs().
void b2DynamicTree::InsertLeaf (int32 node) [private]
bool b2DynamicTree::MoveProxy (int32 proxyId, const b2AABB & aabb1, const b2Vec2 & displacement)
Move a proxy with a swepted AABB. If the proxy has moved outside of its fattened AABB, then the proxy is removed from the tree and re-inserted. Otherwise the function returns immediately.
Returns:
true if the proxy was re-inserted.
template<typename T > void b2DynamicTree::Query (T * callback, const b2AABB & aabb) const [inline]
Query an AABB for overlapping proxies. The callback class is called for each proxy that overlaps the supplied AABB.
Definition at line 164 of file b2DynamicTree.h.
References b2TreeNode::aabb, b2_nullNode, b2TestOverlap(), b2TreeNode::child1, b2TreeNode::child2, b2GrowableStack< T, N >::GetCount(), b2TreeNode::IsLeaf(), m_nodes, m_root, node, b2GrowableStack< T, N >::Pop(), and b2GrowableStack< T, N >::Push().
Referenced by b2BroadPhase::Query(), and b2BroadPhase::UpdatePairs().
template<typename T > void b2DynamicTree::RayCast (T * callback, const b2RayCastInput & input) const [inline]
Ray-cast against the proxies in the tree. This relies on the callback to perform a exact ray-cast in the case were the proxy contains a shape. The callback also performs the any collision filtering. This has performance roughly equal to k * log(n), where k is the number of collisions and n is the number of proxies in the tree.
Parameters:
input the ray-cast input data. The ray extends from p1 to p1 + maxFraction * (p2 - p1).
callback a callback class that is called for each proxy that is hit by the ray.
Definition at line 199 of file b2DynamicTree.h.
References b2TreeNode::aabb, b2_nullNode, b2Abs(), b2Assert, b2Cross(), b2Dot(), b2Max(), b2Min(), b2TestOverlap(), c, b2TreeNode::child1, b2TreeNode::child2, b2AABB::GetCenter(), b2GrowableStack< T, N >::GetCount(), b2AABB::GetExtents(), b2TreeNode::IsLeaf(), b2Vec2::LengthSquared(), b2AABB::lowerBound, m_nodes, m_root, b2RayCastInput::maxFraction, node, b2Vec2::Normalize(), b2RayCastInput::p1, b2RayCastInput::p2, p2, b2GrowableStack< T, N >::Pop(), b2GrowableStack< T, N >::Push(), r, b2AABB::upperBound, and value.
Referenced by b2BroadPhase::RayCast().
void b2DynamicTree::RebuildBottomUp ()
Build an optimal tree. Very expensive. For testing.
void b2DynamicTree::RemoveLeaf (int32 node) [private]
void b2DynamicTree::Validate () const
Validate this tree. For testing.
void b2DynamicTree::ValidateMetrics (int32 index) const [private]
void b2DynamicTree::ValidateStructure (int32 index) const [private]
Member Data Documentation
int32 b2DynamicTree::m_freeList [private]
Definition at line 143 of file b2DynamicTree.h.
int32 b2DynamicTree::m_insertionCount [private]
Definition at line 148 of file b2DynamicTree.h.
int32 b2DynamicTree::m_nodeCapacity [private]
Definition at line 141 of file b2DynamicTree.h.
Referenced by GetFatAABB(), and GetUserData().
int32 b2DynamicTree::m_nodeCount [private]
Definition at line 140 of file b2DynamicTree.h.
b2TreeNode* b2DynamicTree::m_nodes [private]
Definition at line 139 of file b2DynamicTree.h.
Referenced by GetFatAABB(), GetUserData(), Query(), and RayCast().
uint32 b2DynamicTree::m_path [private]
This is used to incrementally traverse the tree for re-balancing.
Definition at line 146 of file b2DynamicTree.h.
int32 b2DynamicTree::m_root [private]
Definition at line 137 of file b2DynamicTree.h.
Referenced by Query(), and RayCast().
The documentation for this class was generated from the following file:
/Users/gaspard/git/lubyk/modules/b2/bind/b2DynamicTree.h