lubyk: mimas::Painter Class Reference
mimas::Painter Class Reference
#include <Painter.h>
Public Member Functions
Painter (QWidget *widget)
~Painter ()
void fillRect (int x, int y, int width, int height, const Color &color)
void drawPath (const Path &path)
void setPen (const Pen &pen)
void setPen (float width, const Color &color)
void setPen (float width, float h, float s=1.0, float v=1.0, float a=1.0)
void setBrush (const Brush &brush)
void setBrush (const Color &color)
void setBrush (float h, float s=1.0, float v=1.0, float a=1.0)
void drawPoint (int x, int y)
void drawLine (int x1, int y1, int x2, int y2)
void drawChord (int x, int y, int width, int height, float startAngle, float spanAngle)
void drawRect (float x, float y, float w, float h)
void drawRoundedRect (float x, float y, float w, float h, float xRadius, lua_State *L)
void drawEllipse (int x, int y, int width, int height)
void drawText (float x, float y, float w, float h, int flags, const char *text)
Detailed Description
Painter.
Bindings info:
destructor: 'luaDestroy'
Definition at line 49 of file Painter.h.
Constructor & Destructor Documentation
mimas::Painter::Painter (QWidget * widget) [inline]
Definition at line 52 of file Painter.h.
References MIMAS_DEBUG_GX.
mimas::Painter::~Painter () [inline]
Definition at line 58 of file Painter.h.
References MIMAS_DEBUG_GX.
Member Function Documentation
void mimas::Painter::drawChord (int x, int y, int width, int height, float startAngle, float spanAngle) [inline]
Draw a chord (filled arc). TODO: How the rectangle is used is not clear... Angles are specified in degrees.
Definition at line 117 of file Painter.h.
void mimas::Painter::drawEllipse (int x, int y, int width, int height) [inline]
Draw an ellipse in the given rectangle.
Definition at line 136 of file Painter.h.
void mimas::Painter::drawLine (int x1, int y1, int x2, int y2) [inline]
Draw a single line with the current pen.
Definition at line 110 of file Painter.h.
void mimas::Painter::drawPath (const Path & path) [inline]
Definition at line 66 of file Painter.h.
void mimas::Painter::drawPoint (int x, int y) [inline]
Draw a single point with the current pen.
Definition at line 104 of file Painter.h.
void mimas::Painter::drawRect (float x, float y, float w, float h) [inline]
Draw a rectangle.
Definition at line 123 of file Painter.h.
void mimas::Painter::drawRoundedRect (float x, float y, float w, float h, float xRadius, lua_State * L) [inline]
Default value for yRadius = xRadius.
Definition at line 129 of file Painter.h.
void mimas::Painter::drawText (float x, float y, float w, float h, int flags, const char * text) [inline]
Draw some text.
Definition at line 142 of file Painter.h.
void mimas::Painter::fillRect (int x, int y, int width, int height, const Color & color) [inline]
Definition at line 62 of file Painter.h.
void mimas::Painter::setBrush (const Brush & brush) [inline]
Definition at line 82 of file Painter.h.
Referenced by setBrush().
void mimas::Painter::setBrush (const Color & color) [inline]
Definition at line 86 of file Painter.h.
References setBrush().
void mimas::Painter::setBrush (float h, float s = 1.0, float v = 1.0, float a = 1.0) [inline]
Set brush with the given hsva color.
Definition at line 98 of file Painter.h.
References a, and setBrush().
void mimas::Painter::setPen (const Pen & pen) [inline]
Definition at line 70 of file Painter.h.
Referenced by setPen().
void mimas::Painter::setPen (float width, const Color & color) [inline]
Definition at line 74 of file Painter.h.
References setPen().
void mimas::Painter::setPen (float width, float h, float s = 1.0, float v = 1.0, float a = 1.0) [inline]
Definition at line 78 of file Painter.h.
References a, and setPen().
The documentation for this class was generated from the following file:
/Users/gaspard/git/lubyk/modules/mimas/include/mimas/Painter.h