lubyk: mdns::Location Class Reference
mdns::Location Class Reference
#include <Location.h>
Inherited by mdns::AbstractBrowser::Service.
Public Member Functions
Location (const char *protocol, const char *service_name, const char *hostname, uint port=NO_PORT, uint interface=DEFAULT_INTERFACE)
Location (const char *protocol, const char *hostname, uint port)
Location (const char *protocol, unsigned long ip, uint port)
Location (const char *protocol, const char *service_name)
Location ()
void clear ()
bool operator!= (const Location &other) const
bool operator== (const Location &other) const
const char * protocol () const
const char * name () const
const char * host () const
const unsigned long & ip () const
const uint & port () const
const uint & interface () const
void set_port (uint port)
const std::string inspect () const
Static Public Member Functions
static unsigned long ip_from_hostname (const char *hostname)
static const std::string name_from_ip (unsigned long ip)
Static Public Attributes
static const unsigned long NO_IP = 0
static const unsigned long ANY_IP = 0xFFFFFFFF
static const unsigned long LOOPBACK = (127<<24) + 1
static const uint NO_PORT = 0
static const uint DEFAULT_INTERFACE = 0
Private Attributes
std::string protocol_
std::string name_
std::string host_
unsigned long ip_
uint port_
uint interface_
Friends
class Url
std::ostream & operator<< (std::ostream &out_stream, const Location &location)
uint hashId (const Location &location)
Detailed Description
Browse for devices matching a give service type. Call a lua function when devices are added or removed.
Bindings info:
string_format:'%s' string_args:'(*userdata)->inspect().c_str()'
Definition at line 50 of file Location.h.
Constructor & Destructor Documentation
mdns::Location::Location (const char * protocol, const char * service_name, const char * hostname, uint port = NO_PORT, uint interface = DEFAULT_INTERFACE) [inline]
Definition at line 63 of file Location.h.
mdns::Location::Location (const char * protocol, const char * hostname, uint port) [inline]
Definition at line 75 of file Location.h.
mdns::Location::Location (const char * protocol, unsigned long ip, uint port) [inline]
Definition at line 83 of file Location.h.
mdns::Location::Location (const char * protocol, const char * service_name) [inline]
Definition at line 91 of file Location.h.
mdns::Location::Location () [inline]
Definition at line 98 of file Location.h.
Member Function Documentation
void mdns::Location::clear () [inline]
Definition at line 102 of file Location.h.
References host_, ip_, name_, NO_IP, NO_PORT, port_, and protocol_.
const char* mdns::Location::host () const [inline]
Definition at line 130 of file Location.h.
References host_.
Referenced by mdns::Browser::nextService().
const std::string mdns::Location::inspect () const
Used for debugging: show location with ip and port.
const uint& mdns::Location::interface () const [inline]
Definition at line 142 of file Location.h.
References interface_.
Referenced by mdns::Browser::nextService().
const unsigned long& mdns::Location::ip () const [inline]
Definition at line 134 of file Location.h.
References ip_.
Referenced by mdns::Browser::nextService().
static unsigned long mdns::Location::ip_from_hostname (const char * hostname) [static]
const char* mdns::Location::name () const [inline]
Definition at line 126 of file Location.h.
References name_.
Referenced by mdns::Browser::nextService().
static const std::string mdns::Location::name_from_ip (unsigned long ip) [static]
Referenced by mdns::Browser::nextService().
bool mdns::Location::operator!= (const Location & other) const [inline]
Definition at line 110 of file Location.h.
References operator==().
bool mdns::Location::operator== (const Location & other) const [inline]
Definition at line 114 of file Location.h.
References host_, ip_, NO_IP, port_, and protocol_.
Referenced by operator!=().
const uint& mdns::Location::port () const [inline]
Definition at line 138 of file Location.h.
References port_.
Referenced by mdns::Browser::nextService(), and set_port().
const char* mdns::Location::protocol () const [inline]
Definition at line 122 of file Location.h.
References protocol_.
void mdns::Location::set_port (uint port) [inline]
Definition at line 146 of file Location.h.
References port(), and port_.
Friends And Related Function Documentation
uint hashId (const Location & location) [friend]
std::ostream& operator<< (std::ostream & out_stream, const Location & location) [friend]
friend class Url [friend]
Definition at line 159 of file Location.h.
Member Data Documentation
const unsigned long mdns::Location::ANY_IP = 0xFFFFFFFF [static]
Any local IP.
Definition at line 58 of file Location.h.
const uint mdns::Location::DEFAULT_INTERFACE = 0 [static]
Definition at line 61 of file Location.h.
std::string mdns::Location::host_ [private]
This is the host's name ('gaspard.local', 'example.com').
Definition at line 173 of file Location.h.
Referenced by clear(), host(), and operator==().
uint mdns::Location::interface_ [private]
Interface used to connect to this location (set by mdns Browser).
Definition at line 185 of file Location.h.
Referenced by interface().
unsigned long mdns::Location::ip_ [private]
Once the location has been resolved, we have an IP.
Definition at line 177 of file Location.h.
Referenced by clear(), ip(), and operator==().
const unsigned long mdns::Location::LOOPBACK = (127<<24) + 1 [static]
Definition at line 59 of file Location.h.
std::string mdns::Location::name_ [private]
This contains the service's name ("stage camera").
Definition at line 169 of file Location.h.
Referenced by clear(), and name().
const unsigned long mdns::Location::NO_IP = 0 [static]
IP not configured yet.
Definition at line 55 of file Location.h.
Referenced by clear(), and operator==().
const uint mdns::Location::NO_PORT = 0 [static]
Definition at line 60 of file Location.h.
Referenced by clear().
uint mdns::Location::port_ [private]
Port of the remote object (set when location is resolved)
Definition at line 181 of file Location.h.
Referenced by clear(), operator==(), port(), and set_port().
std::string mdns::Location::protocol_ [private]
Protocol used (oscit, http, ...)
Definition at line 165 of file Location.h.
Referenced by clear(), operator==(), and protocol().
The documentation for this class was generated from the following file:
/Users/gaspard/git/lubyk/modules/mdns/include/mdns/Location.h