lubyk: mimas::Callback Class Reference
mimas::Callback Class Reference
#include <Callback.h>
Inherits mimas::QObject, and lubyk::ThreadedLuaObject.
Classes
class Event
Public Slots
void callback ()
void callback (double value)
void callback (int value)
Public Member Functions
Callback ()
virtual ~Callback ()
void connect (QObject *obj, const char *method, const char *callback)
Static Public Attributes
static const QEvent::Type EventType
Private Member Functions
void setCallbackFromApp (lua_State *L)
void deleteOnCall ()
Private Attributes
int self_in_app_
int app_in_thread_
Friends
class Application
class Slider
Detailed Description
Calls a lua function back.
Bindings info:
lib_name:'Callback_core' ignore: 'callback' super: 'QObject'
Definition at line 52 of file Callback.h.
Constructor & Destructor Documentation
mimas::Callback::Callback () [inline]
Definition at line 59 of file Callback.h.
References MIMAS_DEBUG_CC.
virtual mimas::Callback::~Callback () [inline, virtual]
Definition at line 63 of file Callback.h.
References MIMAS_DEBUG_GC.
Member Function Documentation
void mimas::Callback::callback () [inline, slot]
Definition at line 84 of file Callback.h.
References deleteOnCall(), lubyk::ThreadedLuaObject::lua_, pushLuaCallback, and status.
Referenced by callback().
void mimas::Callback::callback (double value) [inline, slot]
Definition at line 97 of file Callback.h.
References deleteOnCall(), lubyk::ThreadedLuaObject::lua_, pushLuaCallback, and status.
void mimas::Callback::callback (int value) [inline, slot]
Definition at line 112 of file Callback.h.
References callback().
void mimas::Callback::connect (QObject * obj, const char * method, const char * callback) [inline]
Definition at line 67 of file Callback.h.
void mimas::Callback::deleteOnCall () [inline, private]
Definition at line 148 of file Callback.h.
References app_in_thread_, lubyk::ThreadedLuaObject::lua_, and self_in_app_.
Referenced by callback().
void mimas::Callback::setCallbackFromApp (lua_State * L) [inline, private]
Define a callback and store a reference inside the application so that it is not garbage collected too soon.
Definition at line 123 of file Callback.h.
References app_in_thread_, lubyk::ThreadedLuaObject::lua_, and self_in_app_.
Friends And Related Function Documentation
friend class Application [friend]
Definition at line 117 of file Callback.h.
friend class Slider [friend]
Definition at line 118 of file Callback.h.
Member Data Documentation
int mimas::Callback::app_in_thread_ [private]
To unprotect self from garbage collection when deleted.
Definition at line 165 of file Callback.h.
Referenced by deleteOnCall(), and setCallbackFromApp().
const QEvent::Type mimas::Callback::EventType [static]
Definition at line 57 of file Callback.h.
int mimas::Callback::self_in_app_ [private]
To protect from garbage collection before app is deleted.
Definition at line 161 of file Callback.h.
Referenced by deleteOnCall(), and setCallbackFromApp().
The documentation for this class was generated from the following file:
/Users/gaspard/git/lubyk/modules/mimas/include/mimas/Callback.h