lubyk: mimas::Pen Class Reference
mimas::Pen Class Reference
#include <Pen.h>
Public Member Functions
Pen ()
Pen (float width, const Color &color, int style=Qt::SolidLine, int cap=Qt::SquareCap, int join=Qt::MiterJoin)
Pen (float width, float h, float s=1.0, float v=1.0, float a=1.0)
~Pen ()
void setWidth (float w)
void setRgba (float r, float g, float b, float a=1.0)
void setColor (const Color &color)
void setHsva (float h, float s=1.0, float v=1.0, float a=1.0)
void setStyle (int style)
void setCapStyle (int style)
void setJoinStyle (int style)
Detailed Description
Pen used by Painter.
Definition at line 43 of file Pen.h.
Constructor & Destructor Documentation
mimas::Pen::Pen () [inline]
Definition at line 46 of file Pen.h.
References MIMAS_DEBUG_GX.
mimas::Pen::Pen (float width, const Color & color, int style = Qt::SolidLine, int cap = Qt::SquareCap, int join = Qt::MiterJoin) [inline]
Definition at line 50 of file Pen.h.
References MIMAS_DEBUG_GX.
mimas::Pen::Pen (float width, float h, float s = 1.0, float v = 1.0, float a = 1.0) [inline]
Definition at line 55 of file Pen.h.
References MIMAS_DEBUG_GX.
mimas::Pen::~Pen () [inline]
Definition at line 60 of file Pen.h.
References MIMAS_DEBUG_GX.
Member Function Documentation
void mimas::Pen::setCapStyle (int style) [inline]
Definition at line 86 of file Pen.h.
void mimas::Pen::setColor (const Color & color) [inline]
Definition at line 72 of file Pen.h.
Referenced by setHsva(), and setRgba().
void mimas::Pen::setHsva (float h, float s = 1.0, float v = 1.0, float a = 1.0) [inline]
Definition at line 76 of file Pen.h.
References a, color, and setColor().
void mimas::Pen::setJoinStyle (int style) [inline]
Definition at line 90 of file Pen.h.
void mimas::Pen::setRgba (float r, float g, float b, float a = 1.0) [inline]
Definition at line 68 of file Pen.h.
References a, and setColor().
void mimas::Pen::setStyle (int style) [inline]
Definition at line 82 of file Pen.h.
void mimas::Pen::setWidth (float w) [inline]
Definition at line 64 of file Pen.h.
The documentation for this class was generated from the following file:
/Users/gaspard/git/lubyk/modules/mimas/include/mimas/Pen.h