lubyk: lubyk::ScopedSUnlock Class Reference
lubyk::ScopedSUnlock Class Reference
#include <mutex.h>
Inherits lubyk::NonCopyable.
Public Member Functions
ScopedSUnlock (Mutex *mutex)
ScopedSUnlock (Mutex &mutex)
~ScopedSUnlock ()
Private Attributes
Mutex * mutex_ptr_
Detailed Description
Scoped simple Mutex Unlock to release exclusive access to a resource.
Definition at line 100 of file mutex.h.
Constructor & Destructor Documentation
lubyk::ScopedSUnlock::ScopedSUnlock (Mutex * mutex) [inline]
Definition at line 105 of file mutex.h.
References mutex_ptr_, and lubyk::Mutex::unlock().
lubyk::ScopedSUnlock::ScopedSUnlock (Mutex & mutex) [inline]
Definition at line 109 of file mutex.h.
References mutex_ptr_, and lubyk::Mutex::unlock().
lubyk::ScopedSUnlock::~ScopedSUnlock () [inline]
Definition at line 113 of file mutex.h.
References lubyk::Mutex::lock(), and mutex_ptr_.
Member Data Documentation
Mutex* lubyk::ScopedSUnlock::mutex_ptr_ [private]
Definition at line 102 of file mutex.h.
Referenced by ScopedSUnlock(), and ~ScopedSUnlock().
The documentation for this class was generated from the following file:
/Users/gaspard/git/lubyk/modules/lubyk/include/lubyk/mutex.h