lubyk: mimas::GLWidget Class Reference
mimas::GLWidget Class Reference
#include <GLWidget.h>
Inherits lubyk::ThreadedLuaObject.
Classes
class OpenGLScene
Public Member Functions
GLWidget ()
~GLWidget ()
void addWidgetToScene (QWidget *widget, float x=0, float y=0)
QString cssClass () const
void updateGL ()
Public Attributes
QSize size_hint_
Protected Member Functions
void resizeEvent (QResizeEvent *event)
virtual void initializeGL ()
virtual void resizeGL (int width, int height)
virtual void paintGL ()
void keyPressEvent (QKeyEvent *event)
void keyReleaseEvent (QKeyEvent *event)
Properties
QString class
OpenGLScene * gl_scene_
Private Member Functions
void keyboard (QKeyEvent *event, bool isPressed)
Detailed Description
GLWidget This class lets you draw OpenGL elements with Widgets on top. http://doc.trolltech.com/qq/qq26-openglcanvas.html
Bindings info:
destructor: 'luaDestroy' super: 'QWidget'
Definition at line 52 of file GLWidget.h.
Constructor & Destructor Documentation
mimas::GLWidget::GLWidget () [inline]
Definition at line 81 of file GLWidget.h.
References MIMAS_DEBUG_CC.
mimas::GLWidget::~GLWidget () [inline]
Definition at line 95 of file GLWidget.h.
References MIMAS_DEBUG_GC.
Member Function Documentation
void mimas::GLWidget::addWidgetToScene (QWidget * widget, float x = 0, float y = 0) [inline]
Definition at line 99 of file GLWidget.h.
References mimas::QWidget::move(), and mimas::QWidget::show().
QString mimas::GLWidget::cssClass () const [inline]
Definition at line 105 of file GLWidget.h.
References parent.
virtual void mimas::GLWidget::initializeGL () [inline, protected, virtual]
Definition at line 125 of file GLWidget.h.
References pushLuaCallback, and status.
Referenced by mimas::GLWidget::OpenGLScene::drawBackground().
void mimas::GLWidget::keyboard (QKeyEvent * event, bool isPressed) [inline, private]
Definition at line 216 of file GLWidget.h.
References pushLuaCallback, and status.
void mimas::GLWidget::keyPressEvent (QKeyEvent * event) [inline, protected]
Definition at line 167 of file GLWidget.h.
void mimas::GLWidget::keyReleaseEvent (QKeyEvent * event) [inline, protected]
Definition at line 171 of file GLWidget.h.
virtual void mimas::GLWidget::paintGL () [inline, protected, virtual]
Definition at line 151 of file GLWidget.h.
References pushLuaCallback, and status.
Referenced by mimas::GLWidget::OpenGLScene::drawBackground().
void mimas::GLWidget::resizeEvent (QResizeEvent * event) [inline, protected]
Force the scene to have the same size as the view.
Definition at line 119 of file GLWidget.h.
virtual void mimas::GLWidget::resizeGL (int width, int height) [inline, protected, virtual]
Definition at line 137 of file GLWidget.h.
References pushLuaCallback, and status.
Referenced by mimas::GLWidget::OpenGLScene::drawBackground().
void mimas::GLWidget::updateGL () [inline]
Definition at line 112 of file GLWidget.h.
Member Data Documentation
QSize mimas::GLWidget::size_hint_
Definition at line 109 of file GLWidget.h.
Property Documentation
QString mimas::GLWidget::class [read]
Definition at line 55 of file GLWidget.h.
OpenGLScene* mimas::GLWidget::gl_scene_
Definition at line 79 of file GLWidget.h.
The documentation for this class was generated from the following file:
/Users/gaspard/git/lubyk/modules/mimas/include/mimas/GLWidget.h