lubyk: lubyk::ScopedSLock Class Reference
lubyk::ScopedSLock Class Reference
#include <mutex.h>
Inherits lubyk::NonCopyable.
Public Member Functions
ScopedSLock (Mutex *mutex)
ScopedSLock (Mutex &mutex)
~ScopedSLock ()
Private Attributes
Mutex * mutex_ptr_
Detailed Description
Scoped simple Mutex Lock for exclusive access to a resource.
Definition at line 80 of file mutex.h.
Constructor & Destructor Documentation
lubyk::ScopedSLock::ScopedSLock (Mutex * mutex) [inline]
Definition at line 82 of file mutex.h.
References lubyk::Mutex::lock(), and mutex_ptr_.
lubyk::ScopedSLock::ScopedSLock (Mutex & mutex) [inline]
Definition at line 86 of file mutex.h.
References lubyk::Mutex::lock(), and mutex_ptr_.
lubyk::ScopedSLock::~ScopedSLock () [inline]
Definition at line 90 of file mutex.h.
References mutex_ptr_, and lubyk::Mutex::unlock().
Member Data Documentation
Mutex* lubyk::ScopedSLock::mutex_ptr_ [private]
Definition at line 94 of file mutex.h.
Referenced by ScopedSLock(), and ~ScopedSLock().
The documentation for this class was generated from the following file:
/Users/gaspard/git/lubyk/modules/lubyk/include/lubyk/mutex.h