lubyk: b2BroadPhase Class Reference
b2BroadPhase Class Reference
#include <b2BroadPhase.h>
Public Types
enum { e_nullProxy = -1 }
Public Member Functions
b2BroadPhase ()
~b2BroadPhase ()
int32 CreateProxy (const b2AABB &aabb, void *userData)
void DestroyProxy (int32 proxyId)
Destroy a proxy. It is up to the client to remove any pairs.
void MoveProxy (int32 proxyId, const b2AABB &aabb, const b2Vec2 &displacement)
void TouchProxy (int32 proxyId)
Call to trigger a re-processing of it's pairs on the next call to UpdatePairs.
const b2AABB & GetFatAABB (int32 proxyId) const
Get the fat AABB for a proxy.
void * GetUserData (int32 proxyId) const
Get user data from a proxy. Returns NULL if the id is invalid.
bool TestOverlap (int32 proxyIdA, int32 proxyIdB) const
Test overlap of fat AABBs.
int32 GetProxyCount () const
Get the number of proxies.
template<typename T >
void UpdatePairs (T *callback)
Update the pairs. This results in pair callbacks. This can only add pairs.
template<typename T >
void Query (T *callback, const b2AABB &aabb) const
template<typename T >
void RayCast (T *callback, const b2RayCastInput &input) const
int32 GetTreeHeight () const
Get the height of the embedded tree.
int32 GetTreeBalance () const
Get the balance of the embedded tree.
float32 GetTreeQuality () const
Get the quality metric of the embedded tree.
Private Member Functions
void BufferMove (int32 proxyId)
void UnBufferMove (int32 proxyId)
bool QueryCallback (int32 proxyId)
Private Attributes
b2DynamicTree m_tree
int32 m_proxyCount
int32 * m_moveBuffer
int32 m_moveCapacity
int32 m_moveCount
b2Pair * m_pairBuffer
int32 m_pairCapacity
int32 m_pairCount
int32 m_queryProxyId
Friends
class b2DynamicTree
Detailed Description
The broad-phase is used for computing pairs and performing volume queries and ray casts. This broad-phase does not persist pairs. Instead, this reports potentially new pairs. It is up to the client to consume the new pairs and to track subsequent overlap.
Definition at line 37 of file b2BroadPhase.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
e_nullProxy
Definition at line 41 of file b2BroadPhase.h.
Constructor & Destructor Documentation
b2BroadPhase::b2BroadPhase ()
b2BroadPhase::~b2BroadPhase ()
Member Function Documentation
void b2BroadPhase::BufferMove (int32 proxyId) [private]
int32 b2BroadPhase::CreateProxy (const b2AABB & aabb, void * userData)
Create a proxy with an initial AABB. Pairs are not reported until UpdatePairs is called.
void b2BroadPhase::DestroyProxy (int32 proxyId)
Destroy a proxy. It is up to the client to remove any pairs.
const b2AABB & b2BroadPhase::GetFatAABB (int32 proxyId) const [inline]
Get the fat AABB for a proxy.
Definition at line 155 of file b2BroadPhase.h.
References b2DynamicTree::GetFatAABB(), and m_tree.
int32 b2BroadPhase::GetProxyCount () const [inline]
Get the number of proxies.
Definition at line 160 of file b2BroadPhase.h.
References m_proxyCount.
int32 b2BroadPhase::GetTreeBalance () const [inline]
Get the balance of the embedded tree.
Definition at line 170 of file b2BroadPhase.h.
References b2DynamicTree::GetMaxBalance(), and m_tree.
int32 b2BroadPhase::GetTreeHeight () const [inline]
Get the height of the embedded tree.
Definition at line 165 of file b2BroadPhase.h.
References b2DynamicTree::GetHeight(), and m_tree.
float32 b2BroadPhase::GetTreeQuality () const [inline]
Get the quality metric of the embedded tree.
Definition at line 175 of file b2BroadPhase.h.
References b2DynamicTree::GetAreaRatio(), and m_tree.
void * b2BroadPhase::GetUserData (int32 proxyId) const [inline]
Get user data from a proxy. Returns NULL if the id is invalid.
Definition at line 143 of file b2BroadPhase.h.
References b2DynamicTree::GetUserData(), and m_tree.
void b2BroadPhase::MoveProxy (int32 proxyId, const b2AABB & aabb, const b2Vec2 & displacement)
Call MoveProxy as many times as you like, then when you are done call UpdatePairs to finalized the proxy pairs (for your time step).
template<typename T > void b2BroadPhase::Query (T * callback, const b2AABB & aabb) const [inline]
Query an AABB for overlapping proxies. The callback class is called for each proxy that overlaps the supplied AABB.
Definition at line 237 of file b2BroadPhase.h.
References m_tree, and b2DynamicTree::Query().
bool b2BroadPhase::QueryCallback (int32 proxyId) [private]
template<typename T > void b2BroadPhase::RayCast (T * callback, const b2RayCastInput & input) const [inline]
Ray-cast against the proxies in the tree. This relies on the callback to perform a exact ray-cast in the case were the proxy contains a shape. The callback also performs the any collision filtering. This has performance roughly equal to k * log(n), where k is the number of collisions and n is the number of proxies in the tree.
Parameters:
input the ray-cast input data. The ray extends from p1 to p1 + maxFraction * (p2 - p1).
callback a callback class that is called for each proxy that is hit by the ray.
Definition at line 243 of file b2BroadPhase.h.
References m_tree, and b2DynamicTree::RayCast().
bool b2BroadPhase::TestOverlap (int32 proxyIdA, int32 proxyIdB) const [inline]
Test overlap of fat AABBs.
Definition at line 148 of file b2BroadPhase.h.
References b2TestOverlap(), b2DynamicTree::GetFatAABB(), and m_tree.
void b2BroadPhase::TouchProxy (int32 proxyId)
Call to trigger a re-processing of it's pairs on the next call to UpdatePairs.
void b2BroadPhase::UnBufferMove (int32 proxyId) [private]
template<typename T > void b2BroadPhase::UpdatePairs (T * callback)
Update the pairs. This results in pair callbacks. This can only add pairs.
Definition at line 181 of file b2BroadPhase.h.
References b2PairLessThan(), e_nullProxy, b2DynamicTree::GetFatAABB(), b2DynamicTree::GetUserData(), m_moveBuffer, m_moveCount, m_pairBuffer, m_pairCount, m_queryProxyId, m_tree, b2Pair::proxyIdA, b2Pair::proxyIdB, and b2DynamicTree::Query().
Friends And Related Function Documentation
friend class b2DynamicTree [friend]
Definition at line 105 of file b2BroadPhase.h.
Member Data Documentation
int32* b2BroadPhase::m_moveBuffer [private]
Definition at line 116 of file b2BroadPhase.h.
Referenced by UpdatePairs().
int32 b2BroadPhase::m_moveCapacity [private]
Definition at line 117 of file b2BroadPhase.h.
int32 b2BroadPhase::m_moveCount [private]
Definition at line 118 of file b2BroadPhase.h.
Referenced by UpdatePairs().
b2Pair* b2BroadPhase::m_pairBuffer [private]
Definition at line 120 of file b2BroadPhase.h.
Referenced by UpdatePairs().
int32 b2BroadPhase::m_pairCapacity [private]
Definition at line 121 of file b2BroadPhase.h.
int32 b2BroadPhase::m_pairCount [private]
Definition at line 122 of file b2BroadPhase.h.
Referenced by UpdatePairs().
int32 b2BroadPhase::m_proxyCount [private]
Definition at line 114 of file b2BroadPhase.h.
Referenced by GetProxyCount().
int32 b2BroadPhase::m_queryProxyId [private]
Definition at line 124 of file b2BroadPhase.h.
Referenced by UpdatePairs().
b2DynamicTree b2BroadPhase::m_tree [private]
Definition at line 112 of file b2BroadPhase.h.
Referenced by GetFatAABB(), GetTreeBalance(), GetTreeHeight(), GetTreeQuality(), GetUserData(), Query(), RayCast(), TestOverlap(), and UpdatePairs().
The documentation for this class was generated from the following file:
/Users/gaspard/git/lubyk/modules/b2/bind/b2BroadPhase.h