lubyk: mimas::QWidget Class Reference
mimas::QWidget Class Reference
#include <QWidget.h>
Inherited by mimas::Slider, and mimas::Widget.
Public Member Functions
void move (int x, int y)
void resize (int w, int h)
int x ()
int y ()
int width ()
int height ()
void setParent (QWidget *parent)
void update ()
void setMinimumSize (float w, float h)
void setMouseTracking (bool enable)
bool close ()
bool isVisible ()
void show ()
void hide ()
void lower ()
void raise ()
void activateWindow ()
bool isFullScreen ()
void addAction (Action *action)
void widget ()
void addWidget (QWidget *widget, float x=0, float y=0)
void size ()
void setStyle (const char *text)
void setStyleSheet (const char *text)
void textSize (const char *text)
void setSizeHint (float w, float h)
void setSizePolicy (int horizontal, int vertical)
void showFullScreen (bool enable=true)
void swapFullScreen ()
LuaStackSize globalPosition ()
LuaStackSize position ()
void globalMove (float x, float y)
Detailed Description
This is a dummy class to create bindings for objects inheriting from Qt's QWidget.
See also:
Widget
QObject
Bindings info:
bind: 'QWidget.yml' super: 'QObject'
Definition at line 11 of file QWidget.h.
Member Function Documentation
void mimas::QWidget::activateWindow ()
void mimas::QWidget::addAction (Action * action)
void mimas::QWidget::addWidget (QWidget * widget, float x = 0, float y = 0)
bool mimas::QWidget::close ()
void mimas::QWidget::globalMove (float x, float y)
Move the widget to the given global coordinates.
LuaStackSize mimas::QWidget::globalPosition ()
Returns (x,y) position of the widget in the global screen coordinates.
int mimas::QWidget::height ()
Reimplemented in mimas::Slider.
void mimas::QWidget::hide ()
bool mimas::QWidget::isFullScreen ()
bool mimas::QWidget::isVisible ()
void mimas::QWidget::lower ()
void mimas::QWidget::move (int x, int y)
Reimplemented in mimas::Slider.
Referenced by mimas::GLWidget::addWidgetToScene().
LuaStackSize mimas::QWidget::position ()
Returns (x,y) position of the widget in the parent coordinates.
void mimas::QWidget::raise ()
void mimas::QWidget::resize (int w, int h)
Reimplemented in mimas::Slider.
void mimas::QWidget::setMinimumSize (float w, float h)
void mimas::QWidget::setMouseTracking (bool enable)
Receive mouse move events even if no button is pressed.
void mimas::QWidget::setParent (QWidget * parent)
void mimas::QWidget::setSizeHint (float w, float h)
Set the prefered size. Use setSizePolicy to define how the widget resizes compared to this value.
void mimas::QWidget::setSizePolicy (int horizontal, int vertical)
Control how the widget behaves in a layout related to it's sizeHint().
void mimas::QWidget::setStyle (const char * text)
Reimplemented in mimas::Slider.
void mimas::QWidget::setStyleSheet (const char * text)
Reimplemented in mimas::Slider.
void mimas::QWidget::show ()
Referenced by mimas::GLWidget::addWidgetToScene().
void mimas::QWidget::showFullScreen (bool enable = true)
void mimas::QWidget::size ()
Return the size of the widget as a pair (width, height).
void mimas::QWidget::swapFullScreen ()
Swap fullscreen mode.
void mimas::QWidget::textSize (const char * text)
Get size of text with current widget font.
void mimas::QWidget::update ()
Referenced by mimas::Label::setHue(), and mimas::Label::setText().
void mimas::QWidget::widget ()
Reimplemented in mimas::Slider.
int mimas::QWidget::width ()
Reimplemented in mimas::Slider.
int mimas::QWidget::x ()
Reimplemented in mimas::Slider.
int mimas::QWidget::y ()
Reimplemented in mimas::Slider.
The documentation for this class was generated from the following file:
/Users/gaspard/git/lubyk/modules/mimas/bind/QWidget.h