lubyk: lubyk::Timer< T, Tmethod > Class Template Reference
lubyk::Timer< T, Tmethod > Class Template Reference
#include <timer.h>
Public Member Functions
Timer (T *owner, time_t interval=0, bool trigger_on_start=true)
~Timer ()
void start (time_t interval, bool trigger_on_start=true)
void start (bool trigger_on_start=true)
void stop ()
void join ()
time_t interval ()
void setInterval (time_t interval)
void stopFromLoop ()
void setIntervalFromLoop (time_t interval)
bool isRunning () const
Private Member Functions
void run ()
void interrupt ()
void startThread (Thread *runner)
Static Private Member Functions
static void interruptSleep (int sig)
Private Attributes
T * owner_
time_t interval_
time_t last_interval_
TimeRef time_ref_
RMutex mutex_
Thread thread_
bool is_running_
bool should_run_
bool trigger_on_start_
Detailed Description
template<class T, void(T::*)() Tmethod>
class lubyk::Timer< T, Tmethod >
Definition at line 40 of file timer.h.
Constructor & Destructor Documentation
template<class T , void(T::*)() Tmethod> lubyk::Timer< T, Tmethod >::Timer (T * owner, time_t interval = 0, bool trigger_on_start = true) [inline]
Definition at line 42 of file timer.h.
Referenced by lubyk::Timer< T, Tmethod >::start().
template<class T , void(T::*)() Tmethod> lubyk::Timer< T, Tmethod >::~Timer () [inline]
Definition at line 49 of file timer.h.
References lubyk::Timer< T, Tmethod >::interrupt(), lubyk::Timer< T, Tmethod >::is_running_, and lubyk::Timer< T, Tmethod >::should_run_.
Member Function Documentation
template<class T , void(T::*)() Tmethod> void lubyk::Timer< T, Tmethod >::interrupt () [inline, private]
Must be called within a loop lock.
Definition at line 192 of file timer.h.
References lubyk::Thread::sendSignal(), and lubyk::Timer< T, Tmethod >::thread_.
Referenced by lubyk::Timer< T, Tmethod >::setInterval(), lubyk::Timer< T, Tmethod >::start(), lubyk::Timer< T, Tmethod >::stop(), and lubyk::Timer< T, Tmethod >::~Timer().
template<class T , void(T::*)() Tmethod> static void lubyk::Timer< T, Tmethod >::interruptSleep (int sig) [inline, static, private]
Definition at line 183 of file timer.h.
Referenced by lubyk::Timer< T, Tmethod >::startThread().
template<class T , void(T::*)() Tmethod> time_t lubyk::Timer< T, Tmethod >::interval () [inline]
Definition at line 96 of file timer.h.
References lubyk::Timer< T, Tmethod >::interval_.
Referenced by lubyk::Timer< T, Tmethod >::setInterval(), lubyk::Timer< T, Tmethod >::setIntervalFromLoop(), and lubyk::Timer< T, Tmethod >::start().
template<class T , void(T::*)() Tmethod> bool lubyk::Timer< T, Tmethod >::isRunning () const [inline]
Definition at line 120 of file timer.h.
References lubyk::Timer< T, Tmethod >::is_running_.
template<class T , void(T::*)() Tmethod> void lubyk::Timer< T, Tmethod >::join () [inline]
Definition at line 91 of file timer.h.
References lubyk::Timer< T, Tmethod >::is_running_, lubyk::Thread::join(), and lubyk::Timer< T, Tmethod >::thread_.
template<class T , void(T::*)() Tmethod> void lubyk::Timer< T, Tmethod >::run () [inline, private]
Definition at line 125 of file timer.h.
References lubyk::TimeRef::elapsed(), lubyk::Timer< T, Tmethod >::interval_, lubyk::Timer< T, Tmethod >::is_running_, k, lubyk::Timer< T, Tmethod >::last_interval_, lubyk::Timer< T, Tmethod >::mutex_, lubyk::Timer< T, Tmethod >::owner_, lubyk::Timer< T, Tmethod >::should_run_, lubyk::Timer< T, Tmethod >::time_ref_, and lubyk::Timer< T, Tmethod >::trigger_on_start_.
Referenced by lubyk::Timer< T, Tmethod >::startThread().
template<class T , void(T::*)() Tmethod> void lubyk::Timer< T, Tmethod >::setInterval (time_t interval) [inline]
Set interval in [ms].
Definition at line 102 of file timer.h.
References lubyk::Timer< T, Tmethod >::interrupt(), lubyk::Timer< T, Tmethod >::interval(), lubyk::Timer< T, Tmethod >::interval_, lubyk::Timer< T, Tmethod >::is_running_, lubyk::Timer< T, Tmethod >::last_interval_, and lubyk::Timer< T, Tmethod >::mutex_.
template<class T , void(T::*)() Tmethod> void lubyk::Timer< T, Tmethod >::setIntervalFromLoop (time_t interval) [inline]
Definition at line 115 of file timer.h.
References lubyk::Timer< T, Tmethod >::interval(), lubyk::Timer< T, Tmethod >::interval_, and lubyk::Timer< T, Tmethod >::last_interval_.
template<class T , void(T::*)() Tmethod> void lubyk::Timer< T, Tmethod >::start (time_t interval, bool trigger_on_start = true) [inline]
Definition at line 58 of file timer.h.
References lubyk::Timer< T, Tmethod >::interrupt(), lubyk::Timer< T, Tmethod >::interval(), lubyk::Timer< T, Tmethod >::interval_, lubyk::Timer< T, Tmethod >::is_running_, lubyk::Thread::join(), lubyk::Timer< T, Tmethod >::last_interval_, lubyk::Timer< T, Tmethod >::mutex_, lubyk::Timer< T, Tmethod >::should_run_, lubyk::Thread::startThread(), lubyk::Timer< T, Tmethod >::startThread(), lubyk::Timer< T, Tmethod >::thread_, lubyk::Timer< T, Tmethod >::Timer(), and lubyk::Timer< T, Tmethod >::trigger_on_start_.
template<class T , void(T::*)() Tmethod> void lubyk::Timer< T, Tmethod >::start (bool trigger_on_start = true) [inline]
Definition at line 71 of file timer.h.
References lubyk::Timer< T, Tmethod >::interrupt(), lubyk::Timer< T, Tmethod >::is_running_, lubyk::Thread::join(), lubyk::Timer< T, Tmethod >::mutex_, lubyk::Timer< T, Tmethod >::should_run_, lubyk::Thread::startThread(), lubyk::Timer< T, Tmethod >::startThread(), lubyk::Timer< T, Tmethod >::thread_, lubyk::Timer< T, Tmethod >::Timer(), and lubyk::Timer< T, Tmethod >::trigger_on_start_.
template<class T , void(T::*)() Tmethod> void lubyk::Timer< T, Tmethod >::startThread (Thread * runner) [inline, private]
Definition at line 196 of file timer.h.
References lubyk::Thread::highPriority(), lubyk::Timer< T, Tmethod >::interruptSleep(), lubyk::Timer< T, Tmethod >::is_running_, lubyk::Timer< T, Tmethod >::run(), lubyk::Timer< T, Tmethod >::should_run_, and lubyk::Thread::threadReady().
Referenced by lubyk::Timer< T, Tmethod >::start().
template<class T , void(T::*)() Tmethod> void lubyk::Timer< T, Tmethod >::stop () [inline]
Definition at line 82 of file timer.h.
References lubyk::Timer< T, Tmethod >::interrupt(), lubyk::Timer< T, Tmethod >::is_running_, lubyk::Thread::join(), lubyk::Timer< T, Tmethod >::mutex_, lubyk::Timer< T, Tmethod >::should_run_, and lubyk::Timer< T, Tmethod >::thread_.
template<class T , void(T::*)() Tmethod> void lubyk::Timer< T, Tmethod >::stopFromLoop () [inline]
Definition at line 111 of file timer.h.
References lubyk::Timer< T, Tmethod >::should_run_.
Member Data Documentation
template<class T , void(T::*)() Tmethod> time_t lubyk::Timer< T, Tmethod >::interval_ [private]
Loop interval.
Definition at line 211 of file timer.h.
Referenced by lubyk::Timer< T, Tmethod >::interval(), lubyk::Timer< T, Tmethod >::run(), lubyk::Timer< T, Tmethod >::setInterval(), lubyk::Timer< T, Tmethod >::setIntervalFromLoop(), and lubyk::Timer< T, Tmethod >::start().
template<class T , void(T::*)() Tmethod> bool lubyk::Timer< T, Tmethod >::is_running_ [private]
Flag indicating if the thread is actually running.
Definition at line 233 of file timer.h.
Referenced by lubyk::Timer< T, Tmethod >::isRunning(), lubyk::Timer< T, Tmethod >::join(), lubyk::Timer< T, Tmethod >::run(), lubyk::Timer< T, Tmethod >::setInterval(), lubyk::Timer< T, Tmethod >::start(), lubyk::Timer< T, Tmethod >::startThread(), lubyk::Timer< T, Tmethod >::stop(), and lubyk::Timer< T, Tmethod >::~Timer().
template<class T , void(T::*)() Tmethod> time_t lubyk::Timer< T, Tmethod >::last_interval_ [private]
We need this to anchor next_fire in case interval changes.
Definition at line 216 of file timer.h.
Referenced by lubyk::Timer< T, Tmethod >::run(), lubyk::Timer< T, Tmethod >::setInterval(), lubyk::Timer< T, Tmethod >::setIntervalFromLoop(), and lubyk::Timer< T, Tmethod >::start().
template<class T , void(T::*)() Tmethod> RMutex lubyk::Timer< T, Tmethod >::mutex_ [private]
Protect internals.
Definition at line 225 of file timer.h.
Referenced by lubyk::Timer< T, Tmethod >::run(), lubyk::Timer< T, Tmethod >::setInterval(), lubyk::Timer< T, Tmethod >::start(), and lubyk::Timer< T, Tmethod >::stop().
template<class T , void(T::*)() Tmethod> T* lubyk::Timer< T, Tmethod >::owner_ [private]
Object to trigger.
Definition at line 207 of file timer.h.
Referenced by lubyk::Timer< T, Tmethod >::run().
template<class T , void(T::*)() Tmethod> bool lubyk::Timer< T, Tmethod >::should_run_ [private]
Flag indicating that we want the timer to fire or die.
Definition at line 237 of file timer.h.
Referenced by lubyk::Timer< T, Tmethod >::run(), lubyk::Timer< T, Tmethod >::start(), lubyk::Timer< T, Tmethod >::startThread(), lubyk::Timer< T, Tmethod >::stop(), lubyk::Timer< T, Tmethod >::stopFromLoop(), and lubyk::Timer< T, Tmethod >::~Timer().
template<class T , void(T::*)() Tmethod> Thread lubyk::Timer< T, Tmethod >::thread_ [private]
Running thread.
Definition at line 229 of file timer.h.
Referenced by lubyk::Timer< T, Tmethod >::interrupt(), lubyk::Timer< T, Tmethod >::join(), lubyk::Timer< T, Tmethod >::start(), and lubyk::Timer< T, Tmethod >::stop().
template<class T , void(T::*)() Tmethod> TimeRef lubyk::Timer< T, Tmethod >::time_ref_ [private]
We want to hold very precise timing.
Definition at line 220 of file timer.h.
Referenced by lubyk::Timer< T, Tmethod >::run().
template<class T , void(T::*)() Tmethod> bool lubyk::Timer< T, Tmethod >::trigger_on_start_ [private]
Set this to true to trigger right away on timer start.
Definition at line 241 of file timer.h.
Referenced by lubyk::Timer< T, Tmethod >::run(), and lubyk::Timer< T, Tmethod >::start().
The documentation for this class was generated from the following file:
/Users/gaspard/git/lubyk/modules/lubyk/include/lubyk/timer.h