lubyk: mimas::Label Class Reference
mimas::Label Class Reference
#include <Label.h>
Inherits lubyk::LuaObject.
Public Member Functions
Label (const char *title=NULL)
Label (const char *title, QWidget *parent)
~Label ()
QString cssClass () const
QWidget * widget ()
QObject * object ()
LuaStackSize name (lua_State *L)
void setName (const char *name)
void move (int x, int y)
void resize (int w, int h)
int x ()
int y ()
int width ()
int height ()
void setStyle (const char *text)
void setStyleSheet (const char *text)
void setHue (float hue)
float hue ()
void setText (const char *text)
Properties
QString class
Private Member Functions
virtual void paintEvent (QPaintEvent *event)
Private Attributes
float hue_
Detailed Description
Label widget.
Bindings info:
lib_name:'Label_core' destructor: 'luaDestroy'
Definition at line 43 of file Label.h.
Constructor & Destructor Documentation
mimas::Label::Label (const char * title = NULL) [inline]
Definition at line 48 of file Label.h.
References MIMAS_DEBUG_CC.
mimas::Label::Label (const char * title, QWidget * parent) [inline]
Definition at line 54 of file Label.h.
References MIMAS_DEBUG_CC.
mimas::Label::~Label () [inline]
Definition at line 60 of file Label.h.
References MIMAS_DEBUG_GC.
Member Function Documentation
QString mimas::Label::cssClass () const [inline]
Definition at line 66 of file Label.h.
Referenced by setStyle().
int mimas::Label::height () [inline]
Definition at line 111 of file Label.h.
float mimas::Label::hue () [inline]
Definition at line 128 of file Label.h.
References hue_.
Referenced by setHue().
void mimas::Label::move (int x, int y) [inline]
Definition at line 91 of file Label.h.
LuaStackSize mimas::Label::name (lua_State * L) [inline]
Get the widget's name.
Definition at line 80 of file Label.h.
References data.
QObject* mimas::Label::object () [inline]
Definition at line 74 of file Label.h.
virtual void mimas::Label::paintEvent (QPaintEvent * event) [private, virtual]
void mimas::Label::resize (int w, int h) [inline]
Definition at line 95 of file Label.h.
void mimas::Label::setHue (float hue) [inline]
Definition at line 123 of file Label.h.
References hue(), hue_, and mimas::QWidget::update().
void mimas::Label::setName (const char * name) [inline]
Set the widget's name.
Definition at line 87 of file Label.h.
void mimas::Label::setStyle (const char * text) [inline]
Definition at line 115 of file Label.h.
References cssClass(), and setStyleSheet().
void mimas::Label::setStyleSheet (const char * text) [inline]
Definition at line 119 of file Label.h.
Referenced by setStyle().
void mimas::Label::setText (const char * text) [inline]
Definition at line 134 of file Label.h.
References mimas::QWidget::update().
QWidget* mimas::Label::widget () [inline]
Definition at line 70 of file Label.h.
int mimas::Label::width () [inline]
Definition at line 107 of file Label.h.
int mimas::Label::x () [inline]
Definition at line 99 of file Label.h.
int mimas::Label::y () [inline]
Definition at line 103 of file Label.h.
Member Data Documentation
float mimas::Label::hue_ [private]
The component's color.
Definition at line 144 of file Label.h.
Referenced by hue(), and setHue().
Property Documentation
QString mimas::Label::class [read]
Definition at line 46 of file Label.h.
The documentation for this class was generated from the following file:
/Users/gaspard/git/lubyk/modules/mimas/include/mimas/Label.h