lubyk: mimas::Color Class Reference
mimas::Color Class Reference
#include <Color.h>
Public Member Functions
Color ()
Color (float h, float s=1.0, float v=1.0, float a=1.0)
~Color ()
float hue () const
float saturation () const
float value () const
float alpha () const
void setRgba (float r, float g, float b, float a=1.0)
void setHsva (float h, float s=1.0, float v=1.0, float a=1.0)
void setHue (float h)
void setSaturation (float s)
void setValue (float v)
void setAlpha (float a)
Color * colorWithHue (float h)
Color * colorWithSaturation (float s)
Color * colorWithValue (float v)
Color * colorWithAlpha (float a)
Detailed Description
Color used by Painter.
Definition at line 42 of file Color.h.
Constructor & Destructor Documentation
mimas::Color::Color () [inline]
Definition at line 45 of file Color.h.
References MIMAS_DEBUG_GX.
Referenced by colorWithAlpha(), colorWithHue(), colorWithSaturation(), and colorWithValue().
mimas::Color::Color (float h, float s = 1.0, float v = 1.0, float a = 1.0) [inline]
Create a color from a given hue, saturation, value and alpha. All values are in the range 0..1
Definition at line 52 of file Color.h.
References a, and MIMAS_DEBUG_GX.
mimas::Color::~Color () [inline]
Definition at line 57 of file Color.h.
References MIMAS_DEBUG_GX.
Member Function Documentation
float mimas::Color::alpha () const [inline]
Definition at line 73 of file Color.h.
Color* mimas::Color::colorWithAlpha (float a) [inline]
Definition at line 113 of file Color.h.
References Color().
Color* mimas::Color::colorWithHue (float h) [inline]
Definition at line 101 of file Color.h.
References Color().
Color* mimas::Color::colorWithSaturation (float s) [inline]
Definition at line 105 of file Color.h.
References Color().
Color* mimas::Color::colorWithValue (float v) [inline]
Definition at line 109 of file Color.h.
References Color().
float mimas::Color::hue () const [inline]
Definition at line 61 of file Color.h.
float mimas::Color::saturation () const [inline]
Definition at line 65 of file Color.h.
void mimas::Color::setAlpha (float a) [inline]
Definition at line 97 of file Color.h.
void mimas::Color::setHsva (float h, float s = 1.0, float v = 1.0, float a = 1.0) [inline]
Definition at line 81 of file Color.h.
References a.
void mimas::Color::setHue (float h) [inline]
Definition at line 85 of file Color.h.
void mimas::Color::setRgba (float r, float g, float b, float a = 1.0) [inline]
Definition at line 77 of file Color.h.
References a.
void mimas::Color::setSaturation (float s) [inline]
Definition at line 89 of file Color.h.
void mimas::Color::setValue (float v) [inline]
Definition at line 93 of file Color.h.
float mimas::Color::value () const [inline]
Definition at line 69 of file Color.h.
The documentation for this class was generated from the following file:
/Users/gaspard/git/lubyk/modules/mimas/include/mimas/Color.h