lubyk: lubyk::RMutex Class Reference
lubyk::RMutex Class Reference
#include <rmutex.h>
Inherits lubyk::NonCopyable.
Inherited by lk::Mutex.
Public Member Functions
RMutex ()
~RMutex ()
void lock ()
void unlock ()
Protected Member Functions
int lockCount () const
Private Attributes
Mutex mutex_
int counter_
pthread_t owner_
Detailed Description
Recursive Mutex: experimental DO NOT USE !
Definition at line 44 of file rmutex.h.
Constructor & Destructor Documentation
lubyk::RMutex::RMutex () [inline]
Definition at line 50 of file rmutex.h.
lubyk::RMutex::~RMutex () [inline]
Definition at line 54 of file rmutex.h.
Member Function Documentation
void lubyk::RMutex::lock () [inline]
If the mutex is locked by another thread, waits until it is unlocked, lock and continue. If the mutex is not locked. Lock and continue. If this thread locked it: bang!
Reimplemented in lk::Mutex.
Definition at line 59 of file rmutex.h.
References counter_, lubyk::Mutex::lock(), mutex_, and owner_.
Referenced by lubyk::ScopedLock::ScopedLock(), and lubyk::ScopedUnlock::~ScopedUnlock().
int lubyk::RMutex::lockCount () const [inline, protected]
Used for debugging and testing.
Definition at line 80 of file rmutex.h.
References counter_.
void lubyk::RMutex::unlock () [inline]
Release the lock so others can work on the data.
Reimplemented in lk::Mutex.
Definition at line 71 of file rmutex.h.
References counter_, mutex_, owner_, and lubyk::Mutex::unlock().
Referenced by lubyk::ScopedUnlock::ScopedUnlock(), and lubyk::ScopedLock::~ScopedLock().
Member Data Documentation
int lubyk::RMutex::counter_ [private]
Definition at line 47 of file rmutex.h.
Referenced by lock(), lockCount(), and unlock().
Mutex lubyk::RMutex::mutex_ [private]
Definition at line 46 of file rmutex.h.
Referenced by lock(), and unlock().
pthread_t lubyk::RMutex::owner_ [private]
Definition at line 48 of file rmutex.h.
Referenced by lock(), and unlock().
The documentation for this class was generated from the following file:
/Users/gaspard/git/lubyk/modules/lubyk/include/lubyk/rmutex.h