lubyk: /Users/gaspard/git/lubyk/modules/cv/include/cv/cvcompat.h File Reference
/Users/gaspard/git/lubyk/modules/cv/include/cv/cvcompat.h File Reference
#include <string.h>
Classes
struct CvRandState
struct _CvPixelPosition8u
struct _CvPixelPosition8s
struct _CvPixelPosition32f
Defines
#define CV_UNREFERENCED(arg) arg
#define CvMatType int
#define CvDisMaskType int
#define CvMatArray CvMat
#define CvThreshType int
#define CvAdaptiveThreshMethod int
#define CvCompareMethod int
#define CvFontFace int
#define CvPolyApproxMethod int
#define CvContoursMatchMethod int
#define CvContourTreesMatchMethod int
#define CvCoeffType int
#define CvRodriguesType int
#define CvElementShape int
#define CvMorphOp int
#define CvTemplMatchMethod int
#define CvPoint2D64d CvPoint2D64f
#define CvPoint3D64d CvPoint3D64f
#define CV_MAT32F CV_32FC1
#define CV_MAT3x1_32F CV_32FC1
#define CV_MAT4x1_32F CV_32FC1
#define CV_MAT3x3_32F CV_32FC1
#define CV_MAT4x4_32F CV_32FC1
#define CV_MAT64D CV_64FC1
#define CV_MAT3x1_64D CV_64FC1
#define CV_MAT4x1_64D CV_64FC1
#define CV_MAT3x3_64D CV_64FC1
#define CV_MAT4x4_64D CV_64FC1
#define IPL_GAUSSIAN_5x5 7
#define CvBox2D32f CvBox2D
#define cvCreateImageData cvCreateData
#define cvReleaseImageData cvReleaseData
#define cvSetImageData cvSetData
#define cvGetImageRawData cvGetRawData
#define cvmAlloc cvCreateData
#define cvmFree cvReleaseData
#define cvmAllocArray cvCreateData
#define cvmFreeArray cvReleaseData
#define cvIntegralImage cvIntegral
#define cvMatchContours cvMatchShapes
#define cvUpdateMHIByTime cvUpdateMotionHistory
#define cvAccMask cvAcc
#define cvSquareAccMask cvSquareAcc
#define cvMultiplyAccMask cvMultiplyAcc
#define cvRunningAvgMask(imgY, imgU, mask, alpha) cvRunningAvg(imgY, imgU, alpha, mask)
#define cvSetHistThresh cvSetHistBinRanges
#define cvCalcHistMask(img, mask, hist, doNotClear) cvCalcHist(img, hist, doNotClear, mask)
#define cvCvtPixToPlane cvSplit
#define cvCvtPlaneToPix cvMerge
#define cvRandNext(_state) cvRandInt(&(_state)->state)
#define cvPseudoInv cvPseudoInverse
#define cvContourMoments(contour, moments) cvMoments(contour, moments, 0)
#define cvGetPtrAt cvPtr2D
#define cvGetAt cvGet2D
#define cvSetAt(arr, val, y, x) cvSet2D((arr),(y),(x),(val))
#define cvMeanMask cvMean
#define cvMean_StdDevMask(img, mask, mean, sdv) cvMean_StdDev(img,mean,sdv,mask)
#define cvNormMask(imgA, imgB, mask, normType) cvNorm(imgA,imgB,normType,mask)
#define cvMinMaxLocMask(img, mask, min_val, max_val, min_loc, max_loc) cvMinMaxLoc(img, min_val, max_val, min_loc, max_loc, mask)
#define cvRemoveMemoryManager cvSetMemoryManager
#define cvmSetZero(mat) cvSetZero(mat)
#define cvmSetIdentity(mat) cvSetIdentity(mat)
#define cvmAdd(src1, src2, dst) cvAdd(src1, src2, dst, 0)
#define cvmSub(src1, src2, dst) cvSub(src1, src2, dst, 0)
#define cvmCopy(src, dst) cvCopy(src, dst, 0)
#define cvmMul(src1, src2, dst) cvMatMulAdd(src1, src2, 0, dst)
#define cvmTranspose(src, dst) cvT(src, dst)
#define cvmInvert(src, dst) cvInv(src, dst)
#define cvmMahalanobis(vec1, vec2, mat) cvMahalanobis(vec1, vec2, mat)
#define cvmDotProduct(vec1, vec2) cvDotProduct(vec1, vec2)
#define cvmCrossProduct(vec1, vec2, dst) cvCrossProduct(vec1, vec2, dst)
#define cvmTrace(mat) (cvTrace(mat)).val[0]
#define cvmMulTransposed(src, dst, order) cvMulTransposed(src, dst, order)
#define cvmEigenVV(mat, evec, eval, eps) cvEigenVV(mat, evec, eval, eps)
#define cvmDet(mat) cvDet(mat)
#define cvmScale(src, dst, scale) cvScale(src, dst, scale)
#define cvCopyImage(src, dst) cvCopy(src, dst, 0)
#define cvReleaseMatHeader cvReleaseMat
#define cvContourConvexHull(contour, orientation, storage) cvConvexHull2(contour, storage, orientation)
#define cvConvexHullApprox(points, num_points, bound_rect, bandwidth,orientation, hull, hullsize) cvConvexHull(points, num_points, bound_rect, orientation, hull, hullsize)
#define cvContourConvexHullApprox(contour, bandwidth, orientation, storage) cvConvexHull2(contour, storage, orientation)
#define cvQueryHistValue_1D(hist, idx0) ((float)cvGetReal1D((hist)->bins, (idx0)))
#define cvQueryHistValue_2D(hist, idx0, idx1) ((float)cvGetReal2D((hist)->bins, (idx0), (idx1)))
#define cvQueryHistValue_3D(hist, idx0, idx1, idx2) ((float)cvGetReal3D((hist)->bins, (idx0), (idx1), (idx2)))
#define cvQueryHistValue_nD(hist, idx) ((float)cvGetRealND((hist)->bins, (idx)))
#define cvGetHistValue_1D(hist, idx0) ((float*)cvPtr1D((hist)->bins, (idx0), 0))
#define cvGetHistValue_2D(hist, idx0, idx1) ((float*)cvPtr2D((hist)->bins, (idx0), (idx1), 0))
#define cvGetHistValue_3D(hist, idx0, idx1, idx2) ((float*)cvPtr3D((hist)->bins, (idx0), (idx1), (idx2), 0))
#define cvGetHistValue_nD(hist, idx) ((float*)cvPtrND((hist)->bins, (idx), 0))
#define CV_IS_SET_ELEM_EXISTS CV_IS_SET_ELEM
#define CV_RODRIGUES_M2V 0
#define CV_RODRIGUES_V2M 1
#define cvKalmanUpdateByTime cvKalmanPredict
#define cvKalmanUpdateByMeasurement cvKalmanCorrect
#define cvMake2DPoints cvConvertPointsHomogeneous
#define cvMake3DPoints cvConvertPointsHomogeneous
#define cvWarpPerspectiveQMatrix cvGetPerspectiveTransform
#define cvConvertPointsHomogenious cvConvertPointsHomogeneous
#define CV_INIT_PIXEL_POS(pos, origin, _step, roi, _x, _y, orientation)
#define CV_MOVE_TO(pos, _x, _y, cs)
#define CV_GET_CURRENT(pos, cs) ((pos).currline + (pos).x * (cs))
#define CV_MOVE_LEFT(pos, cs) (--(pos).x >= 0 ? (pos).currline + (pos).x*(cs) : 0)
#define CV_MOVE_RIGHT(pos, cs) (++(pos).x < (pos).width ? (pos).currline + (pos).x*(cs) : 0)
#define CV_MOVE_UP(pos, cs) (((pos).currline -= (pos).step) != (pos).topline ? (pos).currline + (pos).x*(cs) : 0)
#define CV_MOVE_DOWN(pos, cs) (((pos).currline += (pos).step) != (pos).bottomline ? (pos).currline + (pos).x*(cs) : 0)
#define CV_MOVE_LU(pos, cs) (CV_MOVE_LEFT(pos, cs), CV_MOVE_UP(pos, cs))
#define CV_MOVE_RU(pos, cs) (CV_MOVE_RIGHT(pos, cs), CV_MOVE_UP(pos, cs))
#define CV_MOVE_LD(pos, cs) (CV_MOVE_LEFT(pos, cs), CV_MOVE_DOWN(pos, cs))
#define CV_MOVE_RD(pos, cs) (CV_MOVE_RIGHT(pos, cs), CV_MOVE_DOWN(pos, cs))
#define CV_MOVE_LEFT_WRAP(pos, cs) ((pos).currline + (--(pos).x >= 0 ? (pos).x : ((pos).x = (pos).width-1))*(cs))
#define CV_MOVE_RIGHT_WRAP(pos, cs) ((pos).currline + (++(pos).x < (pos).width ? (pos).x : ((pos).x = 0))*(cs))
#define CV_MOVE_UP_WRAP(pos, cs)
#define CV_MOVE_DOWN_WRAP(pos, cs)
#define CV_MOVE_LU_WRAP(pos, cs) (CV_MOVE_LEFT_WRAP(pos, cs), CV_MOVE_UP_WRAP(pos, cs))
#define CV_MOVE_RU_WRAP(pos, cs) (CV_MOVE_RIGHT_WRAP(pos, cs), CV_MOVE_UP_WRAP(pos, cs))
#define CV_MOVE_LD_WRAP(pos, cs) (CV_MOVE_LEFT_WRAP(pos, cs), CV_MOVE_DOWN_WRAP(pos, cs))
#define CV_MOVE_RD_WRAP(pos, cs) (CV_MOVE_RIGHT_WRAP(pos, cs), CV_MOVE_DOWN_WRAP(pos, cs))
#define CV_SHIFT_NONE 2
#define CV_SHIFT_LEFT 1
#define CV_SHIFT_RIGHT 3
#define CV_SHIFT_UP 6
#define CV_SHIFT_DOWN 10
#define CV_SHIFT_LU 5
#define CV_SHIFT_RU 7
#define CV_SHIFT_LD 9
#define CV_SHIFT_RD 11
#define CV_MOVE_PARAM(pos, shift, cs)
#define CV_MOVE_PARAM_WRAP(pos, shift, cs)
Typedefs
typedef struct CvRandState CvRandState
typedef int CvDisType
typedef int CvChainApproxMethod
typedef int CvContourRetrievalMode
typedef struct _CvPixelPosition8u CvPixelPosition8u
typedef struct _CvPixelPosition8s CvPixelPosition8s
typedef struct _CvPixelPosition32f CvPixelPosition32f
Functions
CV_INLINE CvMat cvMatArray (int rows, int cols, int type, int count, void *data CV_DEFAULT(0))
CV_INLINE double cvMean (const CvArr *image, const CvArr *mask CV_DEFAULT(0))
CV_INLINE double cvSumPixels (const CvArr *image)
CV_INLINE void cvMean_StdDev (const CvArr *image, double *mean, double *sdv, const CvArr *mask CV_DEFAULT(0))
CV_INLINE void cvmPerspectiveProject (const CvMat *mat, const CvArr *src, CvArr *dst)
CV_INLINE void cvFillImage (CvArr *mat, double color)
CV_INLINE void cvRandSetRange (CvRandState *state, double param1, double param2, int index CV_DEFAULT(-1))
CV_INLINE void cvRandInit (CvRandState *state, double param1, double param2, int seed, int disttype CV_DEFAULT(CV_RAND_UNI))
CV_INLINE void cvRand (CvRandState *state, CvArr *arr)
CV_INLINE void cvbRand (CvRandState *state, float *dst, int len)
CV_INLINE void cvbCartToPolar (const float *y, const float *x, float *magnitude, float *angle, int len)
CV_INLINE void cvbFastArctan (const float *y, const float *x, float *angle, int len)
CV_INLINE void cvbSqrt (const float *x, float *y, int len)
CV_INLINE void cvbInvSqrt (const float *x, float *y, int len)
CV_INLINE void cvbReciprocal (const float *x, float *y, int len)
CV_INLINE void cvbFastExp (const float *x, double *y, int len)
CV_INLINE void cvbFastLog (const double *x, float *y, int len)
CV_INLINE CvRect cvContourBoundingRect (void *point_set, int update CV_DEFAULT(0))
CV_INLINE double cvPseudoInverse (const CvArr *src, CvArr *dst)
CV_INLINE void cvConvexHull (CvPoint *points, int num_points, CvRect *CV_UNREFERENCED(bound_rect), int orientation, int *hull, int *hullsize)
CV_INLINE void cvMinAreaRect (CvPoint *points, int n, int CV_UNREFERENCED(left), int CV_UNREFERENCED(bottom), int CV_UNREFERENCED(right), int CV_UNREFERENCED(top), CvPoint2D32f *anchor, CvPoint2D32f *vect1, CvPoint2D32f *vect2)
CV_INLINE void cvFitLine3D (CvPoint3D32f *points, int count, int dist, void *param, float reps, float aeps, float *line)
CV_INLINE void cvFitLine2D (CvPoint2D32f *points, int count, int dist, void *param, float reps, float aeps, float *line)
CV_INLINE void cvFitEllipse (const CvPoint2D32f *points, int count, CvBox2D *box)
CV_INLINE void cvProject3D (CvPoint3D32f *points3D, int count, CvPoint2D32f *points2D, int xIndx CV_DEFAULT(0), int yIndx CV_DEFAULT(1))
CV_INLINE int cvHoughLines (CvArr *image, double rho, double theta, int threshold, float *lines, int linesNumber)
CV_INLINE int cvHoughLinesP (CvArr *image, double rho, double theta, int threshold, int lineLength, int lineGap, int *lines, int linesNumber)
CV_INLINE int cvHoughLinesSDiv (CvArr *image, double rho, int srn, double theta, int stn, int threshold, float *lines, int linesNumber)
CV_INLINE void cvFindFundamentalMatrix (int *points1, int *points2, int numpoints, int CV_UNREFERENCED(method), float *matrix)
CV_INLINE int cvFindChessBoardCornerGuesses (const void *arr, void *CV_UNREFERENCED(thresharr), CvMemStorage *CV_UNREFERENCED(storage), CvSize pattern_size, CvPoint2D32f *corners, int *corner_count)
CV_INLINE void cvCalibrateCamera (int image_count, int *_point_counts, CvSize image_size, CvPoint2D32f *_image_points, CvPoint3D32f *_object_points, float *_distortion_coeffs, float *_camera_matrix, float *_translation_vectors, float *_rotation_matrices, int flags)
CV_INLINE void cvCalibrateCamera_64d (int image_count, int *_point_counts, CvSize image_size, CvPoint2D64f *_image_points, CvPoint3D64f *_object_points, double *_distortion_coeffs, double *_camera_matrix, double *_translation_vectors, double *_rotation_matrices, int flags)
CV_INLINE void cvFindExtrinsicCameraParams (int point_count, CvSize CV_UNREFERENCED(image_size), CvPoint2D32f *_image_points, CvPoint3D32f *_object_points, float *focal_length, CvPoint2D32f principal_point, float *_distortion_coeffs, float *_rotation_vector, float *_translation_vector)
CV_INLINE void cvFindExtrinsicCameraParams_64d (int point_count, CvSize CV_UNREFERENCED(image_size), CvPoint2D64f *_image_points, CvPoint3D64f *_object_points, double *focal_length, CvPoint2D64f principal_point, double *_distortion_coeffs, double *_rotation_vector, double *_translation_vector)
CV_INLINE void cvRodrigues (CvMat *rotation_matrix, CvMat *rotation_vector, CvMat *jacobian, int conv_type)
CV_INLINE void cvProjectPoints (int point_count, CvPoint3D64f *_object_points, double *_rotation_vector, double *_translation_vector, double *focal_length, CvPoint2D64f principal_point, double *_distortion, CvPoint2D64f *_image_points, double *_deriv_points_rotation_matrix, double *_deriv_points_translation_vect, double *_deriv_points_focal, double *_deriv_points_principal_point, double *_deriv_points_distortion_coeffs)
CV_INLINE void cvProjectPointsSimple (int point_count, CvPoint3D64f *_object_points, double *_rotation_matrix, double *_translation_vector, double *_camera_matrix, double *_distortion, CvPoint2D64f *_image_points)
CV_INLINE void cvUnDistortOnce (const CvArr *src, CvArr *dst, const float *intrinsic_matrix, const float *distortion_coeffs, int CV_UNREFERENCED(interpolate))
CV_INLINE void cvUnDistortInit (const CvArr *CV_UNREFERENCED(src), CvArr *undistortion_map, const float *A, const float *k, int CV_UNREFERENCED(interpolate))
CV_INLINE void cvUnDistort (const CvArr *src, CvArr *dst, const CvArr *undistortion_map, int CV_UNREFERENCED(interpolate))
CV_INLINE float cvCalcEMD (const float *signature1, int size1, const float *signature2, int size2, int dims, int dist_type CV_DEFAULT(CV_DIST_L2), CvDistanceFunction dist_func CV_DEFAULT(0), float *lower_bound CV_DEFAULT(0), void *user_param CV_DEFAULT(0))
CV_INLINE void cvKMeans (int num_clusters, float **samples, int num_samples, int vec_size, CvTermCriteria termcrit, int *cluster_idx)
CV_INLINE void cvStartScanGraph (CvGraph *graph, CvGraphScanner *scanner, CvGraphVtx *vtx CV_DEFAULT(NULL), int mask CV_DEFAULT(CV_GRAPH_ALL_ITEMS))
CV_INLINE void cvEndScanGraph (CvGraphScanner *scanner)
CV_INLINE void cvLineAA (CvArr *img, CvPoint pt1, CvPoint pt2, double color, int scale CV_DEFAULT(0))
CV_INLINE void cvCircleAA (CvArr *img, CvPoint center, int radius, double color, int scale CV_DEFAULT(0))
CV_INLINE void cvEllipseAA (CvArr *img, CvPoint center, CvSize axes, double angle, double start_angle, double end_angle, double color, int scale CV_DEFAULT(0))
CV_INLINE void cvPolyLineAA (CvArr *img, CvPoint **pts, int *npts, int contours, int is_closed, double color, int scale CV_DEFAULT(0))
Define Documentation
#define CV_GET_CURRENT (pos, cs) ((pos).currline + (pos).x * (cs))
Definition at line 975 of file cvcompat.h.
#define CV_INIT_PIXEL_POS (pos, origin, _step, roi, _x, _y, orientation)
Value:
(\
    (pos).step = (_step)/sizeof((pos).currline[0]) * (orientation ? -1 : 1), \
    (pos).width = (roi).width,                                               \
    (pos).height = (roi).height,                                             \
    (pos).bottomline = (origin) + (pos).step*(pos).height,                   \
    (pos).topline = (origin) - (pos).step,                                   \
    (pos).step_arr[0] = 0,                                                   \
    (pos).step_arr[1] = -(pos).step,                                         \
    (pos).step_arr[2] = (pos).step,                                          \
    (pos).x = (_x),                                                          \
    (pos).currline = (origin) + (pos).step*(_y) )
Definition at line 949 of file cvcompat.h.
#define CV_IS_SET_ELEM_EXISTS CV_IS_SET_ELEM
Definition at line 500 of file cvcompat.h.
#define CV_MAT32F CV_32FC1
Definition at line 81 of file cvcompat.h.
#define CV_MAT3x1_32F CV_32FC1
Definition at line 82 of file cvcompat.h.
#define CV_MAT3x1_64D CV_64FC1
Definition at line 88 of file cvcompat.h.
#define CV_MAT3x3_32F CV_32FC1
Definition at line 84 of file cvcompat.h.
#define CV_MAT3x3_64D CV_64FC1
Definition at line 90 of file cvcompat.h.
#define CV_MAT4x1_32F CV_32FC1
Definition at line 83 of file cvcompat.h.
#define CV_MAT4x1_64D CV_64FC1
Definition at line 89 of file cvcompat.h.
#define CV_MAT4x4_32F CV_32FC1
Definition at line 85 of file cvcompat.h.
#define CV_MAT4x4_64D CV_64FC1
Definition at line 91 of file cvcompat.h.
#define CV_MAT64D CV_64FC1
Definition at line 87 of file cvcompat.h.
#define CV_MOVE_DOWN (pos, cs) (((pos).currline += (pos).step) != (pos).bottomline ? (pos).currline + (pos).x*(cs) : 0)
Definition at line 994 of file cvcompat.h.
#define CV_MOVE_DOWN_WRAP (pos, cs)
Value:
((((pos).currline += (pos).step) != (pos).bottomline ? \
    (pos).currline : ((pos).currline = (pos).topline + (pos).step)) + (pos).x*(cs) )
Definition at line 1030 of file cvcompat.h.
#define CV_MOVE_LD (pos, cs) (CV_MOVE_LEFT(pos, cs), CV_MOVE_DOWN(pos, cs))
Definition at line 1004 of file cvcompat.h.
#define CV_MOVE_LD_WRAP (pos, cs) (CV_MOVE_LEFT_WRAP(pos, cs), CV_MOVE_DOWN_WRAP(pos, cs))
Definition at line 1039 of file cvcompat.h.
#define CV_MOVE_LEFT (pos, cs) (--(pos).x >= 0 ? (pos).currline + (pos).x*(cs) : 0)
Definition at line 982 of file cvcompat.h.
#define CV_MOVE_LEFT_WRAP (pos, cs) ((pos).currline + (--(pos).x >= 0 ? (pos).x : ((pos).x = (pos).width-1))*(cs))
Definition at line 1017 of file cvcompat.h.
#define CV_MOVE_LU (pos, cs) (CV_MOVE_LEFT(pos, cs), CV_MOVE_UP(pos, cs))
Definition at line 998 of file cvcompat.h.
#define CV_MOVE_LU_WRAP (pos, cs) (CV_MOVE_LEFT_WRAP(pos, cs), CV_MOVE_UP_WRAP(pos, cs))
Definition at line 1035 of file cvcompat.h.
#define CV_MOVE_PARAM (pos, shift, cs)
Value:
((pos).currline += (pos).step_arr[(shift)>>2], (pos).x += ((shift)&3)-2,       \
    ((pos).currline != (pos).topline && (pos).currline != (pos).bottomline &&       \
    (pos).x >= 0 && (pos).x < (pos).width) ? (pos).currline + (pos).x*(cs) : 0 )
Definition at line 1058 of file cvcompat.h.
#define CV_MOVE_PARAM_WRAP (pos, shift, cs)
Value:
((pos).currline += (pos).step_arr[(shift)>>2],                                 \
    (pos).currline = ((pos).currline == (pos).topline ?                             \
    (pos).bottomline - (pos).step :                                                 \
    (pos).currline == (pos).bottomline ?                                            \
    (pos).topline + (pos).step : (pos).currline),                                   \
                                                                                    \
    (pos).x += ((shift)&3)-2,                                                       \
    (pos).x = ((pos).x < 0 ? (pos).width-1 : (pos).x >= (pos).width ? 0 : (pos).x), \
                                                                                    \
    (pos).currline + (pos).x*(cs) )
Definition at line 1068 of file cvcompat.h.
#define CV_MOVE_RD (pos, cs) (CV_MOVE_RIGHT(pos, cs), CV_MOVE_DOWN(pos, cs))
Definition at line 1007 of file cvcompat.h.
#define CV_MOVE_RD_WRAP (pos, cs) (CV_MOVE_RIGHT_WRAP(pos, cs), CV_MOVE_DOWN_WRAP(pos, cs))
Definition at line 1041 of file cvcompat.h.
#define CV_MOVE_RIGHT (pos, cs) (++(pos).x < (pos).width ? (pos).currline + (pos).x*(cs) : 0)
Definition at line 986 of file cvcompat.h.
#define CV_MOVE_RIGHT_WRAP (pos, cs) ((pos).currline + (++(pos).x < (pos).width ? (pos).x : ((pos).x = 0))*(cs))
Definition at line 1021 of file cvcompat.h.
#define CV_MOVE_RU (pos, cs) (CV_MOVE_RIGHT(pos, cs), CV_MOVE_UP(pos, cs))
Definition at line 1001 of file cvcompat.h.
#define CV_MOVE_RU_WRAP (pos, cs) (CV_MOVE_RIGHT_WRAP(pos, cs), CV_MOVE_UP_WRAP(pos, cs))
Definition at line 1037 of file cvcompat.h.
#define CV_MOVE_TO (pos, _x, _y, cs)
Value:
((pos).currline = (_y) >= 0 && (_y) < (pos).height ? (pos).topline + ((_y)+1)*(pos).step : 0, \
 (pos).x = (_x) >= 0 && (_x) < (pos).width ? (_x) : 0, (pos).currline + (_x) * (cs) )
Definition at line 967 of file cvcompat.h.
#define CV_MOVE_UP (pos, cs) (((pos).currline -= (pos).step) != (pos).topline ? (pos).currline + (pos).x*(cs) : 0)
Definition at line 990 of file cvcompat.h.
#define CV_MOVE_UP_WRAP (pos, cs)
Value:
((((pos).currline -= (pos).step) != (pos).topline ? \
    (pos).currline : ((pos).currline = (pos).bottomline - (pos).step)) + (pos).x*(cs) )
Definition at line 1025 of file cvcompat.h.
#define CV_RODRIGUES_M2V 0
Definition at line 687 of file cvcompat.h.
#define CV_RODRIGUES_V2M 1
Definition at line 688 of file cvcompat.h.
Referenced by cvRodrigues().
#define CV_SHIFT_DOWN 10
Definition at line 1048 of file cvcompat.h.
#define CV_SHIFT_LD 9
Definition at line 1051 of file cvcompat.h.
#define CV_SHIFT_LEFT 1
Definition at line 1045 of file cvcompat.h.
#define CV_SHIFT_LU 5
Definition at line 1049 of file cvcompat.h.
#define CV_SHIFT_NONE 2
Definition at line 1044 of file cvcompat.h.
#define CV_SHIFT_RD 11
Definition at line 1052 of file cvcompat.h.
#define CV_SHIFT_RIGHT 3
Definition at line 1046 of file cvcompat.h.
#define CV_SHIFT_RU 7
Definition at line 1050 of file cvcompat.h.
#define CV_SHIFT_UP 6
Definition at line 1047 of file cvcompat.h.
#define CV_UNREFERENCED (arg) arg
Definition at line 58 of file cvcompat.h.
Referenced by cvMinAreaRect().
#define cvAccMask cvAcc
Definition at line 118 of file cvcompat.h.
#define CvAdaptiveThreshMethod int
Definition at line 66 of file cvcompat.h.
#define CvBox2D32f CvBox2D
Definition at line 94 of file cvcompat.h.
#define cvCalcHistMask (img, mask, hist, doNotClear) cvCalcHist(img, hist, doNotClear, mask)
Definition at line 124 of file cvcompat.h.
#define CvCoeffType int
Definition at line 72 of file cvcompat.h.
#define CvCompareMethod int
Definition at line 67 of file cvcompat.h.
#define cvContourConvexHull (contour, orientation, storage) cvConvexHull2(contour, storage, orientation)
Definition at line 394 of file cvcompat.h.
#define cvContourConvexHullApprox (contour, bandwidth, orientation, storage) cvConvexHull2(contour, storage, orientation)
Definition at line 403 of file cvcompat.h.
#define cvContourMoments (contour, moments) cvMoments(contour, moments, 0)
Definition at line 344 of file cvcompat.h.
#define CvContoursMatchMethod int
Definition at line 70 of file cvcompat.h.
#define CvContourTreesMatchMethod int
Definition at line 71 of file cvcompat.h.
#define cvConvertPointsHomogenious cvConvertPointsHomogeneous
Definition at line 895 of file cvcompat.h.
#define cvConvexHullApprox (points, num_points, bound_rect, bandwidth, orientation, hull, hullsize) cvConvexHull(points, num_points, bound_rect, orientation, hull, hullsize)
Definition at line 398 of file cvcompat.h.
#define cvCopyImage (src, dst) cvCopy(src, dst, 0)
Definition at line 378 of file cvcompat.h.
#define cvCreateImageData cvCreateData
Definition at line 97 of file cvcompat.h.
#define cvCvtPixToPlane cvSplit
Definition at line 170 of file cvcompat.h.
#define cvCvtPlaneToPix cvMerge
Definition at line 171 of file cvcompat.h.
#define CvDisMaskType int
Definition at line 62 of file cvcompat.h.
#define CvElementShape int
Definition at line 74 of file cvcompat.h.
#define CvFontFace int
Definition at line 68 of file cvcompat.h.
#define cvGetAt cvGet2D
Definition at line 348 of file cvcompat.h.
#define cvGetHistValue_1D (hist, idx0) ((float*)cvPtr1D((hist)->bins, (idx0), 0))
Definition at line 490 of file cvcompat.h.
#define cvGetHistValue_2D (hist, idx0, idx1) ((float*)cvPtr2D((hist)->bins, (idx0), (idx1), 0))
Definition at line 492 of file cvcompat.h.
#define cvGetHistValue_3D (hist, idx0, idx1, idx2) ((float*)cvPtr3D((hist)->bins, (idx0), (idx1), (idx2), 0))
Definition at line 494 of file cvcompat.h.
#define cvGetHistValue_nD (hist, idx) ((float*)cvPtrND((hist)->bins, (idx), 0))
Definition at line 496 of file cvcompat.h.
#define cvGetImageRawData cvGetRawData
Definition at line 100 of file cvcompat.h.
#define cvGetPtrAt cvPtr2D
Definition at line 347 of file cvcompat.h.
#define cvIntegralImage cvIntegral
Definition at line 107 of file cvcompat.h.
#define cvKalmanUpdateByMeasurement cvKalmanCorrect
Definition at line 857 of file cvcompat.h.
#define cvKalmanUpdateByTime cvKalmanPredict
Definition at line 856 of file cvcompat.h.
#define cvmAdd (src1, src2, dst) cvAdd(src1, src2, dst, 0)
Definition at line 363 of file cvcompat.h.
#define cvMake2DPoints cvConvertPointsHomogeneous
Definition at line 890 of file cvcompat.h.
#define cvMake3DPoints cvConvertPointsHomogeneous
Definition at line 891 of file cvcompat.h.
#define cvmAlloc cvCreateData
Definition at line 102 of file cvcompat.h.
#define cvmAllocArray cvCreateData
Definition at line 104 of file cvcompat.h.
#define CvMatArray CvMat
Definition at line 63 of file cvcompat.h.
#define cvMatchContours cvMatchShapes
Definition at line 108 of file cvcompat.h.
#define CvMatType int
Definition at line 61 of file cvcompat.h.
#define cvmCopy (src, dst) cvCopy(src, dst, 0)
Definition at line 365 of file cvcompat.h.
#define cvmCrossProduct (vec1, vec2, dst) cvCrossProduct(vec1, vec2, dst)
Definition at line 371 of file cvcompat.h.
#define cvmDet (mat) cvDet(mat)
Definition at line 375 of file cvcompat.h.
#define cvmDotProduct (vec1, vec2) cvDotProduct(vec1, vec2)
Definition at line 370 of file cvcompat.h.
#define cvMean_StdDevMask (img, mask, mean, sdv) cvMean_StdDev(img,mean,sdv,mask)
Definition at line 352 of file cvcompat.h.
#define cvMeanMask cvMean
Definition at line 351 of file cvcompat.h.
#define cvmEigenVV (mat, evec, eval, eps) cvEigenVV(mat, evec, eval, eps)
Definition at line 374 of file cvcompat.h.
#define cvmFree cvReleaseData
Definition at line 103 of file cvcompat.h.
#define cvmFreeArray cvReleaseData
Definition at line 105 of file cvcompat.h.
#define cvMinMaxLocMask (img, mask, min_val, max_val, min_loc, max_loc) cvMinMaxLoc(img, min_val, max_val, min_loc, max_loc, mask)
Definition at line 356 of file cvcompat.h.
#define cvmInvert (src, dst) cvInv(src, dst)
Definition at line 368 of file cvcompat.h.
#define cvmMahalanobis (vec1, vec2, mat) cvMahalanobis(vec1, vec2, mat)
Definition at line 369 of file cvcompat.h.
#define cvmMul (src1, src2, dst) cvMatMulAdd(src1, src2, 0, dst)
Definition at line 366 of file cvcompat.h.
#define cvmMulTransposed (src, dst, order) cvMulTransposed(src, dst, order)
Definition at line 373 of file cvcompat.h.
#define CvMorphOp int
Definition at line 75 of file cvcompat.h.
#define cvmScale (src, dst, scale) cvScale(src, dst, scale)
Definition at line 376 of file cvcompat.h.
#define cvmSetIdentity (mat) cvSetIdentity(mat)
Definition at line 362 of file cvcompat.h.
#define cvmSetZero (mat) cvSetZero(mat)
Definition at line 361 of file cvcompat.h.
#define cvmSub (src1, src2, dst) cvSub(src1, src2, dst, 0)
Definition at line 364 of file cvcompat.h.
#define cvmTrace (mat) (cvTrace(mat)).val[0]
Definition at line 372 of file cvcompat.h.
#define cvmTranspose (src, dst) cvT(src, dst)
Definition at line 367 of file cvcompat.h.
#define cvMultiplyAccMask cvMultiplyAcc
Definition at line 120 of file cvcompat.h.
#define cvNormMask (imgA, imgB, mask, normType) cvNorm(imgA,imgB,normType,mask)
Definition at line 354 of file cvcompat.h.
#define CvPoint2D64d CvPoint2D64f
Definition at line 78 of file cvcompat.h.
#define CvPoint3D64d CvPoint3D64f
Definition at line 79 of file cvcompat.h.
#define CvPolyApproxMethod int
Definition at line 69 of file cvcompat.h.
#define cvPseudoInv cvPseudoInverse
Definition at line 342 of file cvcompat.h.
#define cvQueryHistValue_1D (hist, idx0) ((float)cvGetReal1D((hist)->bins, (idx0)))
Definition at line 479 of file cvcompat.h.
#define cvQueryHistValue_2D (hist, idx0, idx1) ((float)cvGetReal2D((hist)->bins, (idx0), (idx1)))
Definition at line 481 of file cvcompat.h.
#define cvQueryHistValue_3D (hist, idx0, idx1, idx2) ((float)cvGetReal3D((hist)->bins, (idx0), (idx1), (idx2)))
Definition at line 483 of file cvcompat.h.
#define cvQueryHistValue_nD (hist, idx) ((float)cvGetRealND((hist)->bins, (idx)))
Definition at line 485 of file cvcompat.h.
#define cvRandNext (_state) cvRandInt(&(_state)->state)
Definition at line 246 of file cvcompat.h.
#define cvReleaseImageData cvReleaseData
Definition at line 98 of file cvcompat.h.
#define cvReleaseMatHeader cvReleaseMat
Definition at line 379 of file cvcompat.h.
#define cvRemoveMemoryManager cvSetMemoryManager
Definition at line 359 of file cvcompat.h.
#define CvRodriguesType int
Definition at line 73 of file cvcompat.h.
#define cvRunningAvgMask (imgY, imgU, mask, alpha) cvRunningAvg(imgY, imgU, alpha, mask)
Definition at line 121 of file cvcompat.h.
#define cvSetAt (arr, val, y, x) cvSet2D((arr),(y),(x),(val))
Definition at line 349 of file cvcompat.h.
#define cvSetHistThresh cvSetHistBinRanges
Definition at line 123 of file cvcompat.h.
#define cvSetImageData cvSetData
Definition at line 99 of file cvcompat.h.
#define cvSquareAccMask cvSquareAcc
Definition at line 119 of file cvcompat.h.
#define CvTemplMatchMethod int
Definition at line 76 of file cvcompat.h.
#define CvThreshType int
Definition at line 65 of file cvcompat.h.
#define cvUpdateMHIByTime cvUpdateMotionHistory
Definition at line 116 of file cvcompat.h.
#define cvWarpPerspectiveQMatrix cvGetPerspectiveTransform
Definition at line 893 of file cvcompat.h.
#define IPL_GAUSSIAN_5x5 7
Definition at line 93 of file cvcompat.h.
Typedef Documentation
typedef int CvChainApproxMethod
Definition at line 429 of file cvcompat.h.
typedef int CvContourRetrievalMode
Definition at line 430 of file cvcompat.h.
typedef int CvDisType
Definition at line 428 of file cvcompat.h.
typedef struct _CvPixelPosition32f CvPixelPosition32f
typedef struct _CvPixelPosition8s CvPixelPosition8s
typedef struct _CvPixelPosition8u CvPixelPosition8u
typedef struct CvRandState CvRandState
Function Documentation
CV_INLINE void cvbCartToPolar (const float * y, const float * x, float * magnitude, float * angle, int len)
Definition at line 255 of file cvcompat.h.
References CV_32F, cvMat(), CvMat::data, and CvMat::fl.
CV_INLINE void cvbFastArctan (const float * y, const float * x, float * angle, int len)
Definition at line 271 of file cvcompat.h.
References CV_32F, cvMat(), CvMat::data, and CvMat::fl.
CV_INLINE void cvbFastExp (const float * x, double * y, int len)
Definition at line 315 of file cvcompat.h.
References CV_32F, CV_64F, and cvMat().
CV_INLINE void cvbFastLog (const double * x, float * y, int len)
Definition at line 323 of file cvcompat.h.
References CV_32F, CV_64F, and cvMat().
CV_INLINE void cvbInvSqrt (const float * x, float * y, int len)
Definition at line 295 of file cvcompat.h.
References CV_32F, cvMat(), CvMat::data, and CvMat::fl.
CV_INLINE void cvbRand (CvRandState * state, float * dst, int len)
Definition at line 248 of file cvcompat.h.
References CV_32F, cvMat(), cvRand(), and mat.
CV_INLINE void cvbReciprocal (const float * x, float * y, int len)
Definition at line 305 of file cvcompat.h.
References CV_32F, cvMat(), CvMat::data, and CvMat::fl.
CV_INLINE void cvbSqrt (const float * x, float * y, int len)
Definition at line 285 of file cvcompat.h.
References CV_32F, cvMat(), CvMat::data, and CvMat::fl.
CV_INLINE float cvCalcEMD (const float * signature1, int size1, const float * signature2, int size2, int dims, int dist_type CV_DEFAULTCV_DIST_L2, CvDistanceFunction dist_func CV_DEFAULT0, float *lower_bound CV_DEFAULT0, void *user_param CV_DEFAULT0)
Definition at line 798 of file cvcompat.h.
References CV_32FC1, cvMat(), dist_type, and lower_bound.
CV_INLINE void cvCalibrateCamera (int image_count, int * _point_counts, CvSize image_size, CvPoint2D32f * _image_points, CvPoint3D32f * _object_points, float * _distortion_coeffs, float * _camera_matrix, float * _translation_vectors, float * _rotation_matrices, int flags)
Definition at line 584 of file cvcompat.h.
References camera_matrix, CV_32FC1, CV_32FC2, CV_32FC3, CV_32SC1, cvMat(), dist_coeffs, image_points, point_counts, and total.
CV_INLINE void cvCalibrateCamera_64d (int image_count, int * _point_counts, CvSize image_size, CvPoint2D64f * _image_points, CvPoint3D64f * _object_points, double * _distortion_coeffs, double * _camera_matrix, double * _translation_vectors, double * _rotation_matrices, int flags)
Definition at line 609 of file cvcompat.h.
References camera_matrix, CV_32SC1, CV_64FC1, CV_64FC2, CV_64FC3, cvMat(), dist_coeffs, image_points, point_counts, and total.
CV_INLINE void cvCircleAA (CvArr * img, CvPoint center, int radius, double color, int scale CV_DEFAULT0)
Definition at line 866 of file cvcompat.h.
References CV_AA, and scale.
CV_INLINE CvRect cvContourBoundingRect (void * point_set, int update CV_DEFAULT0)
Definition at line 331 of file cvcompat.h.
CV_INLINE void cvConvexHull (CvPoint * points, int num_points, CvRect * CV_UNREFERENCEDbound_rect, int orientation, int * hull, int * hullsize)
Definition at line 382 of file cvcompat.h.
References CvMat::cols, CV_32SC1, CV_32SC2, cvMat(), and points1.
CV_INLINE void cvEllipseAA (CvArr * img, CvPoint center, CvSize axes, double angle, double start_angle, double end_angle, double color, int scale CV_DEFAULT0)
Definition at line 872 of file cvcompat.h.
References CV_AA, and scale.
CV_INLINE void cvEndScanGraph (CvGraphScanner * scanner)
Definition at line 841 of file cvcompat.h.
References CV_StsNullPtr, and CvGraphScanner::stack.
CV_INLINE void cvFillImage (CvArr * mat, double color)
Definition at line 164 of file cvcompat.h.
CV_INLINE int cvFindChessBoardCornerGuesses (const void * arr, void * CV_UNREFERENCEDthresharr, CvMemStorage * CV_UNREFERENCEDstorage, CvSize pattern_size, CvPoint2D32f * corners, int * corner_count)
Definition at line 573 of file cvcompat.h.
References CV_CALIB_CB_ADAPTIVE_THRESH.
CV_INLINE void cvFindExtrinsicCameraParams (int point_count, CvSize CV_UNREFERENCEDimage_size, CvPoint2D32f * _image_points, CvPoint3D32f * _object_points, float * focal_length, CvPoint2D32f principal_point, float * _distortion_coeffs, float * _rotation_vector, float * _translation_vector)
Definition at line 637 of file cvcompat.h.
References a, camera_matrix, CV_32FC1, CV_32FC2, CV_32FC3, cvMat(), dist_coeffs, image_points, rotation_vector, translation_vector, CvPoint2D32f::x, and CvPoint2D32f::y.
CV_INLINE void cvFindExtrinsicCameraParams_64d (int point_count, CvSize CV_UNREFERENCEDimage_size, CvPoint2D64f * _image_points, CvPoint3D64f * _object_points, double * focal_length, CvPoint2D64f principal_point, double * _distortion_coeffs, double * _rotation_vector, double * _translation_vector)
Definition at line 662 of file cvcompat.h.
References a, camera_matrix, CV_64FC1, CV_64FC2, CV_64FC3, cvMat(), dist_coeffs, image_points, rotation_vector, translation_vector, CvPoint2D64f::x, and CvPoint2D64f::y.
CV_INLINE void cvFindFundamentalMatrix (int * points1, int * points2, int numpoints, int CV_UNREFERENCEDmethod, float * matrix)
Definition at line 541 of file cvcompat.h.
References curr, CV_32F, CV_64F, CV_FM_RANSAC, cvMat(), cvmSet(), and fundMatr.
CV_INLINE void cvFitEllipse (const CvPoint2D32f * points, int count, CvBox2D * box)
Definition at line 452 of file cvcompat.h.
References CV_32FC2, cvMat(), and mat.
CV_INLINE void cvFitLine2D (CvPoint2D32f * points, int count, int dist, void * param, float reps, float aeps, float * line)
Definition at line 442 of file cvcompat.h.
References CV_32FC2, CV_DIST_USER, cvMat(), and mat.
CV_INLINE void cvFitLine3D (CvPoint3D32f * points, int count, int dist, void * param, float reps, float aeps, float * line)
Definition at line 432 of file cvcompat.h.
References CV_32FC3, CV_DIST_USER, cvMat(), and mat.
CV_INLINE int cvHoughLines (CvArr * image, double rho, double theta, int threshold, float * lines, int linesNumber)
Definition at line 503 of file cvcompat.h.
References CvMat::cols, CV_32FC2, CV_HOUGH_STANDARD, and cvMat().
CV_INLINE int cvHoughLinesP (CvArr * image, double rho, double theta, int threshold, int lineLength, int lineGap, int * lines, int linesNumber)
Definition at line 515 of file cvcompat.h.
References CvMat::cols, CV_32SC4, CV_HOUGH_PROBABILISTIC, and cvMat().
CV_INLINE int cvHoughLinesSDiv (CvArr * image, double rho, int srn, double theta, int stn, int threshold, float * lines, int linesNumber)
Definition at line 528 of file cvcompat.h.
References CvMat::cols, CV_32FC2, CV_HOUGH_MULTI_SCALE, and cvMat().
CV_INLINE void cvKMeans (int num_clusters, float ** samples, int num_samples, int vec_size, CvTermCriteria termcrit, int * cluster_idx)
Definition at line 812 of file cvcompat.h.
References CV_32FC1, CV_32SC1, cvMat(), CvMat::data, and CvMat::fl.
CV_INLINE void cvLineAA (CvArr * img, CvPoint pt1, CvPoint pt2, double color, int scale CV_DEFAULT0)
Definition at line 860 of file cvcompat.h.
References CV_AA, and scale.
CV_INLINE CvMat cvMatArray (int rows, int cols, int type, int count, void *data CV_DEFAULT0)
Definition at line 110 of file cvcompat.h.
References cvMat(), and data.
CV_INLINE double cvMean (const CvArr * image, const CvArr *mask CV_DEFAULT0)
Definition at line 126 of file cvcompat.h.
References mask, mean, and CvScalar::val.
CV_INLINE void cvMean_StdDev (const CvArr * image, double * mean, double * sdv, const CvArr *mask CV_DEFAULT0)
Definition at line 139 of file cvcompat.h.
References mask, and CvScalar::val.
CV_INLINE void cvMinAreaRect (CvPoint * points, int n, int CV_UNREFERENCEDleft, int CV_UNREFERENCEDbottom, int CV_UNREFERENCEDright, int CV_UNREFERENCEDtop, CvPoint2D32f * anchor, CvPoint2D32f * vect1, CvPoint2D32f * vect2)
Definition at line 407 of file cvcompat.h.
References CV_32SC2, CV_UNREFERENCED, cvMat(), mat, pt, right, CvPoint2D32f::x, and CvPoint2D32f::y.
CV_INLINE void cvmPerspectiveProject (const CvMat * mat, const CvArr * src, CvArr * dst)
Definition at line 153 of file cvcompat.h.
CV_INLINE void cvPolyLineAA (CvArr * img, CvPoint ** pts, int * npts, int contours, int is_closed, double color, int scale CV_DEFAULT0)
Definition at line 881 of file cvcompat.h.
References CV_AA, and scale.
CV_INLINE void cvProject3D (CvPoint3D32f * points3D, int count, CvPoint2D32f * points2D, int xIndx CV_DEFAULT0, int yIndx CV_DEFAULT1)
Definition at line 460 of file cvcompat.h.
References CV_32F, CV_32FC2, CV_32FC3, cvMat(), dst, M, and src.
CV_INLINE void cvProjectPoints (int point_count, CvPoint3D64f * _object_points, double * _rotation_vector, double * _translation_vector, double * focal_length, CvPoint2D64f principal_point, double * _distortion, CvPoint2D64f * _image_points, double * _deriv_points_rotation_matrix, double * _deriv_points_translation_vect, double * _deriv_points_focal, double * _deriv_points_principal_point, double * _deriv_points_distortion_coeffs)
Definition at line 702 of file cvcompat.h.
References a, camera_matrix, CV_64FC1, CV_64FC2, CV_64FC3, cvMat(), dist_coeffs, image_points, rotation_vector, translation_vector, CvPoint2D64f::x, and CvPoint2D64f::y.
CV_INLINE void cvProjectPointsSimple (int point_count, CvPoint3D64f * _object_points, double * _rotation_matrix, double * _translation_vector, double * _camera_matrix, double * _distortion, CvPoint2D64f * _image_points)
Definition at line 737 of file cvcompat.h.
References camera_matrix, CV_64FC1, CV_64FC2, CV_64FC3, cvMat(), dist_coeffs, image_points, rotation_matrix, and translation_vector.
CV_INLINE double cvPseudoInverse (const CvArr * src, CvArr * dst)
Definition at line 337 of file cvcompat.h.
References CV_SVD.
CV_INLINE void cvRand (CvRandState * state, CvArr * arr)
Definition at line 236 of file cvcompat.h.
References CV_StsNullPtr, CvRandState::disttype, CvRandState::param, and CvRandState::state.
Referenced by cvbRand().
CV_INLINE void cvRandInit (CvRandState * state, double param1, double param2, int seed, int disttype CV_DEFAULTCV_RAND_UNI)
Definition at line 213 of file cvcompat.h.
References CV_RAND_NORMAL, CV_RAND_UNI, CV_StsBadFlag, CV_StsNullPtr, cvRandSetRange(), CvRandState::disttype, and CvRandState::state.
CV_INLINE void cvRandSetRange (CvRandState * state, double param1, double param2, int index CV_DEFAULT-1)
Definition at line 183 of file cvcompat.h.
References CV_StsNullPtr, CV_StsOutOfRange, index, CvRandState::param, param1, param2, and CvScalar::val.
Referenced by cvRandInit().
CV_INLINE void cvRodrigues (CvMat * rotation_matrix, CvMat * rotation_vector, CvMat * jacobian, int conv_type)
Definition at line 691 of file cvcompat.h.
References CV_RODRIGUES_V2M.
CV_INLINE void cvStartScanGraph (CvGraph * graph, CvGraphScanner * scanner, CvGraphVtx *vtx CV_DEFAULTNULL, int mask CV_DEFAULTCV_GRAPH_ALL_ITEMS)
Definition at line 826 of file cvcompat.h.
References CV_StsNullPtr, cvFree, mask, and vtx.
CV_INLINE double cvSumPixels (const CvArr * image)
Definition at line 133 of file cvcompat.h.
References scalar, and CvScalar::val.
CV_INLINE void cvUnDistort (const CvArr * src, CvArr * dst, const CvArr * undistortion_map, int CV_UNREFERENCEDinterpolate)
Definition at line 783 of file cvcompat.h.
References a, cvUnDistortOnce(), data, ptr, and CvSize::width.
CV_INLINE void cvUnDistortInit (const CvArr * CV_UNREFERENCEDsrc, CvArr * undistortion_map, const float * A, const float * k, int CV_UNREFERENCEDinterpolate)
Definition at line 767 of file cvcompat.h.
References data, ptr, and CvSize::width.
CV_INLINE void cvUnDistortOnce (const CvArr * src, CvArr * dst, const float * intrinsic_matrix, const float * distortion_coeffs, int CV_UNREFERENCEDinterpolate)
Definition at line 754 of file cvcompat.h.
References CV_32F, and cvMat().
Referenced by cvUnDistort().