lubyk: /Users/gaspard/git/lubyk/modules/cv/include/cv/cxtypes.h File Reference
/Users/gaspard/git/lubyk/modules/cv/include/cv/cxtypes.h File Reference
#include <assert.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <stdint.h>
#include <math.h>
Classes
union Cv32suf
union Cv64suf
struct _IplImage
struct _IplROI
struct _IplConvKernel
struct _IplConvKernelFP
struct CvMat
struct CvMatND
struct CvSparseMat
struct CvSparseNode
struct CvSparseMatIterator
struct CvHistogram
struct CvRect
struct CvTermCriteria
struct CvPoint
struct CvPoint2D32f
struct CvPoint3D32f
struct CvPoint2D64f
struct CvPoint3D64f
struct CvSize
struct CvSize2D32f
struct CvBox2D
struct CvLineIterator
struct CvSlice
struct CvScalar
struct CvMemBlock
struct CvMemStorage
struct CvMemStoragePos
struct CvSeqBlock
struct CvSeq
struct CvSetElem
struct CvSet
struct CvGraphEdge
struct CvGraphVtx
struct CvGraphVtx2D
struct CvGraph
struct CvChain
struct CvContour
struct CvSeqWriter
struct CvSeqReader
struct CvAttrList
struct CvString
struct CvStringHashNode
struct CvFileNode
struct CvTypeInfo
struct CvPluginFuncInfo
struct CvModuleInfo
Defines
#define CV_SSE2 0
#define CV_CDECL
#define CV_STDCALL
#define CV_EXTERN_C
#define CV_DEFAULT(val)
#define CV_EXTERN_C_FUNCPTR(x) typedef x
#define CV_INLINE static
#define CV_EXPORTS
#define CVAPI(rettype) CV_EXTERN_C CV_EXPORTS rettype CV_CDECL
#define CV_PI 3.1415926535897932384626433832795
#define CV_LOG2 0.69314718055994530941723212145818
#define CV_SWAP(a, b, t) ((t) = (a), (a) = (b), (b) = (t))
#define MIN(a, b) ((a) > (b) ? (b) : (a))
#define MAX(a, b) ((a) < (b) ? (b) : (a))
#define CV_IMIN(a, b) ((a) ^ (((a)^(b)) & (((a) < (b)) - 1)))
#define CV_IMAX(a, b) ((a) ^ (((a)^(b)) & (((a) > (b)) - 1)))
#define CV_IABS(a) (((a) ^ ((a) < 0 ? -1 : 0)) - ((a) < 0 ? -1 : 0))
#define CV_CMP(a, b) (((a) > (b)) - ((a) < (b)))
#define CV_SIGN(a) CV_CMP((a),0)
#define cvInvSqrt(value) ((float)(1./sqrt(value)))
#define cvSqrt(value) ((float)sqrt(value))
#define IPL_DEPTH_SIGN 0x80000000
#define IPL_DEPTH_1U 1
#define IPL_DEPTH_8U 8
#define IPL_DEPTH_16U 16
#define IPL_DEPTH_32F 32
#define IPL_DEPTH_8S (IPL_DEPTH_SIGN| 8)
#define IPL_DEPTH_16S (IPL_DEPTH_SIGN|16)
#define IPL_DEPTH_32S (IPL_DEPTH_SIGN|32)
#define IPL_DATA_ORDER_PIXEL 0
#define IPL_DATA_ORDER_PLANE 1
#define IPL_ORIGIN_TL 0
#define IPL_ORIGIN_BL 1
#define IPL_ALIGN_4BYTES 4
#define IPL_ALIGN_8BYTES 8
#define IPL_ALIGN_16BYTES 16
#define IPL_ALIGN_32BYTES 32
#define IPL_ALIGN_DWORD IPL_ALIGN_4BYTES
#define IPL_ALIGN_QWORD IPL_ALIGN_8BYTES
#define IPL_BORDER_CONSTANT 0
#define IPL_BORDER_REPLICATE 1
#define IPL_BORDER_REFLECT 2
#define IPL_BORDER_WRAP 3
#define IPL_IMAGE_HEADER 1
#define IPL_IMAGE_DATA 2
#define IPL_IMAGE_ROI 4
#define IPL_BORDER_REFLECT_101 4
#define IPL_IMAGE_MAGIC_VAL ((int)sizeof(IplImage))
#define CV_TYPE_NAME_IMAGE "opencv-image"
#define CV_IS_IMAGE_HDR(img) ((img) != NULL && ((const IplImage*)(img))->nSize == sizeof(IplImage))
#define CV_IS_IMAGE(img) (CV_IS_IMAGE_HDR(img) && ((IplImage*)img)->imageData != NULL)
#define IPL_DEPTH_64F 64
#define CV_IMAGE_ELEM(image, elemtype, row, col) (((elemtype*)((image)->imageData + (image)->widthStep*(row)))[(col)])
#define CV_CN_MAX 64
#define CV_CN_SHIFT 3
#define CV_DEPTH_MAX (1 << CV_CN_SHIFT)
#define CV_8U 0
#define CV_8S 1
#define CV_16U 2
#define CV_16S 3
#define CV_32S 4
#define CV_32F 5
#define CV_64F 6
#define CV_USRTYPE1 7
#define CV_MAT_DEPTH_MASK (CV_DEPTH_MAX - 1)
#define CV_MAT_DEPTH(flags) ((flags) & CV_MAT_DEPTH_MASK)
#define CV_MAKETYPE(depth, cn) (CV_MAT_DEPTH(depth) + (((cn)-1) << CV_CN_SHIFT))
#define CV_MAKE_TYPE CV_MAKETYPE
#define CV_8UC1 CV_MAKETYPE(CV_8U,1)
#define CV_8UC2 CV_MAKETYPE(CV_8U,2)
#define CV_8UC3 CV_MAKETYPE(CV_8U,3)
#define CV_8UC4 CV_MAKETYPE(CV_8U,4)
#define CV_8UC(n) CV_MAKETYPE(CV_8U,(n))
#define CV_8SC1 CV_MAKETYPE(CV_8S,1)
#define CV_8SC2 CV_MAKETYPE(CV_8S,2)
#define CV_8SC3 CV_MAKETYPE(CV_8S,3)
#define CV_8SC4 CV_MAKETYPE(CV_8S,4)
#define CV_8SC(n) CV_MAKETYPE(CV_8S,(n))
#define CV_16UC1 CV_MAKETYPE(CV_16U,1)
#define CV_16UC2 CV_MAKETYPE(CV_16U,2)
#define CV_16UC3 CV_MAKETYPE(CV_16U,3)
#define CV_16UC4 CV_MAKETYPE(CV_16U,4)
#define CV_16UC(n) CV_MAKETYPE(CV_16U,(n))
#define CV_16SC1 CV_MAKETYPE(CV_16S,1)
#define CV_16SC2 CV_MAKETYPE(CV_16S,2)
#define CV_16SC3 CV_MAKETYPE(CV_16S,3)
#define CV_16SC4 CV_MAKETYPE(CV_16S,4)
#define CV_16SC(n) CV_MAKETYPE(CV_16S,(n))
#define CV_32SC1 CV_MAKETYPE(CV_32S,1)
#define CV_32SC2 CV_MAKETYPE(CV_32S,2)
#define CV_32SC3 CV_MAKETYPE(CV_32S,3)
#define CV_32SC4 CV_MAKETYPE(CV_32S,4)
#define CV_32SC(n) CV_MAKETYPE(CV_32S,(n))
#define CV_32FC1 CV_MAKETYPE(CV_32F,1)
#define CV_32FC2 CV_MAKETYPE(CV_32F,2)
#define CV_32FC3 CV_MAKETYPE(CV_32F,3)
#define CV_32FC4 CV_MAKETYPE(CV_32F,4)
#define CV_32FC(n) CV_MAKETYPE(CV_32F,(n))
#define CV_64FC1 CV_MAKETYPE(CV_64F,1)
#define CV_64FC2 CV_MAKETYPE(CV_64F,2)
#define CV_64FC3 CV_MAKETYPE(CV_64F,3)
#define CV_64FC4 CV_MAKETYPE(CV_64F,4)
#define CV_64FC(n) CV_MAKETYPE(CV_64F,(n))
#define CV_AUTO_STEP 0x7fffffff
#define CV_WHOLE_ARR cvSlice(0, 0x3fffffff)
#define CV_MAT_CN_MASK ((CV_CN_MAX - 1) << CV_CN_SHIFT)
#define CV_MAT_CN(flags) ((((flags) & CV_MAT_CN_MASK) >> CV_CN_SHIFT) + 1)
#define CV_MAT_TYPE_MASK (CV_DEPTH_MAX*CV_CN_MAX - 1)
#define CV_MAT_TYPE(flags) ((flags) & CV_MAT_TYPE_MASK)
#define CV_MAT_CONT_FLAG_SHIFT 14
#define CV_MAT_CONT_FLAG (1 << CV_MAT_CONT_FLAG_SHIFT)
#define CV_IS_MAT_CONT(flags) ((flags) & CV_MAT_CONT_FLAG)
#define CV_IS_CONT_MAT CV_IS_MAT_CONT
#define CV_MAT_TEMP_FLAG_SHIFT 15
#define CV_MAT_TEMP_FLAG (1 << CV_MAT_TEMP_FLAG_SHIFT)
#define CV_IS_TEMP_MAT(flags) ((flags) & CV_MAT_TEMP_FLAG)
#define CV_MAGIC_MASK 0xFFFF0000
#define CV_MAT_MAGIC_VAL 0x42420000
#define CV_TYPE_NAME_MAT "opencv-matrix"
#define CV_IS_MAT_HDR(mat)
#define CV_IS_MAT(mat) (CV_IS_MAT_HDR(mat) && ((const CvMat*)(mat))->data.ptr != NULL)
#define CV_IS_MASK_ARR(mat) (((mat)->type & (CV_MAT_TYPE_MASK & ~CV_8SC1)) == 0)
#define CV_ARE_TYPES_EQ(mat1, mat2) ((((mat1)->type ^ (mat2)->type) & CV_MAT_TYPE_MASK) == 0)
#define CV_ARE_CNS_EQ(mat1, mat2) ((((mat1)->type ^ (mat2)->type) & CV_MAT_CN_MASK) == 0)
#define CV_ARE_DEPTHS_EQ(mat1, mat2) ((((mat1)->type ^ (mat2)->type) & CV_MAT_DEPTH_MASK) == 0)
#define CV_ARE_SIZES_EQ(mat1, mat2) ((mat1)->rows == (mat2)->rows && (mat1)->cols == (mat2)->cols)
#define CV_IS_MAT_CONST(mat) (((mat)->rows|(mat)->cols) == 1)
#define CV_ELEM_SIZE1(type) ((((sizeof(size_t)<<28)|0x8442211) >> CV_MAT_DEPTH(type)*4) & 15)
#define CV_ELEM_SIZE(type) (CV_MAT_CN(type) << ((((sizeof(size_t)/4+1)*16384|0x3a50) >> CV_MAT_DEPTH(type)*2) & 3))
#define IPL2CV_DEPTH(depth)
#define CV_MAT_ELEM_PTR_FAST(mat, row, col, pix_size)
#define CV_MAT_ELEM_PTR(mat, row, col) CV_MAT_ELEM_PTR_FAST(mat, row, col, CV_ELEM_SIZE((mat).type))
#define CV_MAT_ELEM(mat, elemtype, row, col) (*(elemtype*)CV_MAT_ELEM_PTR_FAST(mat, row, col, sizeof(elemtype)))
#define CV_MATND_MAGIC_VAL 0x42430000
#define CV_TYPE_NAME_MATND "opencv-nd-matrix"
#define CV_MAX_DIM 32
#define CV_MAX_DIM_HEAP (1 << 16)
#define CV_IS_MATND_HDR(mat) ((mat) != NULL && (((const CvMatND*)(mat))->type & CV_MAGIC_MASK) == CV_MATND_MAGIC_VAL)
#define CV_IS_MATND(mat) (CV_IS_MATND_HDR(mat) && ((const CvMatND*)(mat))->data.ptr != NULL)
#define CV_SPARSE_MAT_MAGIC_VAL 0x42440000
#define CV_TYPE_NAME_SPARSE_MAT "opencv-sparse-matrix"
#define CV_IS_SPARSE_MAT_HDR(mat)
#define CV_IS_SPARSE_MAT(mat) CV_IS_SPARSE_MAT_HDR(mat)
#define CV_NODE_VAL(mat, node) ((void*)((uchar*)(node) + (mat)->valoffset))
#define CV_NODE_IDX(mat, node) ((int*)((uchar*)(node) + (mat)->idxoffset))
#define CV_HIST_MAGIC_VAL 0x42450000
#define CV_HIST_UNIFORM_FLAG (1 << 10)
#define CV_HIST_RANGES_FLAG (1 << 11)
#define CV_HIST_ARRAY 0
#define CV_HIST_SPARSE 1
#define CV_HIST_TREE CV_HIST_SPARSE
#define CV_HIST_UNIFORM 1
#define CV_IS_HIST(hist)
#define CV_IS_UNIFORM_HIST(hist) (((hist)->type & CV_HIST_UNIFORM_FLAG) != 0)
#define CV_IS_SPARSE_HIST(hist) CV_IS_SPARSE_MAT((hist)->bins)
#define CV_HIST_HAS_RANGES(hist) (((hist)->type & CV_HIST_RANGES_FLAG) != 0)
#define CV_TERMCRIT_ITER 1
#define CV_TERMCRIT_NUMBER CV_TERMCRIT_ITER
#define CV_TERMCRIT_EPS 2
#define CV_WHOLE_SEQ_END_INDEX 0x3fffffff
#define CV_WHOLE_SEQ cvSlice(0, CV_WHOLE_SEQ_END_INDEX)
#define CV_STORAGE_MAGIC_VAL 0x42890000
#define CV_IS_STORAGE(storage)
#define CV_TREE_NODE_FIELDS(node_type)
#define CV_SEQUENCE_FIELDS()
#define CV_TYPE_NAME_SEQ "opencv-sequence"
#define CV_TYPE_NAME_SEQ_TREE "opencv-sequence-tree"
#define CV_SET_ELEM_FIELDS(elem_type)
#define CV_SET_FIELDS()
#define CV_SET_ELEM_IDX_MASK ((1 << 26) - 1)
#define CV_SET_ELEM_FREE_FLAG (1 << (sizeof(int)*8-1))
#define CV_IS_SET_ELEM(ptr) (((CvSetElem*)(ptr))->flags >= 0)
#define CV_GRAPH_EDGE_FIELDS()
#define CV_GRAPH_VERTEX_FIELDS()
#define CV_GRAPH_FIELDS()
#define CV_TYPE_NAME_GRAPH "opencv-graph"
#define CV_CONTOUR_FIELDS()
#define CV_SEQ_MAGIC_VAL 0x42990000
#define CV_IS_SEQ(seq) ((seq) != NULL && (((CvSeq*)(seq))->flags & CV_MAGIC_MASK) == CV_SEQ_MAGIC_VAL)
#define CV_SET_MAGIC_VAL 0x42980000
#define CV_IS_SET(set) ((set) != NULL && (((CvSeq*)(set))->flags & CV_MAGIC_MASK) == CV_SET_MAGIC_VAL)
#define CV_SEQ_ELTYPE_BITS 9
#define CV_SEQ_ELTYPE_MASK ((1 << CV_SEQ_ELTYPE_BITS) - 1)
#define CV_SEQ_ELTYPE_POINT CV_32SC2
#define CV_SEQ_ELTYPE_CODE CV_8UC1
#define CV_SEQ_ELTYPE_GENERIC 0
#define CV_SEQ_ELTYPE_PTR CV_USRTYPE1
#define CV_SEQ_ELTYPE_PPOINT CV_SEQ_ELTYPE_PTR
#define CV_SEQ_ELTYPE_INDEX CV_32SC1
#define CV_SEQ_ELTYPE_GRAPH_EDGE 0
#define CV_SEQ_ELTYPE_GRAPH_VERTEX 0
#define CV_SEQ_ELTYPE_TRIAN_ATR 0
#define CV_SEQ_ELTYPE_CONNECTED_COMP 0
#define CV_SEQ_ELTYPE_POINT3D CV_32FC3
#define CV_SEQ_KIND_BITS 3
#define CV_SEQ_KIND_MASK (((1 << CV_SEQ_KIND_BITS) - 1)<<CV_SEQ_ELTYPE_BITS)
#define CV_SEQ_KIND_GENERIC (0 << CV_SEQ_ELTYPE_BITS)
#define CV_SEQ_KIND_CURVE (1 << CV_SEQ_ELTYPE_BITS)
#define CV_SEQ_KIND_BIN_TREE (2 << CV_SEQ_ELTYPE_BITS)
#define CV_SEQ_KIND_GRAPH (3 << CV_SEQ_ELTYPE_BITS)
#define CV_SEQ_KIND_SUBDIV2D (4 << CV_SEQ_ELTYPE_BITS)
#define CV_SEQ_FLAG_SHIFT (CV_SEQ_KIND_BITS + CV_SEQ_ELTYPE_BITS)
#define CV_SEQ_FLAG_CLOSED (1 << CV_SEQ_FLAG_SHIFT)
#define CV_SEQ_FLAG_SIMPLE (2 << CV_SEQ_FLAG_SHIFT)
#define CV_SEQ_FLAG_CONVEX (4 << CV_SEQ_FLAG_SHIFT)
#define CV_SEQ_FLAG_HOLE (8 << CV_SEQ_FLAG_SHIFT)
#define CV_GRAPH_FLAG_ORIENTED (1 << CV_SEQ_FLAG_SHIFT)
#define CV_GRAPH CV_SEQ_KIND_GRAPH
#define CV_ORIENTED_GRAPH (CV_SEQ_KIND_GRAPH|CV_GRAPH_FLAG_ORIENTED)
#define CV_SEQ_POINT_SET (CV_SEQ_KIND_GENERIC| CV_SEQ_ELTYPE_POINT)
#define CV_SEQ_POINT3D_SET (CV_SEQ_KIND_GENERIC| CV_SEQ_ELTYPE_POINT3D)
#define CV_SEQ_POLYLINE (CV_SEQ_KIND_CURVE | CV_SEQ_ELTYPE_POINT)
#define CV_SEQ_POLYGON (CV_SEQ_FLAG_CLOSED | CV_SEQ_POLYLINE)
#define CV_SEQ_CONTOUR CV_SEQ_POLYGON
#define CV_SEQ_SIMPLE_POLYGON (CV_SEQ_FLAG_SIMPLE | CV_SEQ_POLYGON)
#define CV_SEQ_CHAIN (CV_SEQ_KIND_CURVE | CV_SEQ_ELTYPE_CODE)
#define CV_SEQ_CHAIN_CONTOUR (CV_SEQ_FLAG_CLOSED | CV_SEQ_CHAIN)
#define CV_SEQ_POLYGON_TREE (CV_SEQ_KIND_BIN_TREE | CV_SEQ_ELTYPE_TRIAN_ATR)
#define CV_SEQ_CONNECTED_COMP (CV_SEQ_KIND_GENERIC | CV_SEQ_ELTYPE_CONNECTED_COMP)
#define CV_SEQ_INDEX (CV_SEQ_KIND_GENERIC | CV_SEQ_ELTYPE_INDEX)
#define CV_SEQ_ELTYPE(seq) ((seq)->flags & CV_SEQ_ELTYPE_MASK)
#define CV_SEQ_KIND(seq) ((seq)->flags & CV_SEQ_KIND_MASK)
#define CV_IS_SEQ_INDEX(seq)
#define CV_IS_SEQ_CURVE(seq) (CV_SEQ_KIND(seq) == CV_SEQ_KIND_CURVE)
#define CV_IS_SEQ_CLOSED(seq) (((seq)->flags & CV_SEQ_FLAG_CLOSED) != 0)
#define CV_IS_SEQ_CONVEX(seq) (((seq)->flags & CV_SEQ_FLAG_CONVEX) != 0)
#define CV_IS_SEQ_HOLE(seq) (((seq)->flags & CV_SEQ_FLAG_HOLE) != 0)
#define CV_IS_SEQ_SIMPLE(seq)
#define CV_IS_SEQ_POINT_SET(seq) ((CV_SEQ_ELTYPE(seq) == CV_32SC2 || CV_SEQ_ELTYPE(seq) == CV_32FC2))
#define CV_IS_SEQ_POINT_SUBSET(seq) (CV_IS_SEQ_INDEX(seq) || CV_SEQ_ELTYPE(seq) == CV_SEQ_ELTYPE_PPOINT)
#define CV_IS_SEQ_POLYLINE(seq) (CV_SEQ_KIND(seq) == CV_SEQ_KIND_CURVE && CV_IS_SEQ_POINT_SET(seq))
#define CV_IS_SEQ_POLYGON(seq) (CV_IS_SEQ_POLYLINE(seq) && CV_IS_SEQ_CLOSED(seq))
#define CV_IS_SEQ_CHAIN(seq) (CV_SEQ_KIND(seq) == CV_SEQ_KIND_CURVE && (seq)->elem_size == 1)
#define CV_IS_SEQ_CONTOUR(seq) (CV_IS_SEQ_CLOSED(seq) && (CV_IS_SEQ_POLYLINE(seq) || CV_IS_SEQ_CHAIN(seq)))
#define CV_IS_SEQ_CHAIN_CONTOUR(seq) (CV_IS_SEQ_CHAIN(seq) && CV_IS_SEQ_CLOSED(seq))
#define CV_IS_SEQ_POLYGON_TREE(seq)
#define CV_IS_GRAPH(seq) (CV_IS_SET(seq) && CV_SEQ_KIND((CvSet*)(seq)) == CV_SEQ_KIND_GRAPH)
#define CV_IS_GRAPH_ORIENTED(seq) (((seq)->flags & CV_GRAPH_FLAG_ORIENTED) != 0)
#define CV_IS_SUBDIV2D(seq) (CV_IS_SET(seq) && CV_SEQ_KIND((CvSet*)(seq)) == CV_SEQ_KIND_SUBDIV2D)
#define CV_SEQ_WRITER_FIELDS()
#define CV_SEQ_READER_FIELDS()
#define CV_SEQ_ELEM(seq, elem_type, index)
#define CV_GET_SEQ_ELEM(elem_type, seq, index) CV_SEQ_ELEM((seq), elem_type, (index))
#define CV_WRITE_SEQ_ELEM_VAR(elem_ptr, writer)
#define CV_WRITE_SEQ_ELEM(elem, writer)
#define CV_NEXT_SEQ_ELEM(elem_size, reader)
#define CV_PREV_SEQ_ELEM(elem_size, reader)
#define CV_READ_SEQ_ELEM(elem, reader)
#define CV_REV_READ_SEQ_ELEM(elem, reader)
#define CV_READ_CHAIN_POINT(_pt, reader)
#define CV_CURRENT_POINT(reader) (*((CvPoint*)((reader).ptr)))
#define CV_PREV_POINT(reader) (*((CvPoint*)((reader).prev_elem)))
#define CV_READ_EDGE(pt1, pt2, reader)
#define CV_NEXT_GRAPH_EDGE(edge, vertex)
#define CV_STORAGE_READ 0
#define CV_STORAGE_WRITE 1
#define CV_STORAGE_WRITE_TEXT CV_STORAGE_WRITE
#define CV_STORAGE_WRITE_BINARY CV_STORAGE_WRITE
#define CV_STORAGE_APPEND 2
#define CV_NODE_NONE 0
#define CV_NODE_INT 1
#define CV_NODE_INTEGER CV_NODE_INT
#define CV_NODE_REAL 2
#define CV_NODE_FLOAT CV_NODE_REAL
#define CV_NODE_STR 3
#define CV_NODE_STRING CV_NODE_STR
#define CV_NODE_REF 4
#define CV_NODE_SEQ 5
#define CV_NODE_MAP 6
#define CV_NODE_TYPE_MASK 7
#define CV_NODE_TYPE(flags) ((flags) & CV_NODE_TYPE_MASK)
#define CV_NODE_FLOW 8
#define CV_NODE_USER 16
#define CV_NODE_EMPTY 32
#define CV_NODE_NAMED 64
#define CV_NODE_IS_INT(flags) (CV_NODE_TYPE(flags) == CV_NODE_INT)
#define CV_NODE_IS_REAL(flags) (CV_NODE_TYPE(flags) == CV_NODE_REAL)
#define CV_NODE_IS_STRING(flags) (CV_NODE_TYPE(flags) == CV_NODE_STRING)
#define CV_NODE_IS_SEQ(flags) (CV_NODE_TYPE(flags) == CV_NODE_SEQ)
#define CV_NODE_IS_MAP(flags) (CV_NODE_TYPE(flags) == CV_NODE_MAP)
#define CV_NODE_IS_COLLECTION(flags) (CV_NODE_TYPE(flags) >= CV_NODE_SEQ)
#define CV_NODE_IS_FLOW(flags) (((flags) & CV_NODE_FLOW) != 0)
#define CV_NODE_IS_EMPTY(flags) (((flags) & CV_NODE_EMPTY) != 0)
#define CV_NODE_IS_USER(flags) (((flags) & CV_NODE_USER) != 0)
#define CV_NODE_HAS_NAME(flags) (((flags) & CV_NODE_NAMED) != 0)
#define CV_NODE_SEQ_SIMPLE 256
#define CV_NODE_SEQ_IS_SIMPLE(seq) (((seq)->flags & CV_NODE_SEQ_SIMPLE) != 0)
Typedefs
typedef int64_t int64
typedef uint64_t uint64
typedef unsigned char uchar
typedef unsigned short ushort
typedef signed char schar
typedef void CvArr
typedef union Cv32suf Cv32suf
typedef union Cv64suf Cv64suf
typedef uint64 CvRNG
typedef struct _IplImage IplImage
typedef struct _IplTileInfo IplTileInfo
typedef struct _IplROI IplROI
typedef struct _IplConvKernel IplConvKernel
typedef struct _IplConvKernelFP IplConvKernelFP
typedef struct CvMat CvMat
typedef struct CvMatND CvMatND
typedef struct CvSparseMat CvSparseMat
typedef struct CvSparseNode CvSparseNode
typedef struct CvSparseMatIterator CvSparseMatIterator
typedef int CvHistType
typedef struct CvHistogram CvHistogram
typedef struct CvRect CvRect
typedef struct CvTermCriteria CvTermCriteria
typedef struct CvPoint CvPoint
typedef struct CvPoint2D32f CvPoint2D32f
typedef struct CvPoint3D32f CvPoint3D32f
typedef struct CvPoint2D64f CvPoint2D64f
typedef struct CvPoint3D64f CvPoint3D64f
typedef struct CvSize2D32f CvSize2D32f
typedef struct CvBox2D CvBox2D
typedef struct CvLineIterator CvLineIterator
typedef struct CvSlice CvSlice
typedef struct CvScalar CvScalar
typedef struct CvMemBlock CvMemBlock
typedef struct CvMemStorage CvMemStorage
typedef struct CvMemStoragePos CvMemStoragePos
typedef struct CvSeqBlock CvSeqBlock
typedef struct CvSeq CvSeq
typedef struct CvSetElem CvSetElem
typedef struct CvSet CvSet
typedef struct CvGraphEdge CvGraphEdge
typedef struct CvGraphVtx CvGraphVtx
typedef struct CvGraphVtx2D CvGraphVtx2D
typedef struct CvGraph CvGraph
typedef struct CvChain CvChain
typedef struct CvContour CvContour
typedef CvContour CvPoint2DSeq
typedef struct CvSeqWriter CvSeqWriter
typedef struct CvSeqReader CvSeqReader
typedef struct CvFileStorage CvFileStorage
typedef struct CvAttrList CvAttrList
typedef struct CvString CvString
typedef struct CvStringHashNode CvStringHashNode
typedef struct CvGenericHash CvFileNodeHash
typedef struct CvFileNode CvFileNode
typedef int(CV_CDECL * CvIsInstanceFunc)(const void *struct_ptr)
typedef void(CV_CDECL * CvReleaseFunc)(void **struct_dblptr)
typedef void *(CV_CDECL * CvReadFunc)(CvFileStorage *storage, CvFileNode *node)
typedef void(CV_CDECL * CvWriteFunc)(CvFileStorage *storage, const char *name, const void *struct_ptr, CvAttrList attributes)
typedef void *(CV_CDECL * CvCloneFunc)(const void *struct_ptr)
typedef struct CvTypeInfo CvTypeInfo
typedef struct CvPluginFuncInfo CvPluginFuncInfo
typedef struct CvModuleInfo CvModuleInfo
Functions
CV_INLINE int cvRound (double value)
CV_INLINE int cvFloor (double value)
CV_INLINE int cvCeil (double value)
CV_INLINE int cvIsNaN (double value)
CV_INLINE int cvIsInf (double value)
CV_INLINE CvRNG cvRNG (int64 seed CV_DEFAULT(-1))
CV_INLINE unsigned cvRandInt (CvRNG *rng)
CV_INLINE double cvRandReal (CvRNG *rng)
CV_INLINE CvMat cvMat (int rows, int cols, int type, void *data CV_DEFAULT(NULL))
CV_INLINE double cvmGet (const CvMat *mat, int row, int col)
CV_INLINE void cvmSet (CvMat *mat, int row, int col, double value)
CV_INLINE int cvIplDepth (int type)
CV_INLINE CvRect cvRect (int x, int y, int width, int height)
CV_INLINE IplROI cvRectToROI (CvRect rect, int coi)
CV_INLINE CvRect cvROIToRect (IplROI roi)
CV_INLINE CvTermCriteria cvTermCriteria (int type, int max_iter, double epsilon)
CV_INLINE CvPoint cvPoint (int x, int y)
CV_INLINE CvPoint2D32f cvPoint2D32f (double x, double y)
CV_INLINE CvPoint2D32f cvPointTo32f (CvPoint point)
CV_INLINE CvPoint cvPointFrom32f (CvPoint2D32f point)
CV_INLINE CvPoint3D32f cvPoint3D32f (double x, double y, double z)
CV_INLINE CvPoint2D64f cvPoint2D64f (double x, double y)
CV_INLINE CvPoint3D64f cvPoint3D64f (double x, double y, double z)
CV_INLINE CvSize cvSize (int width, int height)
CV_INLINE CvSize2D32f cvSize2D32f (double width, double height)
CV_INLINE CvSlice cvSlice (int start, int end)
CV_INLINE CvScalar cvScalar (double val0, double val1 CV_DEFAULT(0), double val2 CV_DEFAULT(0), double val3 CV_DEFAULT(0))
CV_INLINE CvScalar cvRealScalar (double val0)
CV_INLINE CvScalar cvScalarAll (double val0123)
CV_INLINE CvAttrList cvAttrList (const char **attr CV_DEFAULT(NULL), CvAttrList *next CV_DEFAULT(NULL))
Define Documentation
#define CV_ARE_CNS_EQ (mat1, mat2) ((((mat1)->type ^ (mat2)->type) & CV_MAT_CN_MASK) == 0)
Definition at line 630 of file cxtypes.h.
#define CV_ARE_DEPTHS_EQ (mat1, mat2) ((((mat1)->type ^ (mat2)->type) & CV_MAT_DEPTH_MASK) == 0)
Definition at line 633 of file cxtypes.h.
#define CV_ARE_SIZES_EQ (mat1, mat2) ((mat1)->rows == (mat2)->rows && (mat1)->cols == (mat2)->cols)
Definition at line 636 of file cxtypes.h.
#define CV_ARE_TYPES_EQ (mat1, mat2) ((((mat1)->type ^ (mat2)->type) & CV_MAT_TYPE_MASK) == 0)
Definition at line 627 of file cxtypes.h.
#define CV_AUTO_STEP 0x7fffffff
Definition at line 558 of file cxtypes.h.
#define CV_CDECL
Definition at line 118 of file cxtypes.h.
#define CV_CMP (a, b) (((a) > (b)) - ((a) < (b)))
Definition at line 226 of file cxtypes.h.
#define CV_CN_MAX 64
Definition at line 484 of file cxtypes.h.
#define CV_CN_SHIFT 3
Definition at line 485 of file cxtypes.h.
#define CV_CONTOUR_FIELDS ()
Value:
CV_SEQUENCE_FIELDS()     \
    CvRect rect;             \
    int color;               \
    int reserved[3];
Definition at line 1380 of file cxtypes.h.
#define CV_CURRENT_POINT (reader) (*((CvPoint*)((reader).ptr)))
Definition at line 1640 of file cxtypes.h.
#define CV_DEFAULT (val)
Definition at line 128 of file cxtypes.h.
#define CV_DEPTH_MAX (1 << CV_CN_SHIFT)
Definition at line 486 of file cxtypes.h.
#define CV_ELEM_SIZE (type) (CV_MAT_CN(type) << ((((sizeof(size_t)/4+1)*16384|0x3a50) >> CV_MAT_DEPTH(type)*2) & 3))
Definition at line 648 of file cxtypes.h.
Referenced by cvMat().
#define CV_ELEM_SIZE1 (type) ((((sizeof(size_t)<<28)|0x8442211) >> CV_MAT_DEPTH(type)*4) & 15)
Definition at line 644 of file cxtypes.h.
Referenced by cvIplDepth().
#define CV_EXPORTS
Definition at line 153 of file cxtypes.h.
#define CV_EXTERN_C
Definition at line 127 of file cxtypes.h.
#define CV_EXTERN_C_FUNCPTR (x) typedef x
Definition at line 136 of file cxtypes.h.
#define CV_GET_SEQ_ELEM (elem_type, seq, index) CV_SEQ_ELEM((seq), elem_type, (index))
Definition at line 1566 of file cxtypes.h.
#define CV_GRAPH CV_SEQ_KIND_GRAPH
Definition at line 1445 of file cxtypes.h.
#define CV_GRAPH_EDGE_FIELDS ()
Value:
int flags;                      \
    float weight;                   \
    struct CvGraphEdge* next[2];    \
    struct CvGraphVtx* vtx[2];
Definition at line 1324 of file cxtypes.h.
#define CV_GRAPH_FIELDS ()
Value:
CV_SET_FIELDS()          \
    CvSet* edges;
Definition at line 1359 of file cxtypes.h.
#define CV_GRAPH_FLAG_ORIENTED (1 << CV_SEQ_FLAG_SHIFT)
Definition at line 1443 of file cxtypes.h.
#define CV_GRAPH_VERTEX_FIELDS ()
Value:
int flags;                      \
    struct CvGraphEdge* first;
Definition at line 1331 of file cxtypes.h.
#define CV_HIST_ARRAY 0
Definition at line 840 of file cxtypes.h.
#define CV_HIST_HAS_RANGES (hist) (((hist)->type & CV_HIST_RANGES_FLAG) != 0)
Definition at line 869 of file cxtypes.h.
#define CV_HIST_MAGIC_VAL 0x42450000
Definition at line 834 of file cxtypes.h.
#define CV_HIST_RANGES_FLAG (1 << 11)
Definition at line 838 of file cxtypes.h.
#define CV_HIST_SPARSE 1
Definition at line 841 of file cxtypes.h.
#define CV_HIST_TREE CV_HIST_SPARSE
Definition at line 842 of file cxtypes.h.
#define CV_HIST_UNIFORM 1
Definition at line 846 of file cxtypes.h.
#define CV_HIST_UNIFORM_FLAG (1 << 10)
Definition at line 835 of file cxtypes.h.
#define CV_IABS (a) (((a) ^ ((a) < 0 ? -1 : 0)) - ((a) < 0 ? -1 : 0))
Definition at line 222 of file cxtypes.h.
#define CV_IMAGE_ELEM (image, elemtype, row, col) (((elemtype*)((image)->imageData + (image)->widthStep*(row)))[(col)])
Definition at line 477 of file cxtypes.h.
#define CV_IMAX (a, b) ((a) ^ (((a)^(b)) & (((a) > (b)) - 1)))
Definition at line 218 of file cxtypes.h.
#define CV_IMIN (a, b) ((a) ^ (((a)^(b)) & (((a) < (b)) - 1)))
Definition at line 216 of file cxtypes.h.
#define CV_INLINE static
Definition at line 146 of file cxtypes.h.
#define CV_IS_CONT_MAT CV_IS_MAT_CONT
Definition at line 568 of file cxtypes.h.
#define CV_IS_GRAPH (seq) (CV_IS_SET(seq) && CV_SEQ_KIND((CvSet*)(seq)) == CV_SEQ_KIND_GRAPH)
Definition at line 1509 of file cxtypes.h.
#define CV_IS_GRAPH_ORIENTED (seq) (((seq)->flags & CV_GRAPH_FLAG_ORIENTED) != 0)
Definition at line 1512 of file cxtypes.h.
#define CV_IS_HIST (hist)
Value:
((hist) != NULL  && \
     (((CvHistogram*)(hist))->type & CV_MAGIC_MASK) == CV_HIST_MAGIC_VAL && \
     (hist)->bins != NULL)
Definition at line 858 of file cxtypes.h.
#define CV_IS_IMAGE (img) (CV_IS_IMAGE_HDR(img) && ((IplImage*)img)->imageData != NULL)
Definition at line 468 of file cxtypes.h.
#define CV_IS_IMAGE_HDR (img) ((img) != NULL && ((const IplImage*)(img))->nSize == sizeof(IplImage))
Definition at line 465 of file cxtypes.h.
#define CV_IS_MASK_ARR (mat) (((mat)->type & (CV_MAT_TYPE_MASK & ~CV_8SC1)) == 0)
Definition at line 624 of file cxtypes.h.
#define CV_IS_MAT (mat) (CV_IS_MAT_HDR(mat) && ((const CvMat*)(mat))->data.ptr != NULL)
Definition at line 621 of file cxtypes.h.
Referenced by cvDecRefData(), and cvIncRefData().
#define CV_IS_MAT_CONST (mat) (((mat)->rows|(mat)->cols) == 1)
Definition at line 639 of file cxtypes.h.
#define CV_IS_MAT_CONT (flags) ((flags) & CV_MAT_CONT_FLAG)
Definition at line 567 of file cxtypes.h.
#define CV_IS_MAT_HDR (mat)
Value:
((mat) != NULL && \
    (((const CvMat*)(mat))->type & CV_MAGIC_MASK) == CV_MAT_MAGIC_VAL && \
    ((const CvMat*)(mat))->cols > 0 && ((const CvMat*)(mat))->rows > 0)
Definition at line 616 of file cxtypes.h.
#define CV_IS_MATND (mat) (CV_IS_MATND_HDR(mat) && ((const CvMatND*)(mat))->data.ptr != NULL)
Definition at line 772 of file cxtypes.h.
Referenced by cvDecRefData(), and cvIncRefData().
#define CV_IS_MATND_HDR (mat) ((mat) != NULL && (((const CvMatND*)(mat))->type & CV_MAGIC_MASK) == CV_MATND_MAGIC_VAL)
Definition at line 769 of file cxtypes.h.
#define CV_IS_SEQ (seq) ((seq) != NULL && (((CvSeq*)(seq))->flags & CV_MAGIC_MASK) == CV_SEQ_MAGIC_VAL)
Definition at line 1400 of file cxtypes.h.
#define CV_IS_SEQ_CHAIN (seq) (CV_SEQ_KIND(seq) == CV_SEQ_KIND_CURVE && (seq)->elem_size == 1)
Definition at line 1496 of file cxtypes.h.
#define CV_IS_SEQ_CHAIN_CONTOUR (seq) (CV_IS_SEQ_CHAIN(seq) && CV_IS_SEQ_CLOSED(seq))
Definition at line 1502 of file cxtypes.h.
#define CV_IS_SEQ_CLOSED (seq) (((seq)->flags & CV_SEQ_FLAG_CLOSED) != 0)
Definition at line 1477 of file cxtypes.h.
#define CV_IS_SEQ_CONTOUR (seq) (CV_IS_SEQ_CLOSED(seq) && (CV_IS_SEQ_POLYLINE(seq) || CV_IS_SEQ_CHAIN(seq)))
Definition at line 1499 of file cxtypes.h.
#define CV_IS_SEQ_CONVEX (seq) (((seq)->flags & CV_SEQ_FLAG_CONVEX) != 0)
Definition at line 1478 of file cxtypes.h.
#define CV_IS_SEQ_CURVE (seq) (CV_SEQ_KIND(seq) == CV_SEQ_KIND_CURVE)
Definition at line 1476 of file cxtypes.h.
#define CV_IS_SEQ_HOLE (seq) (((seq)->flags & CV_SEQ_FLAG_HOLE) != 0)
Definition at line 1479 of file cxtypes.h.
#define CV_IS_SEQ_INDEX (seq)
Value:
((CV_SEQ_ELTYPE(seq) == CV_SEQ_ELTYPE_INDEX) && \
                                     (CV_SEQ_KIND(seq) == CV_SEQ_KIND_GENERIC))
Definition at line 1473 of file cxtypes.h.
#define CV_IS_SEQ_POINT_SET (seq) ((CV_SEQ_ELTYPE(seq) == CV_32SC2 || CV_SEQ_ELTYPE(seq) == CV_32FC2))
Definition at line 1484 of file cxtypes.h.
#define CV_IS_SEQ_POINT_SUBSET (seq) (CV_IS_SEQ_INDEX(seq) || CV_SEQ_ELTYPE(seq) == CV_SEQ_ELTYPE_PPOINT)
Definition at line 1487 of file cxtypes.h.
#define CV_IS_SEQ_POLYGON (seq) (CV_IS_SEQ_POLYLINE(seq) && CV_IS_SEQ_CLOSED(seq))
Definition at line 1493 of file cxtypes.h.
#define CV_IS_SEQ_POLYGON_TREE (seq)
Value:
(CV_SEQ_ELTYPE (seq) ==  CV_SEQ_ELTYPE_TRIAN_ATR &&    \
    CV_SEQ_KIND( seq ) ==  CV_SEQ_KIND_BIN_TREE )
Definition at line 1505 of file cxtypes.h.
#define CV_IS_SEQ_POLYLINE (seq) (CV_SEQ_KIND(seq) == CV_SEQ_KIND_CURVE && CV_IS_SEQ_POINT_SET(seq))
Definition at line 1490 of file cxtypes.h.
#define CV_IS_SEQ_SIMPLE (seq)
Value:
((((seq)->flags & CV_SEQ_FLAG_SIMPLE) != 0) || \
                                    CV_IS_SEQ_CONVEX(seq))
Definition at line 1480 of file cxtypes.h.
#define CV_IS_SET (set) ((set) != NULL && (((CvSeq*)(set))->flags & CV_MAGIC_MASK) == CV_SET_MAGIC_VAL)
Definition at line 1404 of file cxtypes.h.
#define CV_IS_SET_ELEM (ptr) (((CvSetElem*)(ptr))->flags >= 0)
Definition at line 1302 of file cxtypes.h.
Referenced by cvGetSetElem().
#define CV_IS_SPARSE_HIST (hist) CV_IS_SPARSE_MAT((hist)->bins)
Definition at line 866 of file cxtypes.h.
#define CV_IS_SPARSE_MAT (mat) CV_IS_SPARSE_MAT_HDR(mat)
Definition at line 805 of file cxtypes.h.
#define CV_IS_SPARSE_MAT_HDR (mat)
Value:
((mat) != NULL && \
    (((const CvSparseMat*)(mat))->type & CV_MAGIC_MASK) == CV_SPARSE_MAT_MAGIC_VAL)
Definition at line 801 of file cxtypes.h.
#define CV_IS_STORAGE (storage)
Value:
((storage) != NULL &&       \
    (((CvMemStorage*)(storage))->signature & CV_MAGIC_MASK) == CV_STORAGE_MAGIC_VAL)
Definition at line 1210 of file cxtypes.h.
#define CV_IS_SUBDIV2D (seq) (CV_IS_SET(seq) && CV_SEQ_KIND((CvSet*)(seq)) == CV_SEQ_KIND_SUBDIV2D)
Definition at line 1515 of file cxtypes.h.
#define CV_IS_TEMP_MAT (flags) ((flags) & CV_MAT_TEMP_FLAG)
Definition at line 571 of file cxtypes.h.
#define CV_IS_UNIFORM_HIST (hist) (((hist)->type & CV_HIST_UNIFORM_FLAG) != 0)
Definition at line 863 of file cxtypes.h.
#define CV_LOG2 0.69314718055994530941723212145818
Definition at line 203 of file cxtypes.h.
#define CV_MAGIC_MASK 0xFFFF0000
Definition at line 573 of file cxtypes.h.
#define CV_MAKE_TYPE CV_MAKETYPE
Definition at line 505 of file cxtypes.h.
#define CV_MAKETYPE (depth, cn) (CV_MAT_DEPTH(depth) + (((cn)-1) << CV_CN_SHIFT))
Definition at line 504 of file cxtypes.h.
#define CV_MAT_CN (flags) ((((flags) & CV_MAT_CN_MASK) >> CV_CN_SHIFT) + 1)
Definition at line 562 of file cxtypes.h.
#define CV_MAT_CN_MASK ((CV_CN_MAX - 1) << CV_CN_SHIFT)
Definition at line 561 of file cxtypes.h.
#define CV_MAT_CONT_FLAG (1 << CV_MAT_CONT_FLAG_SHIFT)
Definition at line 566 of file cxtypes.h.
Referenced by cvMat().
#define CV_MAT_CONT_FLAG_SHIFT 14
Definition at line 565 of file cxtypes.h.
#define CV_MAT_DEPTH (flags) ((flags) & CV_MAT_DEPTH_MASK)
Definition at line 502 of file cxtypes.h.
Referenced by cvIplDepth(), and cvMat().
#define CV_MAT_DEPTH_MASK (CV_DEPTH_MAX - 1)
Definition at line 501 of file cxtypes.h.
#define CV_MAT_ELEM (mat, elemtype, row, col) (*(elemtype*)CV_MAT_ELEM_PTR_FAST(mat, row, col, sizeof(elemtype)))
Definition at line 686 of file cxtypes.h.
#define CV_MAT_ELEM_PTR (mat, row, col) CV_MAT_ELEM_PTR_FAST(mat, row, col, CV_ELEM_SIZE((mat).type))
Definition at line 683 of file cxtypes.h.
#define CV_MAT_ELEM_PTR_FAST (mat, row, col, pix_size)
Value:
(assert((unsigned)(row) < (unsigned)(mat).rows &&   \
             (unsigned)(col) < (unsigned)(mat).cols ),   \
     (mat).data.ptr + (size_t)(mat).step*(row) + (pix_size)*(col))
Definition at line 678 of file cxtypes.h.
#define CV_MAT_MAGIC_VAL 0x42420000
Definition at line 574 of file cxtypes.h.
Referenced by cvMat().
#define CV_MAT_TEMP_FLAG (1 << CV_MAT_TEMP_FLAG_SHIFT)
Definition at line 570 of file cxtypes.h.
#define CV_MAT_TEMP_FLAG_SHIFT 15
Definition at line 569 of file cxtypes.h.
#define CV_MAT_TYPE (flags) ((flags) & CV_MAT_TYPE_MASK)
Definition at line 564 of file cxtypes.h.
Referenced by cvMat(), cvmGet(), and cvmSet().
#define CV_MAT_TYPE_MASK (CV_DEPTH_MAX*CV_CN_MAX - 1)
Definition at line 563 of file cxtypes.h.
#define CV_MATND_MAGIC_VAL 0x42430000
Definition at line 737 of file cxtypes.h.
#define CV_MAX_DIM 32
Definition at line 740 of file cxtypes.h.
#define CV_MAX_DIM_HEAP (1 << 16)
Definition at line 741 of file cxtypes.h.
#define CV_NEXT_GRAPH_EDGE (edge, vertex)
Value:
(assert((edge)->vtx[0] == (vertex) || (edge)->vtx[1] == (vertex)),  \
      (edge)->next[(edge)->vtx[1] == (vertex)])
Definition at line 1657 of file cxtypes.h.
#define CV_NEXT_SEQ_ELEM (elem_size, reader)
Value:
{                                                             \
    if( ((reader).ptr += (elem_size)) >= (reader).block_max ) \
    {                                                         \
        cvChangeSeqBlock( &(reader), 1 );                     \
    }                                                         \
}
Definition at line 1593 of file cxtypes.h.
#define CV_NODE_EMPTY 32
Definition at line 1714 of file cxtypes.h.
#define CV_NODE_FLOAT CV_NODE_REAL
Definition at line 1701 of file cxtypes.h.
#define CV_NODE_FLOW 8
Definition at line 1712 of file cxtypes.h.
#define CV_NODE_HAS_NAME (flags) (((flags) & CV_NODE_NAMED) != 0)
Definition at line 1726 of file cxtypes.h.
#define CV_NODE_IDX (mat, node) ((int*)((uchar*)(node) + (mat)->idxoffset))
Definition at line 826 of file cxtypes.h.
#define CV_NODE_INT 1
Definition at line 1698 of file cxtypes.h.
#define CV_NODE_INTEGER CV_NODE_INT
Definition at line 1699 of file cxtypes.h.
#define CV_NODE_IS_COLLECTION (flags) (CV_NODE_TYPE(flags) >= CV_NODE_SEQ)
Definition at line 1722 of file cxtypes.h.
#define CV_NODE_IS_EMPTY (flags) (((flags) & CV_NODE_EMPTY) != 0)
Definition at line 1724 of file cxtypes.h.
#define CV_NODE_IS_FLOW (flags) (((flags) & CV_NODE_FLOW) != 0)
Definition at line 1723 of file cxtypes.h.
#define CV_NODE_IS_INT (flags) (CV_NODE_TYPE(flags) == CV_NODE_INT)
Definition at line 1717 of file cxtypes.h.
Referenced by cvReadInt(), and cvReadReal().
#define CV_NODE_IS_MAP (flags) (CV_NODE_TYPE(flags) == CV_NODE_MAP)
Definition at line 1721 of file cxtypes.h.
#define CV_NODE_IS_REAL (flags) (CV_NODE_TYPE(flags) == CV_NODE_REAL)
Definition at line 1718 of file cxtypes.h.
Referenced by cvReadInt(), and cvReadReal().
#define CV_NODE_IS_SEQ (flags) (CV_NODE_TYPE(flags) == CV_NODE_SEQ)
Definition at line 1720 of file cxtypes.h.
#define CV_NODE_IS_STRING (flags) (CV_NODE_TYPE(flags) == CV_NODE_STRING)
Definition at line 1719 of file cxtypes.h.
Referenced by cvReadString().
#define CV_NODE_IS_USER (flags) (((flags) & CV_NODE_USER) != 0)
Definition at line 1725 of file cxtypes.h.
#define CV_NODE_MAP 6
Definition at line 1706 of file cxtypes.h.
#define CV_NODE_NAMED 64
Definition at line 1715 of file cxtypes.h.
#define CV_NODE_NONE 0
Definition at line 1697 of file cxtypes.h.
#define CV_NODE_REAL 2
Definition at line 1700 of file cxtypes.h.
#define CV_NODE_REF 4
Definition at line 1704 of file cxtypes.h.
#define CV_NODE_SEQ 5
Definition at line 1705 of file cxtypes.h.
#define CV_NODE_SEQ_IS_SIMPLE (seq) (((seq)->flags & CV_NODE_SEQ_SIMPLE) != 0)
Definition at line 1729 of file cxtypes.h.
#define CV_NODE_SEQ_SIMPLE 256
Definition at line 1728 of file cxtypes.h.
#define CV_NODE_STR 3
Definition at line 1702 of file cxtypes.h.
#define CV_NODE_STRING CV_NODE_STR
Definition at line 1703 of file cxtypes.h.
#define CV_NODE_TYPE (flags) ((flags) & CV_NODE_TYPE_MASK)
Definition at line 1709 of file cxtypes.h.
#define CV_NODE_TYPE_MASK 7
Definition at line 1707 of file cxtypes.h.
#define CV_NODE_USER 16
Definition at line 1713 of file cxtypes.h.
#define CV_NODE_VAL (mat, node) ((void*)((uchar*)(node) + (mat)->valoffset))
Definition at line 825 of file cxtypes.h.
#define CV_ORIENTED_GRAPH (CV_SEQ_KIND_GRAPH|CV_GRAPH_FLAG_ORIENTED)
Definition at line 1446 of file cxtypes.h.
#define CV_PI 3.1415926535897932384626433832795
Definition at line 202 of file cxtypes.h.
#define CV_PREV_POINT (reader) (*((CvPoint*)((reader).prev_elem)))
Definition at line 1641 of file cxtypes.h.
#define CV_PREV_SEQ_ELEM (elem_size, reader)
Value:
{                                                            \
    if( ((reader).ptr -= (elem_size)) < (reader).block_min ) \
    {                                                        \
        cvChangeSeqBlock( &(reader), -1 );                   \
    }                                                        \
}
Definition at line 1603 of file cxtypes.h.
#define CV_READ_CHAIN_POINT (_pt, reader)
Value:
{                                                                       \
    (_pt) = (reader).pt;                                                \
    if( (reader).ptr )                                                  \
    {                                                                   \
        CV_READ_SEQ_ELEM( (reader).code, (reader));                     \
        assert( ((reader).code & ~7) == 0 );                            \
        (reader).pt.x += (reader).deltas[(int)(reader).code][0];        \
        (reader).pt.y += (reader).deltas[(int)(reader).code][1];        \
    }                                                                   \
}
Definition at line 1628 of file cxtypes.h.
#define CV_READ_EDGE (pt1, pt2, reader)
Value:
{                                                      \
    assert( sizeof(pt1) == sizeof(CvPoint) &&          \
            sizeof(pt2) == sizeof(CvPoint) &&          \
            reader.seq->elem_size == sizeof(CvPoint)); \
    (pt1) = CV_PREV_POINT( reader );                   \
    (pt2) = CV_CURRENT_POINT( reader );                \
    (reader).prev_elem = (reader).ptr;                 \
    CV_NEXT_SEQ_ELEM( sizeof(CvPoint), (reader));      \
}
Definition at line 1643 of file cxtypes.h.
#define CV_READ_SEQ_ELEM (elem, reader)
Value:
{                                                              \
    assert( (reader).seq->elem_size == sizeof(elem));          \
    memcpy( &(elem), (reader).ptr, sizeof((elem)));            \
    CV_NEXT_SEQ_ELEM( sizeof(elem), reader )                   \
}
Definition at line 1612 of file cxtypes.h.
#define CV_REV_READ_SEQ_ELEM (elem, reader)
Value:
{                                                                \
    assert( (reader).seq->elem_size == sizeof(elem));            \
    memcpy(&(elem), (reader).ptr, sizeof((elem)));               \
    CV_PREV_SEQ_ELEM( sizeof(elem), reader )                     \
}
Definition at line 1620 of file cxtypes.h.
#define CV_SEQ_CHAIN (CV_SEQ_KIND_CURVE | CV_SEQ_ELTYPE_CODE)
Definition at line 1457 of file cxtypes.h.
#define CV_SEQ_CHAIN_CONTOUR (CV_SEQ_FLAG_CLOSED | CV_SEQ_CHAIN)
Definition at line 1458 of file cxtypes.h.
#define CV_SEQ_CONNECTED_COMP (CV_SEQ_KIND_GENERIC | CV_SEQ_ELTYPE_CONNECTED_COMP)
Definition at line 1464 of file cxtypes.h.
#define CV_SEQ_CONTOUR CV_SEQ_POLYGON
Definition at line 1453 of file cxtypes.h.
#define CV_SEQ_ELEM (seq, elem_type, index)
Value:
/* assert gives some guarantee that <seq> parameter is valid */  \
(assert(sizeof((seq)->first[0]) == sizeof(CvSeqBlock) &&      \
    (seq)->elem_size == sizeof(elem_type)),                      \
    (elem_type*)((seq)->first && (unsigned)index <               \
    (unsigned)((seq)->first->count) ?                            \
    (seq)->first->data + (index) * sizeof(elem_type) :           \
    cvGetSeqElem( (CvSeq*)(seq), (index) )))
Definition at line 1558 of file cxtypes.h.
#define CV_SEQ_ELTYPE (seq) ((seq)->flags & CV_SEQ_ELTYPE_MASK)
Definition at line 1469 of file cxtypes.h.
#define CV_SEQ_ELTYPE_BITS 9
Definition at line 1407 of file cxtypes.h.
#define CV_SEQ_ELTYPE_CODE CV_8UC1
Definition at line 1411 of file cxtypes.h.
#define CV_SEQ_ELTYPE_CONNECTED_COMP 0
Definition at line 1419 of file cxtypes.h.
#define CV_SEQ_ELTYPE_GENERIC 0
Definition at line 1412 of file cxtypes.h.
#define CV_SEQ_ELTYPE_GRAPH_EDGE 0
Definition at line 1416 of file cxtypes.h.
#define CV_SEQ_ELTYPE_GRAPH_VERTEX 0
Definition at line 1417 of file cxtypes.h.
#define CV_SEQ_ELTYPE_INDEX CV_32SC1
Definition at line 1415 of file cxtypes.h.
#define CV_SEQ_ELTYPE_MASK ((1 << CV_SEQ_ELTYPE_BITS) - 1)
Definition at line 1408 of file cxtypes.h.
#define CV_SEQ_ELTYPE_POINT CV_32SC2
Definition at line 1410 of file cxtypes.h.
#define CV_SEQ_ELTYPE_POINT3D CV_32FC3
Definition at line 1420 of file cxtypes.h.
#define CV_SEQ_ELTYPE_PPOINT CV_SEQ_ELTYPE_PTR
Definition at line 1414 of file cxtypes.h.
#define CV_SEQ_ELTYPE_PTR CV_USRTYPE1
Definition at line 1413 of file cxtypes.h.
#define CV_SEQ_ELTYPE_TRIAN_ATR 0
Definition at line 1418 of file cxtypes.h.
#define CV_SEQ_FLAG_CLOSED (1 << CV_SEQ_FLAG_SHIFT)
Definition at line 1437 of file cxtypes.h.
#define CV_SEQ_FLAG_CONVEX (4 << CV_SEQ_FLAG_SHIFT)
Definition at line 1439 of file cxtypes.h.
#define CV_SEQ_FLAG_HOLE (8 << CV_SEQ_FLAG_SHIFT)
Definition at line 1440 of file cxtypes.h.
#define CV_SEQ_FLAG_SHIFT (CV_SEQ_KIND_BITS + CV_SEQ_ELTYPE_BITS)
Definition at line 1434 of file cxtypes.h.
#define CV_SEQ_FLAG_SIMPLE (2 << CV_SEQ_FLAG_SHIFT)
Definition at line 1438 of file cxtypes.h.
#define CV_SEQ_INDEX (CV_SEQ_KIND_GENERIC | CV_SEQ_ELTYPE_INDEX)
Definition at line 1467 of file cxtypes.h.
#define CV_SEQ_KIND (seq) ((seq)->flags & CV_SEQ_KIND_MASK)
Definition at line 1470 of file cxtypes.h.
#define CV_SEQ_KIND_BIN_TREE (2 << CV_SEQ_ELTYPE_BITS)
Definition at line 1428 of file cxtypes.h.
#define CV_SEQ_KIND_BITS 3
Definition at line 1422 of file cxtypes.h.
#define CV_SEQ_KIND_CURVE (1 << CV_SEQ_ELTYPE_BITS)
Definition at line 1427 of file cxtypes.h.
#define CV_SEQ_KIND_GENERIC (0 << CV_SEQ_ELTYPE_BITS)
Definition at line 1426 of file cxtypes.h.
#define CV_SEQ_KIND_GRAPH (3 << CV_SEQ_ELTYPE_BITS)
Definition at line 1431 of file cxtypes.h.
#define CV_SEQ_KIND_MASK (((1 << CV_SEQ_KIND_BITS) - 1)<<CV_SEQ_ELTYPE_BITS)
Definition at line 1423 of file cxtypes.h.
#define CV_SEQ_KIND_SUBDIV2D (4 << CV_SEQ_ELTYPE_BITS)
Definition at line 1432 of file cxtypes.h.
Referenced by cvCreateSubdivDelaunay2D().
#define CV_SEQ_MAGIC_VAL 0x42990000
Definition at line 1398 of file cxtypes.h.
#define CV_SEQ_POINT3D_SET (CV_SEQ_KIND_GENERIC| CV_SEQ_ELTYPE_POINT3D)
Definition at line 1450 of file cxtypes.h.
#define CV_SEQ_POINT_SET (CV_SEQ_KIND_GENERIC| CV_SEQ_ELTYPE_POINT)
Definition at line 1449 of file cxtypes.h.
#define CV_SEQ_POLYGON (CV_SEQ_FLAG_CLOSED | CV_SEQ_POLYLINE)
Definition at line 1452 of file cxtypes.h.
#define CV_SEQ_POLYGON_TREE (CV_SEQ_KIND_BIN_TREE | CV_SEQ_ELTYPE_TRIAN_ATR)
Definition at line 1461 of file cxtypes.h.
#define CV_SEQ_POLYLINE (CV_SEQ_KIND_CURVE | CV_SEQ_ELTYPE_POINT)
Definition at line 1451 of file cxtypes.h.
#define CV_SEQ_READER_FIELDS ()
Value:
int          header_size;                                       \
    CvSeq*       seq;        /* sequence, beign read */             \
    CvSeqBlock*  block;      /* current block */                    \
    schar*       ptr;        /* pointer to element be read next */  \
    schar*       block_min;  /* pointer to the beginning of block */\
    schar*       block_max;  /* pointer to the end of block */      \
    int          delta_index;/* = seq->first->start_index   */      \
    schar*       prev_elem;
Definition at line 1537 of file cxtypes.h.
#define CV_SEQ_SIMPLE_POLYGON (CV_SEQ_FLAG_SIMPLE | CV_SEQ_POLYGON)
Definition at line 1454 of file cxtypes.h.
#define CV_SEQ_WRITER_FIELDS ()
Value:
int          header_size;                                      \
    CvSeq*       seq;        /* the sequence written */            \
    CvSeqBlock*  block;      /* current block */                   \
    schar*       ptr;        /* pointer to free space */           \
    schar*       block_min;  /* pointer to the beginning of block*/\
    schar*       block_max;
Definition at line 1522 of file cxtypes.h.
#define CV_SEQUENCE_FIELDS ()
Value:
CV_TREE_NODE_FIELDS(CvSeq);                                           \
    int       total;          /* Total number of elements.            */  \
    int       elem_size;      /* Size of sequence element in bytes.   */  \
    schar*    block_max;      /* Maximal bound of the last block.     */  \
    schar*    ptr;            /* Current write pointer.               */  \
    int       delta_elems;    /* Grow seq this many at a time.        */  \
    CvMemStorage* storage;    /* Where the seq is stored.             */  \
    CvSeqBlock* free_blocks;  /* Free blocks list.                    */  \
    CvSeqBlock* first;
Definition at line 1249 of file cxtypes.h.
#define CV_SET_ELEM_FIELDS (elem_type)
Value:
int  flags;                         \
    struct elem_type* next_free;
Definition at line 1276 of file cxtypes.h.
#define CV_SET_ELEM_FREE_FLAG (1 << (sizeof(int)*8-1))
Definition at line 1299 of file cxtypes.h.
Referenced by cvSetRemoveByPtr().
#define CV_SET_ELEM_IDX_MASK ((1 << 26) - 1)
Definition at line 1298 of file cxtypes.h.
Referenced by cvSetNew(), and cvSetRemoveByPtr().
#define CV_SET_FIELDS ()
Value:
CV_SEQUENCE_FIELDS()     \
    CvSetElem* free_elems;   \
    int active_count;
Definition at line 1286 of file cxtypes.h.
#define CV_SET_MAGIC_VAL 0x42980000
Definition at line 1403 of file cxtypes.h.
#define CV_SIGN (a) CV_CMP((a),0)
Definition at line 227 of file cxtypes.h.
#define CV_SPARSE_MAT_MAGIC_VAL 0x42440000
Definition at line 780 of file cxtypes.h.
#define CV_SSE2 0
Definition at line 88 of file cxtypes.h.
#define CV_STDCALL
Definition at line 119 of file cxtypes.h.
#define CV_STORAGE_APPEND 2
Definition at line 1675 of file cxtypes.h.
#define CV_STORAGE_MAGIC_VAL 0x42890000
Definition at line 1197 of file cxtypes.h.
#define CV_STORAGE_READ 0
Definition at line 1671 of file cxtypes.h.
#define CV_STORAGE_WRITE 1
Definition at line 1672 of file cxtypes.h.
#define CV_STORAGE_WRITE_BINARY CV_STORAGE_WRITE
Definition at line 1674 of file cxtypes.h.
#define CV_STORAGE_WRITE_TEXT CV_STORAGE_WRITE
Definition at line 1673 of file cxtypes.h.
#define CV_SWAP (a, b, t) ((t) = (a), (a) = (b), (b) = (t))
Definition at line 205 of file cxtypes.h.
#define CV_TERMCRIT_EPS 2
Definition at line 922 of file cxtypes.h.
#define CV_TERMCRIT_ITER 1
Definition at line 920 of file cxtypes.h.
#define CV_TERMCRIT_NUMBER CV_TERMCRIT_ITER
Definition at line 921 of file cxtypes.h.
#define CV_TREE_NODE_FIELDS (node_type)
Value:
int       flags;             /* Miscellaneous flags.     */      \
    int       header_size;       /* Size of sequence header. */      \
    struct    node_type* h_prev; /* Previous sequence.       */      \
    struct    node_type* h_next; /* Next sequence.           */      \
    struct    node_type* v_prev; /* 2nd previous sequence.   */      \
    struct    node_type* v_next
Definition at line 1237 of file cxtypes.h.
#define CV_TYPE_NAME_GRAPH "opencv-graph"
Definition at line 1369 of file cxtypes.h.
#define CV_TYPE_NAME_IMAGE "opencv-image"
Definition at line 463 of file cxtypes.h.
#define CV_TYPE_NAME_MAT "opencv-matrix"
Definition at line 575 of file cxtypes.h.
#define CV_TYPE_NAME_MATND "opencv-nd-matrix"
Definition at line 738 of file cxtypes.h.
#define CV_TYPE_NAME_SEQ "opencv-sequence"
Definition at line 1266 of file cxtypes.h.
#define CV_TYPE_NAME_SEQ_TREE "opencv-sequence-tree"
Definition at line 1267 of file cxtypes.h.
#define CV_TYPE_NAME_SPARSE_MAT "opencv-sparse-matrix"
Definition at line 781 of file cxtypes.h.
#define CV_WHOLE_ARR cvSlice(0, 0x3fffffff)
Definition at line 559 of file cxtypes.h.
#define CV_WHOLE_SEQ cvSlice(0, CV_WHOLE_SEQ_END_INDEX)
Definition at line 1145 of file cxtypes.h.
#define CV_WHOLE_SEQ_END_INDEX 0x3fffffff
Definition at line 1144 of file cxtypes.h.
#define CV_WRITE_SEQ_ELEM (elem, writer)
Value:
{                                                     \
    assert( (writer).seq->elem_size == sizeof(elem)); \
    if( (writer).ptr >= (writer).block_max )          \
    {                                                 \
        cvCreateSeqBlock( &writer);                   \
    }                                                 \
    assert( (writer).ptr <= (writer).block_max - sizeof(elem));\
    memcpy((writer).ptr, &(elem), sizeof(elem));      \
    (writer).ptr += sizeof(elem);                     \
}
Definition at line 1579 of file cxtypes.h.
#define CV_WRITE_SEQ_ELEM_VAR (elem_ptr, writer)
Value:
{                                                     \
    if( (writer).ptr >= (writer).block_max )          \
    {                                                 \
        cvCreateSeqBlock( &writer);                   \
    }                                                 \
    memcpy((writer).ptr, elem_ptr, (writer).seq->elem_size);\
    (writer).ptr += (writer).seq->elem_size;          \
}
Definition at line 1569 of file cxtypes.h.
#define CVAPI (rettype) CV_EXTERN_C CV_EXPORTS rettype CV_CDECL
Definition at line 157 of file cxtypes.h.
#define cvInvSqrt (value) ((float)(1./sqrt(value)))
Definition at line 286 of file cxtypes.h.
#define cvSqrt (value) ((float)sqrt(value))
Definition at line 287 of file cxtypes.h.
#define IPL2CV_DEPTH (depth)
Value:
((((CV_8U)+(CV_16U<<4)+(CV_32F<<8)+(CV_64F<<16)+(CV_8S<<20)+ \
    (CV_16S<<24)+(CV_32S<<28)) >> ((((depth) & 0xF0) >> 2) + \
    (((depth) & IPL_DEPTH_SIGN) ? 20 : 0))) & 15)
Definition at line 651 of file cxtypes.h.
#define IPL_ALIGN_16BYTES 16
Definition at line 374 of file cxtypes.h.
#define IPL_ALIGN_32BYTES 32
Definition at line 375 of file cxtypes.h.
#define IPL_ALIGN_4BYTES 4
Definition at line 372 of file cxtypes.h.
#define IPL_ALIGN_8BYTES 8
Definition at line 373 of file cxtypes.h.
#define IPL_ALIGN_DWORD IPL_ALIGN_4BYTES
Definition at line 377 of file cxtypes.h.
#define IPL_ALIGN_QWORD IPL_ALIGN_8BYTES
Definition at line 378 of file cxtypes.h.
#define IPL_BORDER_CONSTANT 0
Definition at line 380 of file cxtypes.h.
#define IPL_BORDER_REFLECT 2
Definition at line 382 of file cxtypes.h.
#define IPL_BORDER_REFLECT_101 4
Definition at line 460 of file cxtypes.h.
#define IPL_BORDER_REPLICATE 1
Definition at line 381 of file cxtypes.h.
#define IPL_BORDER_WRAP 3
Definition at line 383 of file cxtypes.h.
#define IPL_DATA_ORDER_PIXEL 0
Definition at line 366 of file cxtypes.h.
#define IPL_DATA_ORDER_PLANE 1
Definition at line 367 of file cxtypes.h.
#define IPL_DEPTH_16S (IPL_DEPTH_SIGN|16)
Definition at line 363 of file cxtypes.h.
#define IPL_DEPTH_16U 16
Definition at line 359 of file cxtypes.h.
#define IPL_DEPTH_1U 1
Definition at line 357 of file cxtypes.h.
#define IPL_DEPTH_32F 32
Definition at line 360 of file cxtypes.h.
#define IPL_DEPTH_32S (IPL_DEPTH_SIGN|32)
Definition at line 364 of file cxtypes.h.
#define IPL_DEPTH_64F 64
Definition at line 473 of file cxtypes.h.
#define IPL_DEPTH_8S (IPL_DEPTH_SIGN| 8)
Definition at line 362 of file cxtypes.h.
#define IPL_DEPTH_8U 8
Definition at line 358 of file cxtypes.h.
#define IPL_DEPTH_SIGN 0x80000000
Definition at line 355 of file cxtypes.h.
Referenced by cvIplDepth().
#define IPL_IMAGE_DATA 2
Definition at line 454 of file cxtypes.h.
#define IPL_IMAGE_HEADER 1
Definition at line 453 of file cxtypes.h.
#define IPL_IMAGE_MAGIC_VAL ((int)sizeof(IplImage))
Definition at line 462 of file cxtypes.h.
#define IPL_IMAGE_ROI 4
Definition at line 455 of file cxtypes.h.
#define IPL_ORIGIN_BL 1
Definition at line 370 of file cxtypes.h.
#define IPL_ORIGIN_TL 0
Definition at line 369 of file cxtypes.h.
#define MAX (a, b) ((a) < (b) ? (b) : (a))
Definition at line 212 of file cxtypes.h.
#define MIN (a, b) ((a) > (b) ? (b) : (a))
Definition at line 208 of file cxtypes.h.
Typedef Documentation
typedef union Cv32suf Cv32suf
typedef union Cv64suf Cv64suf
typedef void CvArr
Definition at line 180 of file cxtypes.h.
typedef struct CvAttrList CvAttrList
typedef struct CvBox2D CvBox2D
typedef struct CvChain CvChain
typedef void*(CV_CDECL * CvCloneFunc)(const void *struct_ptr)
Definition at line 1775 of file cxtypes.h.
typedef struct CvContour CvContour
typedef struct CvFileNode CvFileNode
typedef struct CvGenericHash CvFileNodeHash
Definition at line 1748 of file cxtypes.h.
typedef struct CvFileStorage CvFileStorage
Definition at line 1668 of file cxtypes.h.
typedef struct CvGraph CvGraph
typedef struct CvGraphEdge CvGraphEdge
typedef struct CvGraphVtx CvGraphVtx
typedef struct CvGraphVtx2D CvGraphVtx2D
typedef struct CvHistogram CvHistogram
typedef int CvHistType
Definition at line 832 of file cxtypes.h.
typedef int(CV_CDECL * CvIsInstanceFunc)(const void *struct_ptr)
Definition at line 1770 of file cxtypes.h.
typedef struct CvLineIterator CvLineIterator
typedef struct CvMat CvMat
typedef struct CvMatND CvMatND
typedef struct CvMemBlock CvMemBlock
typedef struct CvMemStorage CvMemStorage
typedef struct CvMemStoragePos CvMemStoragePos
typedef struct CvModuleInfo CvModuleInfo
typedef struct CvPluginFuncInfo CvPluginFuncInfo
typedef struct CvPoint CvPoint
typedef struct CvPoint2D32f CvPoint2D32f
typedef struct CvPoint2D64f CvPoint2D64f
typedef CvContour CvPoint2DSeq
Definition at line 1392 of file cxtypes.h.
typedef struct CvPoint3D32f CvPoint3D32f
typedef struct CvPoint3D64f CvPoint3D64f
typedef void*(CV_CDECL * CvReadFunc)(CvFileStorage *storage, CvFileNode *node)
Definition at line 1772 of file cxtypes.h.
typedef struct CvRect CvRect
typedef void(CV_CDECL * CvReleaseFunc)(void **struct_dblptr)
Definition at line 1771 of file cxtypes.h.
typedef uint64 CvRNG
Definition at line 321 of file cxtypes.h.
typedef struct CvScalar CvScalar
typedef struct CvSeq CvSeq
typedef struct CvSeqBlock CvSeqBlock
typedef struct CvSeqReader CvSeqReader
typedef struct CvSeqWriter CvSeqWriter
typedef struct CvSet CvSet
typedef struct CvSetElem CvSetElem
typedef struct CvSize2D32f CvSize2D32f
typedef struct CvSlice CvSlice
typedef struct CvSparseMat CvSparseMat
typedef struct CvSparseMatIterator CvSparseMatIterator
typedef struct CvSparseNode CvSparseNode
typedef struct CvString CvString
typedef struct CvStringHashNode CvStringHashNode
typedef struct CvTermCriteria CvTermCriteria
typedef struct CvTypeInfo CvTypeInfo
typedef void(CV_CDECL * CvWriteFunc)(CvFileStorage *storage, const char *name, const void *struct_ptr, CvAttrList attributes)
Definition at line 1773 of file cxtypes.h.
typedef int64_t int64
Definition at line 164 of file cxtypes.h.
typedef struct _IplConvKernel IplConvKernel
typedef struct _IplConvKernelFP IplConvKernelFP
typedef struct _IplImage IplImage
typedef struct _IplROI IplROI
typedef struct _IplTileInfo IplTileInfo
Definition at line 420 of file cxtypes.h.
typedef signed char schar
Definition at line 173 of file cxtypes.h.
typedef unsigned char uchar
Definition at line 169 of file cxtypes.h.
typedef uint64_t uint64
Definition at line 165 of file cxtypes.h.
typedef unsigned short ushort
Definition at line 170 of file cxtypes.h.
Function Documentation
CV_INLINE CvAttrList cvAttrList (const char **attr CV_DEFAULTNULL, CvAttrList *next CV_DEFAULTNULL)
Definition at line 1685 of file cxtypes.h.
References CvAttrList::attr, next, and CvAttrList::next.
CV_INLINE int cvCeil (double value)
Definition at line 269 of file cxtypes.h.
References cvRound(), Cv32suf::f, Cv32suf::i, and value.
CV_INLINE int cvFloor (double value)
Definition at line 251 of file cxtypes.h.
References cvRound(), Cv32suf::f, Cv32suf::i, and value.
CV_INLINE int cvIplDepth (int type)
Definition at line 725 of file cxtypes.h.
References CV_16S, CV_32S, CV_8S, CV_ELEM_SIZE1, CV_MAT_DEPTH, depth, and IPL_DEPTH_SIGN.
CV_INLINE int cvIsInf (double value)
Definition at line 304 of file cxtypes.h.
References Cv64suf::f, Cv64suf::u, and value.
CV_INLINE int cvIsNaN (double value)
Definition at line 289 of file cxtypes.h.
References Cv64suf::f, Cv64suf::u, and value.
CV_INLINE CvMat cvMat (int rows, int cols, int type, void *data CV_DEFAULTNULL)
Definition at line 660 of file cxtypes.h.
References cols, CvMat::cols, CV_64F, CV_ELEM_SIZE, CV_MAT_CONT_FLAG, CV_MAT_DEPTH, CV_MAT_MAGIC_VAL, CV_MAT_TYPE, CvMat::data, data, CvMat::hdr_refcount, CvMat::ptr, CvMat::refcount, rows, CvMat::rows, CvMat::step, CvMat::type, and type.
Referenced by cvbCartToPolar(), cvbFastArctan(), cvbFastExp(), cvbFastLog(), cvbInvSqrt(), cvbRand(), cvbReciprocal(), cvbSqrt(), cvCalcEMD(), cvCalibrateCamera(), cvCalibrateCamera_64d(), cvConvexHull(), cvFindExtrinsicCameraParams(), cvFindExtrinsicCameraParams_64d(), cvFindFundamentalMatrix(), cvFitEllipse(), cvFitLine2D(), cvFitLine3D(), cvHoughLines(), cvHoughLinesP(), cvHoughLinesSDiv(), cvKMeans(), cvMatArray(), cvMinAreaRect(), cvProject3D(), cvProjectPoints(), cvProjectPointsSimple(), and cvUnDistortOnce().
CV_INLINE double cvmGet (const CvMat * mat, int row, int col)
Definition at line 690 of file cxtypes.h.
References CvMat::cols, CV_32FC1, CV_64FC1, CV_MAT_TYPE, CvMat::data, CvMat::ptr, CvMat::rows, CvMat::step, CvMat::type, and type.
CV_INLINE void cvmSet (CvMat * mat, int row, int col, double value)
Definition at line 708 of file cxtypes.h.
References CvMat::cols, CV_32FC1, CV_64FC1, CV_MAT_TYPE, CvMat::data, CvMat::ptr, CvMat::rows, CvMat::step, CvMat::type, and type.
Referenced by cvFindFundamentalMatrix().
CV_INLINE CvPoint cvPoint (int x, int y)
Definition at line 956 of file cxtypes.h.
References CvPoint::x, and CvPoint::y.
CV_INLINE CvPoint2D32f cvPoint2D32f (double x, double y)
Definition at line 975 of file cxtypes.h.
References CvPoint2D32f::x, and CvPoint2D32f::y.
Referenced by cvPointTo32f().
CV_INLINE CvPoint2D64f cvPoint2D64f (double x, double y)
Definition at line 1031 of file cxtypes.h.
References CvPoint2D64f::x, and CvPoint2D64f::y.
CV_INLINE CvPoint3D32f cvPoint3D32f (double x, double y, double z)
Definition at line 1011 of file cxtypes.h.
References CvPoint3D32f::x, CvPoint3D32f::y, and CvPoint3D32f::z.
CV_INLINE CvPoint3D64f cvPoint3D64f (double x, double y, double z)
Definition at line 1051 of file cxtypes.h.
References CvPoint3D64f::x, CvPoint3D64f::y, and CvPoint3D64f::z.
CV_INLINE CvPoint cvPointFrom32f (CvPoint2D32f point)
Definition at line 992 of file cxtypes.h.
References cvRound(), CvPoint::x, CvPoint2D32f::x, CvPoint::y, and CvPoint2D32f::y.
Referenced by cvEllipseBox().
CV_INLINE CvPoint2D32f cvPointTo32f (CvPoint point)
Definition at line 986 of file cxtypes.h.
References cvPoint2D32f(), CvPoint::x, and CvPoint::y.
CV_INLINE unsigned cvRandInt (CvRNG * rng)
Definition at line 330 of file cxtypes.h.
References rng, temp, and U.
Referenced by cvRandReal().
CV_INLINE double cvRandReal (CvRNG * rng)
Definition at line 339 of file cxtypes.h.
References cvRandInt().
CV_INLINE CvScalar cvRealScalar (double val0)
Definition at line 1166 of file cxtypes.h.
References scalar, and CvScalar::val.
CV_INLINE CvRect cvRect (int x, int y, int width, int height)
Definition at line 887 of file cxtypes.h.
References height, CvRect::height, r, width, CvRect::width, CvRect::x, and CvRect::y.
Referenced by cvROIToRect().
CV_INLINE IplROI cvRectToROI (CvRect rect, int coi)
Definition at line 900 of file cxtypes.h.
References coi, _IplROI::coi, _IplROI::height, CvRect::height, roi, _IplROI::width, CvRect::width, CvRect::x, _IplROI::xOffset, CvRect::y, and _IplROI::yOffset.
CV_INLINE CvRNG cvRNG (int64 seed CV_DEFAULT-1)
Definition at line 323 of file cxtypes.h.
References rng.
CV_INLINE CvRect cvROIToRect (IplROI roi)
Definition at line 913 of file cxtypes.h.
References cvRect(), _IplROI::height, _IplROI::width, _IplROI::xOffset, and _IplROI::yOffset.
CV_INLINE int cvRound (double value)
Definition at line 229 of file cxtypes.h.
References value.
Referenced by cvCeil(), cvEllipseBox(), cvFloor(), cvPointFrom32f(), and cvReadInt().
CV_INLINE CvScalar cvScalar (double val0, double val1 CV_DEFAULT0, double val2 CV_DEFAULT0, double val3 CV_DEFAULT0)
Definition at line 1156 of file cxtypes.h.
References scalar, and CvScalar::val.
Referenced by cvSubS().
CV_INLINE CvScalar cvScalarAll (double val0123)
Definition at line 1174 of file cxtypes.h.
References scalar, and CvScalar::val.
CV_INLINE CvSize cvSize (int width, int height)
Definition at line 1072 of file cxtypes.h.
References height, CvSize::height, width, and CvSize::width.
CV_INLINE CvSize2D32f cvSize2D32f (double width, double height)
Definition at line 1090 of file cxtypes.h.
References CvSize2D32f::height, and CvSize2D32f::width.
CV_INLINE CvSlice cvSlice (int start, int end)
Definition at line 1135 of file cxtypes.h.
References end, CvSlice::end_index, slice, start, and CvSlice::start_index.
CV_INLINE CvTermCriteria cvTermCriteria (int type, int max_iter, double epsilon)
Definition at line 934 of file cxtypes.h.
References CvTermCriteria::epsilon, CvTermCriteria::max_iter, type, and CvTermCriteria::type.