lubyk: /Users/gaspard/git/lubyk/modules/lubyk/include/lubyk/msgpack.h File Reference
/Users/gaspard/git/lubyk/modules/lubyk/include/lubyk/msgpack.h File Reference
#include "lubyk.h"
Classes
struct msgpack_sbuffer
Typedefs
typedef struct msgpack_sbuffer msgpack_sbuffer
Functions
void msgpack_lua_to_bin (lua_State *L, msgpack_sbuffer **buffer, int skip_index=0)
int msgpack_bin_to_lua (lua_State *L, void *msg, size_t msg_len)
void free_msgpack_msg (void *data, void *buffer)
Typedef Documentation
typedef struct msgpack_sbuffer msgpack_sbuffer
Function Documentation
void free_msgpack_msg (void * data, void * buffer)
Referenced by zmq::Socket::request(), and zmq::Socket::send().
int msgpack_bin_to_lua (lua_State * L, void * msg, size_t msg_len)
Referenced by zmq::Socket::recv(), and zmq::Socket::request().
void msgpack_lua_to_bin (lua_State * L, msgpack_sbuffer ** buffer, int skip_index = 0)
Referenced by zmq::Socket::request(), and zmq::Socket::send().