lubyk: lk Namespace Reference
lk Namespace Reference
Classes
class Debug
class Finalizer
class Mutex
class Socket
class VideoIn
Functions
static int readable (const char *filename)
static const char * pushnexttemplate (lua_State *L, const char *path)
LuaStackSize findFile (lua_State *L)
Function Documentation
LuaStackSize lk::findFile (lua_State * L)
Definition at line 60 of file constants.h.
References filename, name, pushnexttemplate(), and readable().
static const char* lk::pushnexttemplate (lua_State * L, const char * path) [static]
Definition at line 47 of file constants.h.
Referenced by findFile().
static int lk::readable (const char * filename) [static]
Definition at line 39 of file constants.h.
Referenced by findFile().