lubyk: b2Vec2 Struct Reference
b2Vec2 Struct Reference
A 2D column vector.
#include <b2Math.h>
Public Member Functions
b2Vec2 ()
Default constructor does nothing (for performance).
b2Vec2 (float32 x, float32 y)
Construct using coordinates.
void SetZero ()
Set this vector to all zeros.
void Set (float32 x_, float32 y_)
Set this vector to some specified coordinates.
b2Vec2 operator- () const
Negate this vector.
float32 operator() (int32 i) const
Read from and indexed element.
float32 & operator() (int32 i)
Write to an indexed element.
void operator+= (const b2Vec2 &v)
Add a vector to this vector.
void operator-= (const b2Vec2 &v)
Subtract a vector from this vector.
void operator*= (float32 a)
Multiply this vector by a scalar.
float32 Length () const
Get the length of this vector (the norm).
float32 LengthSquared () const
float32 Normalize ()
Convert this vector into a unit vector. Returns the length.
bool IsValid () const
Does this vector contain finite coordinates?
b2Vec2 Skew () const
Get the skew vector such that dot(skew_vec, other) == cross(vec, other)
Public Attributes
float32 x
float32 y
Detailed Description
A 2D column vector.
Definition at line 64 of file b2Math.h.
Constructor & Destructor Documentation
b2Vec2::b2Vec2 () [inline]
Default constructor does nothing (for performance).
Definition at line 67 of file b2Math.h.
Referenced by Skew().
b2Vec2::b2Vec2 (float32 x, float32 y) [inline]
Construct using coordinates.
Definition at line 70 of file b2Math.h.
Member Function Documentation
bool b2Vec2::IsValid () const [inline]
Does this vector contain finite coordinates?
Definition at line 140 of file b2Math.h.
References b2IsValid().
Referenced by b2AABB::IsValid().
float32 b2Vec2::Length () const [inline]
Get the length of this vector (the norm).
Definition at line 112 of file b2Math.h.
References b2Sqrt.
Referenced by b2Distance(), and Normalize().
float32 b2Vec2::LengthSquared () const [inline]
Get the length squared. For performance, use this instead of b2Vec2::Length (if possible).
Definition at line 119 of file b2Math.h.
References y.
Referenced by b2DynamicTree::RayCast().
float32 b2Vec2::Normalize () [inline]
Convert this vector into a unit vector. Returns the length.
Definition at line 125 of file b2Math.h.
References b2_epsilon, Length(), and length.
Referenced by b2DynamicTree::RayCast().
float32 b2Vec2::operator() (int32 i) const [inline]
Read from and indexed element.
Definition at line 82 of file b2Math.h.
float32& b2Vec2::operator() (int32 i) [inline]
Write to an indexed element.
Definition at line 88 of file b2Math.h.
void b2Vec2::operator*= (float32 a) [inline]
Multiply this vector by a scalar.
Definition at line 106 of file b2Math.h.
References a.
void b2Vec2::operator+= (const b2Vec2 & v) [inline]
Add a vector to this vector.
Definition at line 94 of file b2Math.h.
References x, and y.
b2Vec2 b2Vec2::operator- () const [inline]
Negate this vector.
Definition at line 79 of file b2Math.h.
References Set().
void b2Vec2::operator-= (const b2Vec2 & v) [inline]
Subtract a vector from this vector.
Definition at line 100 of file b2Math.h.
References x, and y.
void b2Vec2::Set (float32 x_, float32 y_) [inline]
Set this vector to some specified coordinates.
Definition at line 76 of file b2Math.h.
Referenced by b2BodyDef::b2BodyDef(), b2DistanceJointDef::b2DistanceJointDef(), b2MouseJointDef::b2MouseJointDef(), b2PrismaticJointDef::b2PrismaticJointDef(), b2PulleyJointDef::b2PulleyJointDef(), b2RevoluteJointDef::b2RevoluteJointDef(), b2RopeJointDef::b2RopeJointDef(), b2WeldJointDef::b2WeldJointDef(), b2WheelJointDef::b2WheelJointDef(), and operator-().
void b2Vec2::SetZero () [inline]
Set this vector to all zeros.
Definition at line 73 of file b2Math.h.
Referenced by b2CircleShape::b2CircleShape(), b2FrictionJointDef::b2FrictionJointDef(), b2PolygonShape::b2PolygonShape(), b2PrismaticJointDef::b2PrismaticJointDef(), b2RopeDef::b2RopeDef(), b2WheelJointDef::b2WheelJointDef(), b2Body::SetAwake(), and b2Transform::SetIdentity().
b2Vec2 b2Vec2::Skew () const [inline]
Get the skew vector such that dot(skew_vec, other) == cross(vec, other)
Definition at line 146 of file b2Math.h.
References b2Vec2().
Member Data Documentation
float32 b2Vec2::x
Definition at line 151 of file b2Math.h.
Referenced by b2Abs(), b2Cross(), b2Dot(), b2EdgeShape::b2EdgeShape(), b2Mat22::b2Mat22(), b2Max(), b2Min(), b2Mul(), b2Mul22(), b2MulT(), b2TestOverlap(), b2AABB::Contains(), b2Mat22::GetInverse(), b2AABB::GetPerimeter(), b2AABB::IsValid(), operator*(), operator+(), operator+=(), operator-(), operator-=(), operator==(), b2Mat22::SetIdentity(), b2Mat22::SetZero(), and b2Mat22::Solve().
float32 b2Vec2::y
Definition at line 151 of file b2Math.h.
Referenced by b2Abs(), b2Cross(), b2Dot(), b2EdgeShape::b2EdgeShape(), b2Mat22::b2Mat22(), b2Max(), b2Min(), b2Mul(), b2Mul22(), b2MulT(), b2TestOverlap(), b2AABB::Contains(), b2Mat22::GetInverse(), b2AABB::GetPerimeter(), b2AABB::IsValid(), LengthSquared(), operator*(), operator+(), operator+=(), operator-(), operator-=(), operator==(), b2Mat22::SetIdentity(), b2Mat22::SetZero(), and b2Mat22::Solve().
The documentation for this struct was generated from the following file:
/Users/gaspard/git/lubyk/modules/b2/bind/b2Math.h